name: big-bear-mumble-server
services:
  app:
    image: mumblevoip/mumble-server:v1.4.230-6
    container_name: mumble-server
    hostname: mumble-server
    restart: on-failure
    ports:
      - '64738:64738'
      - 12083:64738/udp
    x-casaos:
      ports:
        - container: '64738'
          description:
            en_us: 'Container Port: 64738'
        - container: '64738'
          description:
            en_us: 'Container Port: 64738'
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Mumble is a free, open source, low latency, high quality voice chat application.
  tagline:
    en_us: Mumble Server
  developer: mumblevoip
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/mumble.png
  thumbnail: ''
  title:
    en_us: Mumble Server
  category: BigBearCasaOS
  port_map: '64738'

