name: big-bear-odoo
services:
  big-bear-odoo:
    container_name: big-bear-odoo
    image: odoo:19
    restart: unless-stopped
    user: root
    volumes:
      - /DATA/.docker/AppData/$AppID/data/etc:/etc/odoo
      - /DATA/.docker/AppData/$AppID/data/addons:/mnt/extra-addons
    ports:
      - '8069:8069'
    environment:
      - HOST=big-bear-odoo-db
      - USER=odoo
      - PASSWORD=a8d785b6-bc00-49cc-8675-d404093d1507
    networks:
      - big_bear_odoo_network
    x-casaos:
      envs:
        - container: HOST
          description:
            en_us: 'Container Variable: HOST'
        - container: USER
          description:
            en_us: 'Container Variable: USER'
        - container: PASSWORD
          description:
            en_us: 'Container Variable: PASSWORD'
      volumes:
        - container: /etc/odoo
          description:
            en_us: 'Container Path: /etc/odoo'
        - container: /mnt/extra-addons
          description:
            en_us: 'Container Path: /mnt/extra-addons'
      ports:
        - container: '8069'
          description:
            en_us: 'Container Port: 8069'
  big-bear-odoo-db:
    container_name: big-bear-odoo-db
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=a8d785b6-bc00-49cc-8675-d404093d1507
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data/postgresql:/var/lib/postgresql/data
    networks:
      - big_bear_odoo_network
    x-casaos:
      envs:
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
networks:
  big_bear_odoo_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-odoo
  description:
    en_us: Open-source business management software suite designed to streamline various aspects of business operations. With its modular structure, users can choose and integrate specific applications such as accounting, inventory, and sales. Odoo provides a user-friendly interface, scalability for businesses of all sizes, and is available in both community (free) and enterprise editions. Its integrated approach and customization options make it a popular choice for comprehensive ERP (Enterprise Resource Planning) solutions.
  tagline:
    en_us: Open-source business management software with modular applications for streamlined operations.
  developer: odoo
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/odoo/logo.jpg
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Documentation: https://community.bigbeartechworld.com/t/added-odoo-to-bigbearcasaos/1115?u=dragonfire1119
  title:
    en_us: Odoo
  category: BigBearCasaOS
  port_map: '8069'

