name: big-bear-phpmyadmin
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3
    container_name: big-bear-phpmyadmin
    environment:
      PMA_HOST: '[YOUR-CASAOS-IP]'
      PMA_PORT: '3306'
      PMA_USER: bigbear
      PMA_PASSWORD: password
    ports:
      - '12104:80'
    x-casaos:
      envs:
        - container: PMA_HOST
          description:
            en_us: 'Container Variable: PMA_HOST'
        - container: PMA_PORT
          description:
            en_us: 'Container Variable: PMA_PORT'
        - container: PMA_USER
          description:
            en_us: 'Container Variable: PMA_USER'
        - container: PMA_PASSWORD
          description:
            en_us: 'Container Variable: PMA_PASSWORD'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: phpmyadmin
  description:
    en_us: phpMyAdmin - A web interface for MySQL and MariaDB.
  tagline:
    en_us: phpMyAdmin
  developer: phpMyAdmin
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/phpmyadmin.png
  thumbnail: ''
  title:
    en_us: phpMyAdmin
  category: BigBearCasaOS
  port_map: '12104'

