name: big-bear-watchyourlan
services:
  big-bear-watchyourlan:
    container_name: big-bear-watchyourlan
    image: aceberg/watchyourlan:2.1.4
    environment:
      - IFACES="eth0"
      - TZ="UTC"
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/data/WatchYourLAN
    network_mode: host
    x-casaos:
      envs:
        - container: IFACES
          description:
            en_us: 'Container Variable: IFACES'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /data/WatchYourLAN
          description:
            en_us: 'Container Path: /data/WatchYourLAN'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-watchyourlan
  description:
    en_us: Lightweight network IP scanner. Can be used to notify about new hosts and monitor host online/offline history
  tagline:
    en_us: WatchYourLAN
  developer: ajnart
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/watchyourlan.png
  thumbnail: ''
  title:
    en_us: WatchYourLAN
  category: BigBearCasaOS
  port_map: '8840'

