name: big-bear-spacedrive
services:
  big-bear-spacedrive:
    container_name: big-bear-spacedrive
    image: ghcr.io/spacedriveapp/spacedrive/server:0.4.2
    restart: unless-stopped
    environment:
      - SD_AUTH=bigbear:casaos
    volumes:
      - /DATA/.docker/AppData/$AppID/data/spacedrive:/var/spacedrive
    ports:
      - '12149:8080'
    x-casaos:
      envs:
        - container: SD_AUTH
          description:
            en_us: 'Container Variable: SD_AUTH'
      volumes:
        - container: /var/spacedrive
          description:
            en_us: 'Container Path: /var/spacedrive'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-spacedrive
  description:
    en_us: Spacedrive is an open source cross-platform file explorer, powered by a virtual distributed filesystem written in Rust.
  tagline:
    en_us: Cross-platform file explorer
  developer: spacedriveapp
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/spacedrive/logo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-spacedrive-to-bigbearcasaos/3163?u=dragonfire1119
  title:
    en_us: Spacedrive
  category: BigBearCasaOS
  port_map: '12149'

