name: big-bear-homarr
services:
  app:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:0.16.1
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/configs:/app/data/configs
      - /DATA/.docker/AppData/$AppID/icons:/app/public/icons
      - /DATA/.docker/AppData/$AppID/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '7575:7575'
    x-casaos:
      volumes:
        - container: /app/data/configs
          description:
            en_us: 'Container Path: /app/data/configs'
        - container: /app/public/icons
          description:
            en_us: 'Container Path: /app/public/icons'
        - container: /data
          description:
            en_us: 'Container Path: /data'
        - container: /var/run/docker.sock
          description:
            en_us: 'Container Path: /var/run/docker.sock'
      ports:
        - container: '7575'
          description:
            en_us: 'Container Port: 7575'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Simplify the management of your server with Homarr - a sleek, modern dashboard that puts all of your apps and services at your fingertips. With Homarr, you can access and control everything in one convenient location. Homarr seamlessly integrates with the apps you've added, providing you with valuable information and giving you complete control. Installation is a breeze, and Homarr supports a wide range of deployment methods.
  tagline:
    en_us: Homarr
  developer: ajnart
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/homarr.png
  thumbnail: ''
  title:
    en_us: Homarr
  category: BigBearCasaOS
  port_map: '7575'

