name: big-bear-fastfetch
services:
  big-bear-fastfetch:
    container_name: big-bear-fastfetch
    image: bigbeartechworld/big-bear-fastfetch:0.0.4
    restart: unless-stopped
    privileged: true
    volumes:
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '12029:7681'
    x-casaos:
      volumes:
        - container: /proc
          description:
            en_us: 'Container Path: /proc'
        - container: /sys
          description:
            en_us: 'Container Path: /sys'
        - container: /dev
          description:
            en_us: 'Container Path: /dev'
        - container: /etc/localtime
          description:
            en_us: 'Container Path: /etc/localtime'
      ports:
        - container: '7681'
          description:
            en_us: 'Container Port: 7681'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-fastfetch
  description:
    en_us: Fastfetch is a neofetch-like tool for fetching system information and displaying it prettily. It is written mainly in C, with performance and customizability in mind. Currently, Linux, Android, FreeBSD, macOS, SunOS and Windows 7+ are supported. https://github.com/fastfetch-cli/fastfetch
  tagline:
    en_us: Fastfetch is a neofetch-like tool.
  developer: bigbeartechworld
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/fastfetch/logo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-fastfetch-to-bigbearcasaos/1579?u=dragonfire1119
  title:
    en_us: Fastfetch
  category: BigBearCasaOS
  port_map: '12029'

