name: big-bear-onedev
services:
  big-bear-onedev:
    container_name: big-bear-onedev
    image: 1dev/server:14.1.8
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/opt/onedev
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - hibernate_dialect=io.onedev.server.persistence.PostgreSQLDialect
      - hibernate_connection_driver_class=org.postgresql.Driver
      - hibernate_connection_url=jdbc:postgresql://big-bear-onedev-db:5432/onedev
      - hibernate_connection_username=bigbear
      - hibernate_connection_password=eea2dad6-2203-45eb-8908-e8ba4d1e7f92
      - initial_user=bigbear
      - initial_password=password
      - initial_email=admin@example.com
      - initial_server_url=http://localhost:6610
    ports:
      - '6610:6610'
      - '6611:6611'
    depends_on:
      - big-bear-onedev-db
    networks:
      - big_bear_ondedev_network
    x-casaos:
      envs:
        - container: hibernate_dialect
          description:
            en_us: 'Container Variable: hibernate_dialect'
        - container: hibernate_connection_driver_class
          description:
            en_us: 'Container Variable: hibernate_connection_driver_class'
        - container: hibernate_connection_url
          description:
            en_us: 'Container Variable: hibernate_connection_url'
        - container: hibernate_connection_username
          description:
            en_us: 'Container Variable: hibernate_connection_username'
        - container: hibernate_connection_password
          description:
            en_us: 'Container Variable: hibernate_connection_password'
        - container: initial_user
          description:
            en_us: 'Container Variable: initial_user'
        - container: initial_password
          description:
            en_us: 'Container Variable: initial_password'
        - container: initial_email
          description:
            en_us: 'Container Variable: initial_email'
        - container: initial_server_url
          description:
            en_us: 'Container Variable: initial_server_url'
      volumes:
        - container: /opt/onedev
          description:
            en_us: 'Container Path: /opt/onedev'
        - container: /var/run/docker.sock
          description:
            en_us: 'Container Path: /var/run/docker.sock'
      ports:
        - container: '6610'
          description:
            en_us: 'Container Port: 6610'
        - container: '6611'
          description:
            en_us: 'Container Port: 6611'
  big-bear-onedev-db:
    container_name: big-bear-onedev-db
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=bigbear
      - POSTGRES_PASSWORD=eea2dad6-2203-45eb-8908-e8ba4d1e7f92
      - POSTGRES_DB=onedev
    volumes:
      - /DATA/.docker/AppData/$AppID/postgres/data:/var/lib/postgresql/data
    networks:
      - big_bear_ondedev_network
    x-casaos:
      envs:
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
networks:
  big_bear_ondedev_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-onedev
  description:
    en_us: Self-hosted Git Server with Kanban and CI/CD
  tagline:
    en_us: Self-hosted Git Server with Kanban and CI/CD
  developer: theonedev
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/onedev.png
  thumbnail: ''
  title:
    en_us: OneDev
  category: BigBearCasaOS
  port_map: '6610'

