name: big-bear-eufy-security-ws
services:
  big-bear-eufy-security-ws:
    container_name: big-bear-eufy-security-ws
    image: bropat/eufy-security-ws:2.1.0
    environment:
      USERNAME: '[EUFY_USERNAME]'
      PASSWORD: '[EUFY_PASSWORD]'
      COUNTRY: US
      LANGUAGE: en
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/data
    network_mode: host
    x-casaos:
      envs:
        - container: USERNAME
          description:
            en_us: 'Container Variable: USERNAME'
        - container: PASSWORD
          description:
            en_us: 'Container Variable: PASSWORD'
        - container: COUNTRY
          description:
            en_us: 'Container Variable: COUNTRY'
        - container: LANGUAGE
          description:
            en_us: 'Container Variable: LANGUAGE'
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-eufy-security-ws
  description:
    en_us: eufy-security-ws is a small server wrapper around the eufy-security-client library to access it via a WebSocket. It allows you to control Eufy security devices by connecting to the Eufy cloud servers and local/remote stations.
  tagline:
    en_us: eufy-security-ws
  developer: bropat
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/_example/logo.jpg
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-eufy-security-ws-to-bigbearcasaos/2228
  title:
    en_us: Eufy Security WS
  category: BigBearCasaOS
  port_map: '3000'

