name: big-bear-unifi-network-application
services:
  app:
    image: linuxserver/unifi-network-application:10.1.85
    container_name: big-bear-unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_HOST=big-bear-unifi-db
      - MONGO_USER=unifi
      - MONGO_PASS=unifi_password
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024
      - MEM_STARTUP=1024
      - MONGO_TLS=
      - MONGO_AUTHSOURCE=
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
    ports:
      - '12162:8443'
      - 3478:3478/udp
      - 10001:10001/udp
      - '12163:8080'
      - 12164:1900/udp
      - '8843:8843'
      - '8880:8880'
      - '6789:6789'
      - 5514:5514/udp
    restart: unless-stopped
    networks:
      - unifi-nework-application-network
    depends_on:
      - unifi-db
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: MONGO_HOST
          description:
            en_us: 'Container Variable: MONGO_HOST'
        - container: MONGO_USER
          description:
            en_us: 'Container Variable: MONGO_USER'
        - container: MONGO_PASS
          description:
            en_us: 'Container Variable: MONGO_PASS'
        - container: MONGO_PORT
          description:
            en_us: 'Container Variable: MONGO_PORT'
        - container: MONGO_DBNAME
          description:
            en_us: 'Container Variable: MONGO_DBNAME'
        - container: MEM_LIMIT
          description:
            en_us: 'Container Variable: MEM_LIMIT'
        - container: MEM_STARTUP
          description:
            en_us: 'Container Variable: MEM_STARTUP'
        - container: MONGO_TLS
          description:
            en_us: 'Container Variable: MONGO_TLS'
        - container: MONGO_AUTHSOURCE
          description:
            en_us: 'Container Variable: MONGO_AUTHSOURCE'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
      ports:
        - container: '8443'
          description:
            en_us: 'Container Port: 8443'
        - container: '3478'
          description:
            en_us: 'Container Port: 3478'
        - container: '10001'
          description:
            en_us: 'Container Port: 10001'
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
        - container: '1900'
          description:
            en_us: 'Container Port: 1900'
        - container: '8843'
          description:
            en_us: 'Container Port: 8843'
        - container: '8880'
          description:
            en_us: 'Container Port: 8880'
        - container: '6789'
          description:
            en_us: 'Container Port: 6789'
        - container: '5514'
          description:
            en_us: 'Container Port: 5514'
  unifi-db:
    image: mongo:6.0.11
    container_name: big-bear-unifi-db
    volumes:
      - /DATA/.docker/AppData/$AppID/db/data:/data/db
      - /DATA/.docker/AppData/$AppID/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - '27017:27017'
    networks:
      - unifi-nework-application-network
    restart: unless-stopped
    x-casaos:
      volumes:
        - container: /data/db
          description:
            en_us: 'Container Path: /data/db'
        - container: /docker-entrypoint-initdb.d/init-mongo.js
          description:
            en_us: 'Container Path: /docker-entrypoint-initdb.d/init-mongo.js'
      ports:
        - container: '27017'
          description:
            en_us: 'Container Port: 27017'
networks:
  unifi-nework-application-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: The Unifi-network-application software is a powerful, enterprise wireless software engine ideal for high-density client deployments requiring low latency and high uptime performance.
  tagline:
    en_us: The Unifi-network-application
  developer: Ubiquiti
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/ubiquiti-unifi.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-unifi-network-application-to-bigbearcasaos/487
  title:
    en_us: Unifi Network Application
  category: BigBearCasaOS
  port_map: '12162'

