name: big-bear-komga
services:
  big-bear-komga:
    container_name: big-bear-komga
    image: ghcr.io/gotson/komga:1.24.1
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
      - /DATA/.docker/AppData/$AppID/data:/data
    ports:
      - '25600:25600'
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /data
          description:
            en_us: 'Container Path: /data'
      ports:
        - container: '25600'
          description:
            en_us: 'Container Port: 25600'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-komga
  description:
    en_us: A media server for your comics, mangas, BDs, magazines and eBooks.
  tagline:
    en_us: A media server for your comics, mangas, BDs, magazines and eBooks.
  developer: gotson
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/komga.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-komga-to-bigbearcasaos/1916#p-3567-documentation-4
  title:
    en_us: Komga
  category: BigBearCasaOS
  port_map: '25600'

