name: big-bear-dockge
services:
  app:
    container_name: big-bear-dockge
    image: louislam/dockge:1.5.0
    environment:
      DOCKGE_STACKS_DIR: /DATA/.docker/AppData/big-bear-dockge/stacks
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /DATA/.docker/AppData/$AppID/data:/app/data
      - /DATA/.docker/AppData/$AppID/stacks:/DATA/AppData/big-bear-dockge/stacks
    ports:
      - '5001:5001'
    x-casaos:
      envs:
        - container: DOCKGE_STACKS_DIR
          description:
            en_us: 'Container Variable: DOCKGE_STACKS_DIR'
      volumes:
        - container: /var/run/docker.sock
          description:
            en_us: 'Container Path: /var/run/docker.sock'
        - container: /app/data
          description:
            en_us: 'Container Path: /app/data'
        - container: /DATA/AppData/big-bear-dockge/stacks
          description:
            en_us: 'Container Path: /DATA/AppData/big-bear-dockge/stacks'
      ports:
        - container: '5001'
          description:
            en_us: 'Container Port: 5001'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: A fancy, easy-to-use and reactive docker `compose.yaml` stack-oriented manager
  tagline:
    en_us: Dockge
  developer: louislam
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/dockge.png
  thumbnail: ''
  title:
    en_us: Dockge
  category: BigBearCasaOS
  port_map: '5001'

