name: big-bear-nocodb
services:
  big-bear-nocodb:
    image: nocodb/nocodb:0.301.3
    container_name: big-bear-nocodb
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://nocodb:nocodb@big-bear-nocodb-db:5432/nocodb
      - NC_AUTH_JWT_SECRET=899499fc-36a0-4131-b077-7bb9f051ac9b
      - NC_REDIS_URL=redis://default:casaos@big-bear-nocodb-redis:6379
    ports:
      - '12088:8080'
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/usr/src/app/data
    networks:
      - big-bear-nocodb-network
    x-casaos:
      envs:
        - container: DATABASE_URL
          description:
            en_us: 'Container Variable: DATABASE_URL'
        - container: NC_AUTH_JWT_SECRET
          description:
            en_us: 'Container Variable: NC_AUTH_JWT_SECRET'
        - container: NC_REDIS_URL
          description:
            en_us: 'Container Variable: NC_REDIS_URL'
      volumes:
        - container: /usr/src/app/data
          description:
            en_us: 'Container Path: /usr/src/app/data'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
  big-bear-nocodb-db:
    container_name: big-bear-nocodb-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: nocodb
      POSTGRES_USER: nocodb
      POSTGRES_PASSWORD: nocodb
    volumes:
      - /DATA/.docker/AppData/$AppID/pgdata:/var/lib/postgresql/data
    networks:
      - big-bear-nocodb-network
    x-casaos:
      envs:
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
  big-bear-nocodb-redis:
    image: redis:8.2.2-alpine@sha256:1c78f5e7512cc8b22b0edc95c20e7abd9e1fd832e5dfd5c3c6b59ce82fb238d0
    container_name: big-bear-nocodb-redis
    restart: unless-stopped
    command:
      - redis-server
      - '--requirepass'
      - casaos
    volumes:
      - /DATA/.docker/AppData/$AppID/redis:/data
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - big-bear-nocodb-network
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
networks:
  big-bear-nocodb-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-nocodb
  description:
    en_us: NocoDB allows building no-code database solutions with ease of spreadsheets. Bring your own database or choose ours! Millions of rows? Not a problem. Your Data. Your rules. You are in control.
  tagline:
    en_us: 🔥 🔥 🔥 Open Source Airtable Alternative
  developer: nocodb
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/nocodb.png
  thumbnail: https://user-images.githubusercontent.com/86527202/277104231-e2fad786-f211-4dcb-9bd3-aaece83a6783.gif
  title:
    en_us: NocoDB
  category: BigBearCasaOS
  port_map: '12088'

