name: big-bear-stirling-pdf
services:
  big-bear-stirling-pdf:
    container_name: big-bear-stirling-pdf
    image: stirlingtools/stirling-pdf:2.5.3
    restart: unless-stopped
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - SECURITY_ENABLE_LOGIN=true
      - SECURITY_INITIALLOGIN_USERNAME=bigbear
      - SECURITY_INITIALLOGIN_PASSWORD=4500733e-a0f8-4605-a712-fd267404956a
      - CSRF_DISABLED=false
      - DEFAULT_LOCALE=en-US
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US
    volumes:
      - /DATA/.docker/AppData/$AppID/tessdata:/usr/share/tessdata
      - /DATA/.docker/AppData/$AppID/configs:/configs
    ports:
      - '12153:8080'
    x-casaos:
      envs:
        - container: DOCKER_ENABLE_SECURITY
          description:
            en_us: 'Container Variable: DOCKER_ENABLE_SECURITY'
        - container: SECURITY_ENABLE_LOGIN
          description:
            en_us: 'Container Variable: SECURITY_ENABLE_LOGIN'
        - container: SECURITY_INITIALLOGIN_USERNAME
          description:
            en_us: 'Container Variable: SECURITY_INITIALLOGIN_USERNAME'
        - container: SECURITY_INITIALLOGIN_PASSWORD
          description:
            en_us: 'Container Variable: SECURITY_INITIALLOGIN_PASSWORD'
        - container: CSRF_DISABLED
          description:
            en_us: 'Container Variable: CSRF_DISABLED'
        - container: DEFAULT_LOCALE
          description:
            en_us: 'Container Variable: DEFAULT_LOCALE'
        - container: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
          description:
            en_us: 'Container Variable: INSTALL_BOOK_AND_ADVANCED_HTML_OPS'
        - container: LANGS
          description:
            en_us: 'Container Variable: LANGS'
      volumes:
        - container: /usr/share/tessdata
          description:
            en_us: 'Container Path: /usr/share/tessdata'
        - container: /configs
          description:
            en_us: 'Container Path: /configs'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-stirling-pdf
  description:
    en_us: Stirling PDF - Local hosted web based PDF editor
  tagline:
    en_us: Stirling PDF - Local hosted web based PDF editor
  developer: stirlingtools
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/stirling-pdf/logo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-stirling-pdf-to-bigbearcasaos/2265#p-4248-documentation-3
  title:
    en_us: Stirling-PDF
  category: BigBearCasaOS
  port_map: '12153'

