name: big-bear-gotify
services:
  app:
    image: gotify/server:2.9.1
    ports:
      - '8091:80'
    environment:
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=custom
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/app/data
    network_mode: bridge
    x-casaos:
      envs:
        - container: GOTIFY_DEFAULTUSER_NAME
          description:
            en_us: 'Container Variable: GOTIFY_DEFAULTUSER_NAME'
        - container: GOTIFY_DEFAULTUSER_PASS
          description:
            en_us: 'Container Variable: GOTIFY_DEFAULTUSER_PASS'
      volumes:
        - container: /app/data
          description:
            en_us: 'Container Path: /app/data'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: a simple server for sending and receiving messages
  tagline:
    en_us: Gotify
  developer: gotify
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/gotify.png
  thumbnail: ''
  title:
    en_us: Gotify
  category: BigBearCasaOS
  port_map: '8091'

