name: big-bear-excalidraw
services:
  app:
    container_name: big-bear-excalidraw
    image: excalidraw/excalidraw:latest
    restart: unless-stopped
    ports:
      - '12027:80'
    x-casaos:
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Virtual whiteboard for sketching hand-drawn like diagrams
  tagline:
    en_us: Virtual whiteboard for sketching hand-drawn like diagrams
  developer: excalidraw
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/excalidraw/logo.png
  thumbnail: ''
  title:
    en_us: Excalidraw
  category: BigBearCasaOS
  port_map: '12027'

