name: big-bear-nexterm
services:
  big-bear-nexterm:
    container_name: big-bear-nexterm
    image: germannewsmaker/nexterm:1.0.9-OPEN-PREVIEW
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/app/data
    ports:
      - '6989:6989'
    x-casaos:
      volumes:
        - container: /app/data
          description:
            en_us: 'Container Path: /app/data'
      ports:
        - container: '6989'
          description:
            en_us: 'Container Port: 6989'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-nexterm
  description:
    en_us: The open source server management software for SSH, VNC & RDP. This is in Preview Release.
  tagline:
    en_us: Nexterm
  developer: germannewsmaker
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/nexterm/logo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-nexterm-to-bigbearcasaos/1835#p-3452-documentation-3
  title:
    en_us: Nexterm
  category: BigBearCasaOS
  port_map: '6989'

