name: big-bear-viseron
services:
  big-bear-viseron:
    container_name: big-bear-viseron
    image: roflcoopter/viseron:3.4.1
    restart: unless-stopped
    shm_size: 1024mb
    volumes:
      - /DATA/.docker/AppData/$AppID/segments:/segments
      - /DATA/.docker/AppData/$AppID/snapshots:/snapshots
      - /DATA/.docker/AppData/$AppID/thumbnails:/thumbnails
      - /DATA/.docker/AppData/$AppID/event/clips:/event_clips
      - /DATA/.docker/AppData/$AppID/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '12176:8888'
    environment:
      - PUID=1000
      - PGID=1000
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
      volumes:
        - container: /segments
          description:
            en_us: 'Container Path: /segments'
        - container: /snapshots
          description:
            en_us: 'Container Path: /snapshots'
        - container: /thumbnails
          description:
            en_us: 'Container Path: /thumbnails'
        - container: /event_clips
          description:
            en_us: 'Container Path: /event_clips'
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /etc/localtime
          description:
            en_us: 'Container Path: /etc/localtime'
      ports:
        - container: '8888'
          description:
            en_us: 'Container Port: 8888'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-viseron
  description:
    en_us: Viseron is a self-hosted, local only NVR and AI Computer Vision software
  tagline:
    en_us: Viseron
  developer: roflcoopter
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/viseron/logo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Before you install read this: https://community.bigbeartechworld.com/t/added-viseron-to-bigbearcasaos/2134?u=dragonfire1119
  title:
    en_us: Viseron
  category: BigBearCasaOS
  port_map: '12176'

