name: big-bear-netalertx
services:
  big-bear-netalertx:
    container_name: big-bear-netalertx
    image: jokobsk/netalertx:26.2.6
    restart: unless-stopped
    privileged: true
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/app/config
      - /DATA/.docker/AppData/$AppID/db:/app/db
    environment:
      - TZ=UTC
      - PORT=8080
      - ALWAYS_FRESH_INSTALL=false
    network_mode: host
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: PORT
          description:
            en_us: 'Container Variable: PORT'
        - container: ALWAYS_FRESH_INSTALL
          description:
            en_us: 'Container Variable: ALWAYS_FRESH_INSTALL'
      volumes:
        - container: /app/config
          description:
            en_us: 'Container Path: /app/config'
        - container: /app/db
          description:
            en_us: 'Container Path: /app/db'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-netalertx
  description:
    en_us: WIFI / LAN intruder detector. Scans for devices connected to your network and alerts you if new and unknown devices are found.
  tagline:
    en_us: NetAlertX
  developer: jokobsk
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/pi-alert.png
  thumbnail: ''
  title:
    en_us: NetAlertX
  category: BigBearCasaOS
  port_map: '8080'

