name: big-bear-jlesage-handbrake
services:
  big-bear-jlesage-handbrake:
    container_name: big-bear-jlesage-handbrake
    image: jlesage/handbrake:v26.02.2
    ports:
      - '12056:5800'
    environment:
      - VNC_PASSWORD=casaos
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
      - /DATA/.docker/AppData/$AppID/storage:/storage
      - /media/Safe-Storage/Library/Watch:/watch
      - /DATA/.docker/AppData/$AppID/output:/output
    x-casaos:
      envs:
        - container: VNC_PASSWORD
          description:
            en_us: 'Container Variable: VNC_PASSWORD'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /storage
          description:
            en_us: 'Container Path: /storage'
        - container: /watch
          description:
            en_us: 'Container Path: /watch'
        - container: /output
          description:
            en_us: 'Container Path: /output'
      ports:
        - container: '5800'
          description:
            en_us: 'Container Port: 5800'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-jlesage-handbrake
  description:
    en_us: The GUI of the application is accessed through a modern web browser (no installation or configuration needed on the client side) or via any VNC client.
  tagline:
    en_us: This project implements a Docker container for Handbrake.
  developer: jlesage
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/handbrake.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-jlesage-handbrake-to-bigbearcasaos/2956?u=dragonfire1119
  title:
    en_us: Jlesage Handbrake
  category: BigBearCasaOS
  port_map: '12056'

