name: big-bear-changedetection
services:
  big-bear-changedetection:
    container_name: big-bear-changedetection
    image: ghcr.io/dgtlmoon/changedetection.io:0.54.3
    restart: unless-stopped
    ports:
      - '12012:5000'
    volumes:
      - /DATA/.docker/AppData/$AppID/datastore:/datastore
    x-casaos:
      volumes:
        - container: /datastore
          description:
            en_us: 'Container Path: /datastore'
      ports:
        - container: '5000'
          description:
            en_us: 'Container Port: 5000'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-changedetection
  description:
    en_us: The best and simplest free open source website change detection, restock monitor and notification service.
  tagline:
    en_us: Website change detection.
  developer: dgtlmoon
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/changedetection.png
  thumbnail: ''
  title:
    en_us: Change Detection
  category: BigBearCasaOS
  port_map: '12012'

