name: big-bear-tududi
services:
  big-bear-tududi:
    container_name: big-bear-tududi
    image: chrisvel/tududi:0.87
    restart: unless-stopped
    environment:
      - TUDUDI_USER_EMAIL=admin@example.com
      - TUDUDI_USER_PASSWORD=2dd25e05-65f4-47d7-a9a6-1a3293c02461
      - TUDUDI_SESSION_SECRET=3337c138d17ac7acefa412e5db0d7ef6540905b198cc28c5bf0d11e48807a71bdfe48d82ed0a0a6eb667c937cbdd1db3e1e6073b3148bff37f73cc6398a39671
      - TUDUDI_INTERNAL_SSL_ENABLED=false
    volumes:
      - /DATA/.docker/AppData/$AppID/tududi/db:/usr/src/app/tududi_db
    ports:
      - '9292:9292'
    x-casaos:
      envs:
        - container: TUDUDI_USER_EMAIL
          description:
            en_us: 'Container Variable: TUDUDI_USER_EMAIL'
        - container: TUDUDI_USER_PASSWORD
          description:
            en_us: 'Container Variable: TUDUDI_USER_PASSWORD'
        - container: TUDUDI_SESSION_SECRET
          description:
            en_us: 'Container Variable: TUDUDI_SESSION_SECRET'
        - container: TUDUDI_INTERNAL_SSL_ENABLED
          description:
            en_us: 'Container Variable: TUDUDI_INTERNAL_SSL_ENABLED'
      volumes:
        - container: /usr/src/app/tududi_db
          description:
            en_us: 'Container Path: /usr/src/app/tududi_db'
      ports:
        - container: '9292'
          description:
            en_us: 'Container Port: 9292'
x-casaos:
  architectures:
    - amd64
  main: big-bear-tududi
  description:
    en_us: tududi is a task and project management web application built with Sinatra. It allows users to efficiently manage their tasks and projects, categorize them into different areas, and track due dates. tududi is designed to be intuitive and easy to use, providing a seamless experience for personal productivity.
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/tududi/screenshots/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/tududi/screenshots/screenshot-2.png
  tagline:
    en_us: tududi is a task and project management web application built with Sinatra
  developer: chrisvel
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/tududi/logo.png
  thumbnail: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/tududi/screenshot-1.png
  title:
    en_us: Tududi
  category: BigBearCasaOS
  port_map: '9292'

