name: big-bear-dbgate
services:
  big-bear-dbgate:
    container_name: big-bear-dbgate
    image: dbgate/dbgate:7.1.2-alpine
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/root/.dbgate
    ports:
      - '12023:3000'
    x-casaos:
      volumes:
        - container: /root/.dbgate
          description:
            en_us: 'Container Path: /root/.dbgate'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-dbgate
  description:
    en_us: Web based UI for managing and exploring SQL database data
  tagline:
    en_us: DBGate
  developer: dbgate
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/dbgate/logo.png
  thumbnail: ''
  title:
    en_us: DBGate
  category: BigBearCasaOS
  port_map: '12023'

