name: big-bear-brave
services:
  brave:
    container_name: big-bear-brave
    image: kasmweb/brave:1.15.0-rolling
    ports:
      - '6901:6901'
    environment:
      - VNC_PW=casaos
      - LAUNCH_URL=https://community.bigbeartechworld.com/
    shm_size: 512m
    volumes:
      - /media/Safe-Storage/Library/Downloads:/home/kasm-user/Downloads
    x-casaos:
      envs:
        - container: VNC_PW
          description:
            en_us: 'Container Variable: VNC_PW'
        - container: LAUNCH_URL
          description:
            en_us: 'Container Variable: LAUNCH_URL'
      volumes:
        - container: /home/kasm-user/Downloads
          description:
            en_us: 'Container Path: /home/kasm-user/Downloads'
      ports:
        - container: '6901'
          description:
            en_us: 'Container Port: 6901'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: brave
  description:
    en_us: This Image contains a browser-accessible version of Brave.
  tagline:
    en_us: Brave
  developer: kasmweb
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/brave.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Username: kasm_user
        Password: casaos
  title:
    en_us: Brave
  category: BigBearCasaOS
  port_map: '6901'

