name: big-bear-playitgg
services:
  app:
    container_name: playitgg
    image: dysta/playitgg:1.2.0
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/secrets:/secrets
    x-casaos:
      volumes:
        - container: /secrets
          description:
            en_us: 'Container Path: /secrets'
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: playit.gg is a global proxy that allows anyone to host a server without port forwarding. We use tunneling. Only the server needs to run the program, not every player!
  tagline:
    en_us: playit.gg is a global proxy that allows anyone to host a server without port forwarding. We use tunneling. Only the server needs to run the program, not every player!
  developer: Dysta
  author: BigBearCommunity
  icon: https://media.forgecdn.net/avatars/848/399/638248438568793075.png
  thumbnail: ''
  title:
    en_us: playit.gg
  category: BigBearCasaOS
  port_map: ''

