name: big-bear-nightscout
services:
  big-bear-nightscout:
    container_name: big-bear-nightscout
    image: nightscout/cgm-remote-monitor:15.0.6
    restart: unless-stopped
    ports:
      - '1337:1337'
    environment:
      NODE_ENV: production
      TZ: Etc/UTC
      INSECURE_USE_HTTP: 'true'
      MONGO_CONNECTION: mongodb://big-bear-nightscout-mongo:27017/nightscout
      API_SECRET: 48f875fa-0e03-416f-b9d6-19c9afc4e194
      ENABLE: careportal rawbg iob
      AUTH_DEFAULT_ROLES: denied
    depends_on:
      - big-bear-nightscout-mongo
    networks:
      - big-bear-nightscout-network
    x-casaos:
      envs:
        - container: NODE_ENV
          description:
            en_us: 'Container Variable: NODE_ENV'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: INSECURE_USE_HTTP
          description:
            en_us: 'Container Variable: INSECURE_USE_HTTP'
        - container: MONGO_CONNECTION
          description:
            en_us: 'Container Variable: MONGO_CONNECTION'
        - container: API_SECRET
          description:
            en_us: 'Container Variable: API_SECRET'
        - container: ENABLE
          description:
            en_us: 'Container Variable: ENABLE'
        - container: AUTH_DEFAULT_ROLES
          description:
            en_us: 'Container Variable: AUTH_DEFAULT_ROLES'
      ports:
        - container: '1337'
          description:
            en_us: 'Container Port: 1337'
  big-bear-nightscout-mongo:
    container_name: big-bear-nightscout-mongo
    image: mongo:4.4
    networks:
      - big-bear-nightscout-network
    volumes:
      - /DATA/.docker/AppData/$AppID/mongo-data:/data/db
    x-casaos:
      volumes:
        - container: /data/db
          description:
            en_us: 'Container Path: /data/db'
networks:
  big-bear-nightscout-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-nightscout
  description:
    en_us: This acts as a web-based CGM (Continuous Glucose Monitor) to allow multiple caregivers to remotely view a patient's glucose data in real time. The server reads a MongoDB which is intended to be data from a physical CGM, where it sends new SGV (sensor glucose values) as the data becomes available. The data is then displayed graphically and blood glucose values are predicted 0.5 hours ahead using an autoregressive second order model. Alarms are generated for high and low values, which can be cleared by any watcher of the data.
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/nightscout/screenshots/screenshot.png
  tagline:
    en_us: Nightscout
  developer: nightscout
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/nightscout.png
  thumbnail: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/nightscout/screenshot.png
  tips:
    before_install:
      en_us: |
        https://community.bigbeartechworld.com/t/added-nightscout-to-bigbearcasaos/1403#documentation-3
  title:
    en_us: nightscout
  category: BigBearCasaOS
  port_map: '1337'

