name: big-bear-libredesk
services:
  big-bear-libredesk:
    container_name: big-bear-libredesk
    image: libredesk/libredesk:v0.7.4-alpha
    restart: unless-stopped
    environment:
      - LIBREDESK_SYSTEM_USER_PASSWORD="c6b51a4e-ab9d-4f4f-933e-e96ed3570c1A"
    volumes:
      - /DATA/.docker/AppData/$AppID/uploads:/libredesk/uploads
      - /DATA/.docker/AppData/$AppID/config:/libredesk/config
    ports:
      - '12066:9000'
    command:
      - sh
      - '-c'
      - ./libredesk --install --idempotent-install --yes --config /libredesk/config/config.toml && ./libredesk --upgrade --yes --config /libredesk/config/config.toml && ./libredesk --config /libredesk/config/config.toml
    depends_on:
      - big-bear-libredesk-db
      - big-bear-libredesk-redis
    networks:
      - big-bear-libredesk-network
    x-casaos:
      envs:
        - container: LIBREDESK_SYSTEM_USER_PASSWORD
          description:
            en_us: 'Container Variable: LIBREDESK_SYSTEM_USER_PASSWORD'
      volumes:
        - container: /libredesk/uploads
          description:
            en_us: 'Container Path: /libredesk/uploads'
        - container: /libredesk/config
          description:
            en_us: 'Container Path: /libredesk/config'
      ports:
        - container: '9000'
          description:
            en_us: 'Container Port: 9000'
  big-bear-libredesk-db:
    image: postgres:17-alpine
    container_name: big-bear-libredesk-db
    restart: unless-stopped
    networks:
      - big-bear-libredesk-network
    ports:
      - '12067:5432'
    environment:
      POSTGRES_USER: libredesk
      POSTGRES_PASSWORD: libredesk
      POSTGRES_DB: big_bear_libredesk
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U libredesk
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - /DATA/.docker/AppData/$AppID/data/postgres:/var/lib/postgresql/data
    x-casaos:
      envs:
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
      ports:
        - container: '5432'
          description:
            en_us: 'Container Port: 5432'
  big-bear-libredesk-redis:
    image: redis:7.4.6-alpine@sha256:7a7c6b5c49a6896d0a58ee0c6dc0dcabe14f30f0a2f7d2d1362d276fa2d43166
    container_name: big-bear-libredesk-redis
    restart: unless-stopped
    ports:
      - '12068:6379'
    networks:
      - big-bear-libredesk-network
    volumes:
      - /DATA/.docker/AppData/$AppID/data/redis:/data
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
      ports:
        - container: '6379'
          description:
            en_us: 'Container Port: 6379'
networks:
  big-bear-libredesk-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-libredesk
  description:
    en_us: Open source, self-hosted customer support desk. Single binary app.
  tagline:
    en_us: Open source, self-hosted customer support desk. Single binary app.
  developer: libredesk
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/_example/logo.jpg
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-libredesk-to-bigbearcasaos/2993#p-5277-documentation-4
  title:
    en_us: Libredesk
  category: BigBearCasaOS
  port_map: '12066'

