name: big-bear-openvpn-as
services:
  big-bear-openvpn-as:
    container_name: big-bear-openvpn-as
    image: openvpn/openvpn-as:2.13.1-d8cdeb9c-Ubuntu22
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Rome
    hostname: OpenVPN
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/openvpn.png
    ports:
      - 943:943/tcp
      - '12096:443'
      - 1194:1194/udp
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/openvpn
    network_mode: bridge
    x-casaos:
      envs:
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /openvpn
          description:
            en_us: 'Container Path: /openvpn'
      ports:
        - container: '943'
          description:
            en_us: 'Container Port: 943'
        - container: '443'
          description:
            en_us: 'Container Port: 443'
        - container: '1194'
          description:
            en_us: 'Container Port: 1194'
x-casaos:
  architectures:
    - amd64
  main: big-bear-openvpn-as
  description:
    en_us: OpenVPN is an open-source commercial software that implements virtual private network (VPN) techniques to create secure point-to-point or site-to-site connections in routed or bridged configurations and remote access facilities.
  tagline:
    en_us: OpenVPN is an open-source commercial software that implements virtual private network (VPN).
  developer: openvpn
  author: BigBearCommunity
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/openvpn.png
  thumbnail: ''
  title:
    en_us: OpenVPN
  category: BigBearCasaOS
  port_map: '943'

