name: big-bear-focalboard
services:
  app:
    container_name: big-bear-focalboard
    image: mattermost/focalboard:7.11.4
    restart: unless-stopped
    ports:
      - '12036:8000'
    network_mode: bridge
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/opt/focalboard/data
    x-casaos:
      volumes:
        - container: /opt/focalboard/data
          description:
            en_us: 'Container Path: /opt/focalboard/data'
      ports:
        - container: '8000'
          description:
            en_us: 'Container Port: 8000'
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Focalboard is an open source, multilingual, self-hosted project management tool that's an alternative to Trello, Notion, and Asana.
  tagline:
    en_us: Focalboard is an open source, self-hosted alternative to Trello, Notion, and Asana.
  developer: mattermost
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/focalboard.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Before you can use the application, you will need to create a new account when going to the Focalboard UI.
  title:
    en_us: Focalboard
  category: BigBearCasaOS
  port_map: '12036'

