name: big-bear-n8n
services:
  app:
    container_name: n8n
    image: n8nio/n8n:2.11.0
    restart: unless-stopped
    ports:
      - '5678:5678'
    links:
      - db-n8n
    volumes:
      - /DATA/.docker/AppData/$AppID/.n8n:/home/node/.n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=db-n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=bigbearcasaos
      - DB_POSTGRESDB_PASSWORD=bigbearcasaos
    depends_on:
      db-n8n:
        condition: service_healthy
    x-casaos:
      envs:
        - container: DB_TYPE
          description:
            en_us: 'Container Variable: DB_TYPE'
        - container: DB_POSTGRESDB_DATABASE
          description:
            en_us: 'Container Variable: DB_POSTGRESDB_DATABASE'
        - container: DB_POSTGRESDB_HOST
          description:
            en_us: 'Container Variable: DB_POSTGRESDB_HOST'
        - container: DB_POSTGRESDB_PORT
          description:
            en_us: 'Container Variable: DB_POSTGRESDB_PORT'
        - container: DB_POSTGRESDB_USER
          description:
            en_us: 'Container Variable: DB_POSTGRESDB_USER'
        - container: DB_POSTGRESDB_PASSWORD
          description:
            en_us: 'Container Variable: DB_POSTGRESDB_PASSWORD'
      volumes:
        - container: /home/node/.n8n
          description:
            en_us: 'Container Path: /home/node/.n8n'
      ports:
        - container: '5678'
          description:
            en_us: 'Container Port: 5678'
  db-n8n:
    container_name: db-n8n
    image: postgres:14.2
    restart: on-failure
    volumes:
      - /DATA/.docker/AppData/$AppID/pgdata:/var/lib/postgresql/data
      - /DATA/.docker/AppData/$AppID/db/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    environment:
      - POSTGRES_PASSWORD=bigbearcasaos
      - POSTGRES_USER=bigbearcasaos
      - POSTGRES_DB=n8n
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -h localhost -U bigbearcasaos -d n8n
      interval: 5s
      timeout: 5s
      retries: 10
    x-casaos:
      envs:
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
        - container: /docker-entrypoint-initdb.d/init-data.sh
          description:
            en_us: 'Container Path: /docker-entrypoint-initdb.d/init-data.sh'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Free and open fair-code licensed node based Workflow Automation Tool.
  tagline:
    en_us: Workflow automation tool
  developer: n8n
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/n8n.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Run this script:

        ```
        bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/generate-n8n-init-data/run.sh)"
        ```
  title:
    en_us: n8n
  category: BigBearCasaOS
  port_map: '5678'

