name: big-bear-morphos
services:
  big-bear-morphos:
    container_name: big-bear-morphos
    image: ghcr.io/danvergara/morphos-server:0.6.0
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/tmp:/tmp
    ports:
      - '12082:8080'
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 30s
    x-casaos:
      volumes:
        - container: /tmp
          description:
            en_us: 'Container Path: /tmp'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-morphos
  description:
    en_us: Today we are forced to rely on third party services to convert files to other formats. This is a serious threat to our privacy, if we use such services to convert files with highly sensitive personal data. It can be used against us, sooner or later. Morphos server aims to solve the problem mentioned above, by providing a self-hosted server to convert files privately. The project provides an user-friendly web UI. For now, Morphos only supports images. Documents will be added soon.
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/morphos/screenshots/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/morphos/screenshots/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/morphos/screenshots/screenshot-3.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/morphos/screenshots/screenshot-4.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/morphos/screenshots/screenshot-5.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/morphos/screenshots/screenshot-6.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/morphos/screenshots/screenshot-7.png
  tagline:
    en_us: Self-hosted file converter server
  developer: danvergara
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/morphos/logo.png
  thumbnail: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/morphos/thumbnail.png
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-morphos-to-bigbearcasaos/3160?u=dragonfire1119
  title:
    en_us: Morphos
  category: BigBearCasaOS
  port_map: '12082'

