name: big-bear-trilium
services:
  app:
    container_name: big-bear-trilium
    image: triliumnext/trilium:v0.102.0
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/home/node/trilium-data
    ports:
      - '12157:8080'
    x-casaos:
      envs:
        - container: TRILIUM_DATA_DIR
          description:
            en_us: 'Container Variable: TRILIUM_DATA_DIR'
      volumes:
        - container: /home/node/trilium-data
          description:
            en_us: 'Container Path: /home/node/trilium-data'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Build your personal knowledge base with Trilium Notes
  tagline:
    en_us: Build your personal knowledge base with Trilium Notes
  developer: TriliumNext
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/trilium-notes.png
  thumbnail: ''
  title:
    en_us: Trilium
  category: BigBearCasaOS
  port_map: '12157'

