name: big-bear-warracker
services:
  big-bear-warracker:
    container_name: big-bear-warracker
    image: ghcr.io/sassanix/warracker/main:9.9.3
    restart: unless-stopped
    privileged: true
    environment:
      - DB_HOST=big-bear-warrackerdb
      - DB_NAME=big_bear_warracker
      - DB_USER=big_bear_warracker_user
      - DB_PASSWORD=4892f1bc-f1ea-464f-b528-1d52b2c9bb05
      - SMTP_HOST=smtp.email.com
      - SMTP_PORT=465
      - SMTP_USERNAME=youremail@email.com
      - SMTP_PASSWORD=password
    volumes:
      - /DATA/.docker/AppData/$AppID/uploads:/data/uploads
    ports:
      - '8005:80'
    networks:
      - big_bear_warracker_network
    depends_on:
      big-bear-warrackerdb:
        condition: service_healthy
    x-casaos:
      envs:
        - container: DB_HOST
          description:
            en_us: 'Container Variable: DB_HOST'
        - container: DB_NAME
          description:
            en_us: 'Container Variable: DB_NAME'
        - container: DB_USER
          description:
            en_us: 'Container Variable: DB_USER'
        - container: DB_PASSWORD
          description:
            en_us: 'Container Variable: DB_PASSWORD'
        - container: SMTP_HOST
          description:
            en_us: 'Container Variable: SMTP_HOST'
        - container: SMTP_PORT
          description:
            en_us: 'Container Variable: SMTP_PORT'
        - container: SMTP_USERNAME
          description:
            en_us: 'Container Variable: SMTP_USERNAME'
        - container: SMTP_PASSWORD
          description:
            en_us: 'Container Variable: SMTP_PASSWORD'
      volumes:
        - container: /data/uploads
          description:
            en_us: 'Container Path: /data/uploads'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
  big-bear-warrackerdb:
    container_name: big-bear-warrackerdb
    image: postgres:15-alpine
    volumes:
      - /DATA/.docker/AppData/$AppID/warrackerdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=big_bear_warracker
      - POSTGRES_USER=big_bear_warracker_user
      - POSTGRES_PASSWORD=4892f1bc-f1ea-464f-b528-1d52b2c9bb05
    restart: unless-stopped
    networks:
      - big_bear_warracker_network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
    x-casaos:
      envs:
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
networks:
  big_bear_warracker_network:
    name: big_bear_warracker_network
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-warracker
  description:
    en_us: A self-hosted warranty tracker
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/warracker/screenshots/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/warracker/screenshots/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/warracker/screenshots/screenshot-3.png
  tagline:
    en_us: A self-hosted warranty tracker
  developer: sassanix
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/warracker.png
  thumbnail: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/warracker/thumbnail.png
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-warracker-to-bigbearcasaos/3346?u=dragonfire1119
  title:
    en_us: Warracker
  category: BigBearCasaOS
  port_map: '8005'

