name: big-bear-authentik
services:
  big-bear-authentik:
    container_name: big-bear-authentik
    image: ghcr.io/goauthentik/server:2025.12.4
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: big-bear-authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: big-bear-authentik-db
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentik-password
      AUTHENTIK_SECRET_KEY: changeme
    volumes:
      - /media/Safe-Storage/Library:/media
      - /DATA/.docker/AppData/$AppID/data/authentik-custom-templates:/templates
    ports:
      - '9443:9443'
    depends_on:
      - big-bear-authentik-db
      - big-bear-authentik-redis
    networks:
      - big_bear_authentik_network
    x-casaos:
      envs:
        - container: AUTHENTIK_REDIS__HOST
          description:
            en_us: 'Container Variable: AUTHENTIK_REDIS__HOST'
        - container: AUTHENTIK_POSTGRESQL__HOST
          description:
            en_us: 'Container Variable: AUTHENTIK_POSTGRESQL__HOST'
        - container: AUTHENTIK_POSTGRESQL__USER
          description:
            en_us: 'Container Variable: AUTHENTIK_POSTGRESQL__USER'
        - container: AUTHENTIK_POSTGRESQL__NAME
          description:
            en_us: 'Container Variable: AUTHENTIK_POSTGRESQL__NAME'
        - container: AUTHENTIK_POSTGRESQL__PASSWORD
          description:
            en_us: 'Container Variable: AUTHENTIK_POSTGRESQL__PASSWORD'
        - container: AUTHENTIK_SECRET_KEY
          description:
            en_us: 'Container Variable: AUTHENTIK_SECRET_KEY'
      volumes:
        - container: /media
          description:
            en_us: 'Container Path: /media'
        - container: /templates
          description:
            en_us: 'Container Path: /templates'
      ports:
        - container: '9443'
          description:
            en_us: 'Container Port: 9443'
  big-bear-authentik-worker:
    image: ghcr.io/goauthentik/server:2025.12.4
    restart: unless-stopped
    command: worker
    container_name: big-bear-authentik-worker
    environment:
      AUTHENTIK_REDIS__HOST: big-bear-authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: big-bear-authentik-db
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentik-password
      AUTHENTIK_SECRET_KEY: changeme
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /media/Safe-Storage/Library:/media
      - /DATA/.docker/AppData/$AppID/data/authentik-certs:/certs
      - /DATA/.docker/AppData/$AppID/data/authentik-custom-templates:/templates
    depends_on:
      - big-bear-authentik-db
      - big-bear-authentik-redis
    networks:
      - big_bear_authentik_network
    x-casaos:
      envs:
        - container: AUTHENTIK_REDIS__HOST
          description:
            en_us: 'Container Variable: AUTHENTIK_REDIS__HOST'
        - container: AUTHENTIK_POSTGRESQL__HOST
          description:
            en_us: 'Container Variable: AUTHENTIK_POSTGRESQL__HOST'
        - container: AUTHENTIK_POSTGRESQL__USER
          description:
            en_us: 'Container Variable: AUTHENTIK_POSTGRESQL__USER'
        - container: AUTHENTIK_POSTGRESQL__NAME
          description:
            en_us: 'Container Variable: AUTHENTIK_POSTGRESQL__NAME'
        - container: AUTHENTIK_POSTGRESQL__PASSWORD
          description:
            en_us: 'Container Variable: AUTHENTIK_POSTGRESQL__PASSWORD'
        - container: AUTHENTIK_SECRET_KEY
          description:
            en_us: 'Container Variable: AUTHENTIK_SECRET_KEY'
      volumes:
        - container: /var/run/docker.sock
          description:
            en_us: 'Container Path: /var/run/docker.sock'
        - container: /media
          description:
            en_us: 'Container Path: /media'
        - container: /certs
          description:
            en_us: 'Container Path: /certs'
        - container: /templates
          description:
            en_us: 'Container Path: /templates'
  big-bear-authentik-db:
    container_name: big-bear-authentik-db
    image: postgres:14-alpine
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - /DATA/.docker/AppData/$AppID/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: authentik-password
      POSTGRES_USER: authentik
      POSTGRES_DB: authentik
    networks:
      - big_bear_authentik_network
    x-casaos:
      envs:
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
  big-bear-authentik-redis:
    image: redis:8.2.2-alpine@sha256:1c78f5e7512cc8b22b0edc95c20e7abd9e1fd832e5dfd5c3c6b59ce82fb238d0
    command:
      - '--save'
      - '60'
      - '1'
      - '--loglevel'
      - warning
    container_name: big-bear-authentik-redis
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - /DATA/.docker/AppData/$AppID/data/redis:/data
    networks:
      - big_bear_authentik_network
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
networks:
  big_bear_authentik_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-authentik
  description:
    en_us: Authentik is a self-hosted identity and access management platform that provides a secure and scalable solution for managing user accounts, authentication, and authorization. It offers a range of features, including user management, role-based access control, and multi-factor authentication. Authentik is designed to be easy to use and integrate with your existing systems, making it a great choice for organizations looking to improve their security and compliance.
  tagline:
    en_us: Authentik
  developer: authentik
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/authentik.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Before you install read this: https://community.bigbeartechworld.com/t/added-authentik-to-bigbearcasaos/1196#instructions-3
  title:
    en_us: Authentik
  category: BigBearCasaOS
  port_map: '9443'

