name: big-bear-node-red
services:
  app:
    container_name: node-red
    image: nodered/node-red:4.1.6
    restart: unless-stopped
    ports:
      - '1880:1880'
    network_mode: bridge
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/data
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
      ports:
        - container: '1880'
          description:
            en_us: 'Container Port: 1880'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Node-RED is a programming tool for wiring together hardware devices, APIs and online services in new and interesting ways.  It provides a browser-based editor that makes it easy to wire together flows using the wide range of nodes in the palette that can be deployed to its runtime in a single-click.
  tagline:
    en_us: Low-code programming for event-driven applications
  developer: nodered
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/node-red.png
  thumbnail: ''
  title:
    en_us: Node-RED
  category: BigBearCasaOS
  port_map: '1880'

