name: big-bear-ihatemoney
services:
  big-bear-ihatemoney:
    container_name: big-bear-ihatemoney
    image: ihatemoney/ihatemoney:7.0.0
    restart: unless-stopped
    environment:
      SECRET_KEY: 1d58bc34-e7ff-4f6d-a1e4-f319262ed9b8
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://bigbear:password@big-bear-ihatemoney-db/ihatemoney
      ACTIVATE_ADMIN_DASHBOARD: 'True'
      ADMIN_PASSWORD: ''
      SESSION_COOKIE_SECURE: 'False'
    ports:
      - '8001:8000'
    networks:
      - big_bear_ihatemoney_network
    x-casaos:
      envs:
        - container: SECRET_KEY
          description:
            en_us: 'Container Variable: SECRET_KEY'
        - container: SQLALCHEMY_DATABASE_URI
          description:
            en_us: 'Container Variable: SQLALCHEMY_DATABASE_URI'
        - container: ACTIVATE_ADMIN_DASHBOARD
          description:
            en_us: 'Container Variable: ACTIVATE_ADMIN_DASHBOARD'
        - container: ADMIN_PASSWORD
          description:
            en_us: 'Container Variable: ADMIN_PASSWORD'
        - container: SESSION_COOKIE_SECURE
          description:
            en_us: 'Container Variable: SESSION_COOKIE_SECURE'
      ports:
        - container: '8000'
          description:
            en_us: 'Container Port: 8000'
  big-bear-ihatemoney-db:
    image: mariadb:10
    container_name: big-bear-ihatemoney-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ihatemoney
      MYSQL_USER: bigbear
      MYSQL_PASSWORD: password
    ports:
      - '12049:3306'
    volumes:
      - /DATA/.docker/AppData/$AppID/mysql:/var/lib/mysql
    networks:
      - big_bear_ihatemoney_network
    x-casaos:
      envs:
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_ROOT_PASSWORD'
        - container: MYSQL_DATABASE
          description:
            en_us: 'Container Variable: MYSQL_DATABASE'
        - container: MYSQL_USER
          description:
            en_us: 'Container Variable: MYSQL_USER'
        - container: MYSQL_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_PASSWORD'
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: 'Container Path: /var/lib/mysql'
      ports:
        - container: '3306'
          description:
            en_us: 'Container Port: 3306'
networks:
  big_bear_ihatemoney_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-ihatemoney
  description:
    en_us: I hate money is a web application made to ease shared budget management. It keeps track of who bought what, when, and for whom; and helps to settle the bills.
  tagline:
    en_us: A simple shared budget manager web application
  developer: spiral-project
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/ihatemoney.png
  thumbnail: ''
  title:
    en_us: I Hate Money
  category: BigBearCasaOS
  port_map: '8001'

