name: big-bear-genmon
services:
  big-bear-genmon:
    container_name: big-bear-genmon
    image: bigbeartechworld/big-bear-genmon:1.19.08
    environment:
      - TZ=America/Chicago
    ports:
      - '20022:22'
      - '38443:443'
      - '12037:8000'
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/git/genmon:/git/genmon
      - /DATA/.docker/AppData/$AppID/etc/genmon:/etc/genmon
      - /DATA/.docker/AppData/$AppID/var/log:/var/log
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /git/genmon
          description:
            en_us: 'Container Path: /git/genmon'
        - container: /etc/genmon
          description:
            en_us: 'Container Path: /etc/genmon'
        - container: /var/log
          description:
            en_us: 'Container Path: /var/log'
      ports:
        - container: '22'
          description:
            en_us: 'Container Port: 22'
        - container: '443'
          description:
            en_us: 'Container Port: 443'
        - container: '8000'
          description:
            en_us: 'Container Port: 8000'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-genmon
  description:
    en_us: Generac (and other models) Generator Monitoring using a Raspberry Pi and WiFi
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/genmon/screenshots/screenshot1.png
  tagline:
    en_us: Genmon
  developer: bigbeartechworld
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/genmon/logo.jpeg
  thumbnail: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/genmon/screenshot1.png
  title:
    en_us: Genmon
  category: BigBearCasaOS
  port_map: '20022'

