name: big-bear-chromium
services:
  chromium:
    container_name: big-bear-chromium
    image: linuxserver/chromium:version-6ae43f81
    ports:
      - '12014:3000'
      - '12015:3001'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CHROME_CLI=https://community.bigbeartechworld.com/
    shm_size: 1gb
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: CHROME_CLI
          description:
            en_us: 'Container Variable: CHROME_CLI'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
        - container: '3001'
          description:
            en_us: 'Container Port: 3001'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: chromium
  description:
    en_us: This Image contains a browser-accessible version of chromium.
  tagline:
    en_us: chromium
  developer: linuxserver
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/chromium.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Access the browser at http://your-server:3000 or https://your-server:3001
  title:
    en_us: chromium
  category: BigBearCasaOS
  port_map: '12014'

