name: big-bear-beaverhabits
services:
  big-bear-beaverhabits:
    container_name: big-bear-beaverhabits
    image: daya0576/beaverhabits:0.9.0
    restart: unless-stopped
    user: '1000:1000'
    environment:
      - HABITS_STORAGE=USER_DISK
      - TRUSTED_LOCAL_EMAIL=your@email.com
      - INDEX_HABIT_DATE_COLUMNS=5
      - ENABLE_IOS_STANDALONE=true
    volumes:
      - /DATA/.docker/AppData/$AppID/.user:/app/.user/
    ports:
      - '12006:8080'
    x-casaos:
      envs:
        - container: HABITS_STORAGE
          description:
            en_us: 'Container Variable: HABITS_STORAGE'
        - container: TRUSTED_LOCAL_EMAIL
          description:
            en_us: 'Container Variable: TRUSTED_LOCAL_EMAIL'
        - container: INDEX_HABIT_DATE_COLUMNS
          description:
            en_us: 'Container Variable: INDEX_HABIT_DATE_COLUMNS'
        - container: ENABLE_IOS_STANDALONE
          description:
            en_us: 'Container Variable: ENABLE_IOS_STANDALONE'
      volumes:
        - container: /app/.user/
          description:
            en_us: 'Container Path: /app/.user/'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-beaverhabits
  description:
    en_us: A self-hosted habit tracking app without Goals
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/beaverhabits/screenshots/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/beaverhabits/screenshots/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/beaverhabits/screenshots/screenshot-3.png
  tagline:
    en_us: A self-hosted habit tracking app without Goals
  developer: daya0576
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/beaver-habit-tracker.png
  thumbnail: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/beaverhabits/thumbnail.png
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-beaverhabits-to-bigbearcasaos/3345?u=dragonfire1119
  title:
    en_us: Beaver Habit Tracker
  category: BigBearCasaOS
  port_map: '12006'

