name: big-bear-jfa-go
services:
  big-bear-jfa-go:
    container_name: big-bear-jfa-go
    image: hrfee/jfa-go:latest
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/.config/jfa-go:/data
      - /DATA/.docker/AppData/$AppID/jellyfin:/jf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8056:8056'
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
        - container: /jf
          description:
            en_us: 'Container Path: /jf'
        - container: /etc/localtime
          description:
            en_us: 'Container Path: /etc/localtime'
      ports:
        - container: '8056'
          description:
            en_us: 'Container Port: 8056'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-jfa-go
  description:
    en_us: jfa-go is a user management app for Jellyfin (and Emby as 2nd class) that provides invite-based account creation as well as other features that make one's instance much easier to manage.
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/jfa-go/screenshots/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/jfa-go/screenshots/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/jfa-go/screenshots/screenshot-3.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/jfa-go/screenshots/screenshot-4.png
  tagline:
    en_us: Manage users in Jellyfin
  developer: hrfee
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin.png
  thumbnail: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/jfa-go/thumbnail.png
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-jfa-go-to-bigbearcasaos/3364?u=dragonfire1119
  title:
    en_us: jfa-go
  category: BigBearCasaOS
  port_map: '8056'

