name: big-bear-code-server
services:
  app:
    image: linuxserver/code-server:4.109.5
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - PASSWORD=my_password
      - SUDO_PASSWORD=sudo_my_password
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
      - /DATA/.docker/AppData/$AppID/projects:/projects
    ports:
      - '12016:8443'
    restart: always
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: PASSWORD
          description:
            en_us: 'Container Variable: PASSWORD'
        - container: SUDO_PASSWORD
          description:
            en_us: 'Container Variable: SUDO_PASSWORD'
        - container: DEFAULT_WORKSPACE
          description:
            en_us: 'Container Variable: DEFAULT_WORKSPACE'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /projects
          description:
            en_us: 'Container Path: /projects'
      ports:
        - container: '8443'
          description:
            en_us: 'Container Port: 8443'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Run VS Code on any machine anywhere and access it in the browser.
  tagline:
    en_us: Code Server
  developer: linuxserver
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/coder.png
  thumbnail: ''
  title:
    en_us: Code Server
  category: BigBearCasaOS
  port_map: '12016'

