name: big-bear-seafile
services:
  big-bear-seafile:
    container_name: big-bear-seafile
    image: seafileltd/seafile-mc:11.0.13
    restart: unless-stopped
    depends_on:
      big-bear-seafile-db:
        condition: service_healthy
      big-bear-seafile-memcached:
        condition: service_started
    volumes:
      - /DATA/.docker/AppData/$AppID/shared:/shared
    ports:
      - '12145:80'
    environment:
      - DB_HOST=big-bear-seafile-db
      - DB_ROOT_PASSWD=seafilepassword
      - TIME_ZONE=Etc/UTC
      - SEAFILE_ADMIN_EMAIL=admin@example.com
      - SEAFILE_ADMIN_PASSWORD=asecret
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=docs.seafile.com
    networks:
      - big_bear_seafile_network
    x-casaos:
      envs:
        - container: DB_HOST
          description:
            en_us: 'Container Variable: DB_HOST'
        - container: DB_ROOT_PASSWD
          description:
            en_us: 'Container Variable: DB_ROOT_PASSWD'
        - container: TIME_ZONE
          description:
            en_us: 'Container Variable: TIME_ZONE'
        - container: SEAFILE_ADMIN_EMAIL
          description:
            en_us: 'Container Variable: SEAFILE_ADMIN_EMAIL'
        - container: SEAFILE_ADMIN_PASSWORD
          description:
            en_us: 'Container Variable: SEAFILE_ADMIN_PASSWORD'
        - container: SEAFILE_SERVER_LETSENCRYPT
          description:
            en_us: 'Container Variable: SEAFILE_SERVER_LETSENCRYPT'
        - container: SEAFILE_SERVER_HOSTNAME
          description:
            en_us: 'Container Variable: SEAFILE_SERVER_HOSTNAME'
      volumes:
        - container: /shared
          description:
            en_us: 'Container Path: /shared'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
  big-bear-seafile-db:
    image: mariadb:10.11
    container_name: big-bear-seafile-db
    environment:
      - MYSQL_ROOT_PASSWORD=seafilepassword
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - /DATA/.docker/AppData/$AppID/mysql:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - big_bear_seafile_network
    x-casaos:
      envs:
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_ROOT_PASSWORD'
        - container: MYSQL_LOG_CONSOLE
          description:
            en_us: 'Container Variable: MYSQL_LOG_CONSOLE'
        - container: MARIADB_AUTO_UPGRADE
          description:
            en_us: 'Container Variable: MARIADB_AUTO_UPGRADE'
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: 'Container Path: /var/lib/mysql'
  big-bear-seafile-memcached:
    container_name: big-bear-seafile-memcached
    image: memcached:1.6.39
    entrypoint: memcached -m 256
    networks:
      - big_bear_seafile_network
networks:
  big_bear_seafile_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-seafile
  description:
    en_us: Seafile is an open source file sync and share platform, focusing on reliability and performance. Seafile's built-in collaborative document SeaDoc, make it easy for collaborative writing and publishing documents.
  tagline:
    en_us: Seafile is an open source file sync and share platform, focusing on reliability and performance.
  developer: seafile
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/seafile.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Before you install read this: https://community.bigbeartechworld.com/t/added-seafile-to-bigbearcasaos/1011#instructions-3
  title:
    en_us: seafile
  category: BigBearCasaOS
  port_map: '12145'

