name: big-bear-linkstack
services:
  big-bear-linkstack:
    image: linkstackorg/linkstack:V4
    container_name: big-bear-linkstack
    hostname: big-bear-linkstack
    environment:
      - HTTP_SERVER_NAME=www.example.xyz
      - HTTPS_SERVER_NAME=www.example.xyz
      - SERVER_ADMIN=admin@example.xyz
      - TZ=Europe/Berlin
      - PHP_MEMORY_LIMIT=512M
      - UPLOAD_MAX_FILESIZE=8M
    ports:
      - '12070:80'
      - '12071:443'
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/data
    entrypoint: /bin/sh
    command:
      - '-c'
      - cp -n -r /htdocs/database/ /data/database; cp -n /htdocs/.env /data/.env; cp -n -r /htdocs/littlelink/images /data/images; cp -n -r /htdocs/themes /data/themes; cp -n -r /htdocs/img /data/img; chown -R apache:apache /data; rm -rf /htdocs/database/; rm /htdocs/.env; rm -rf /htdocs/littlelink/images; rm -rf /htdocs/themes; rm -rf /htdocs/img; sed -i 's/FORCE_HTTPS=false/FORCE_HTTPS=true/g' /data/.env; ln -s /data/database /htdocs/database; ln -s /data/.env /htdocs/.env; ln -s /data/images /htdocs/littlelink/images; ln -s /data/themes /htdocs/themes; ln -s /data/img/ /htdocs/img; cd /htdocs; php artisan migrate --force; exec /usr/local/bin/docker-entrypoint.sh server
    x-casaos:
      envs:
        - container: HTTP_SERVER_NAME
          description:
            en_us: 'Container Variable: HTTP_SERVER_NAME'
        - container: HTTPS_SERVER_NAME
          description:
            en_us: 'Container Variable: HTTPS_SERVER_NAME'
        - container: SERVER_ADMIN
          description:
            en_us: 'Container Variable: SERVER_ADMIN'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: PHP_MEMORY_LIMIT
          description:
            en_us: 'Container Variable: PHP_MEMORY_LIMIT'
        - container: UPLOAD_MAX_FILESIZE
          description:
            en_us: 'Container Variable: UPLOAD_MAX_FILESIZE'
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
        - container: '443'
          description:
            en_us: 'Container Port: 443'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-linkstack
  description:
    en_us: LinkStack is a link-in-bio tool that allows you to create a personalized and easily customizable page that houses all the important links you want to share with your audience.
  tagline:
    en_us: Your all-in-one link sharing solution
  developer: LinkStackOrg
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/linkstack.png
  thumbnail: ''
  title:
    en_us: LinkStack
  category: BigBearCasaOS
  port_map: '12070'

