name: big-bear-npmplus
services:
  big-bear-npmplus:
    container_name: big-bear-npmplus
    image: zoeyvid/npmplus:449
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=America/Chicago
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/data
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-npmplus
  description:
    en_us: Docker container for managing Nginx proxy hosts with a simple, powerful interface
  tagline:
    en_us: NPMPlus
  developer: zoeyvid
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/nginx-proxy-manager.png
  thumbnail: ''
  title:
    en_us: NPMPlus
  category: BigBearCasaOS
  port_map: '81'

