name: big-bear-homebridge
services:
  big-bear-homebridge:
    container_name: big-bear-homebridge
    image: homebridge/homebridge:2024-05-02
    restart: unless-stopped
    environment:
      - TZ=UTC
    privileged: true
    network_mode: host
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/homebridge
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /homebridge
          description:
            en_us: 'Container Path: /homebridge'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-homebridge
  description:
    en_us: HomeKit support for the impatient.
  tagline:
    en_us: HomeKit support for the impatient.
  developer: homebridge
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/homebridge.png
  thumbnail: ''
  title:
    en_us: HomeBridge
  category: BigBearCasaOS
  port_map: '8581'

