name: big-bear-poste-io
services:
  big-bear-poste-io:
    container_name: big-bear-poste-io
    image: analogic/poste.io:2.5.9
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=UTC
    hostname: mail.example.com
    tty: true
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/data
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-poste-io
  description:
    en_us: Full stack mail server solution with SSL TLS support. POP3s, SMTP(s), IMAPs, RSPAMD, Clamav, Roundcube(HTTPS), SPF, DKIM with easy installation and web administration.
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/poste-io/screenshots/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/poste-io/screenshots/screenshot-2.png
  tagline:
    en_us: Free version of full mail server solution. POP3, SMTP, IMAP, Spamassassin, WebMail, WebAdmin
  developer: analogic
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/poste.png
  thumbnail: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/poste-io/thumbnail.png
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-poste-io-to-bigbearcasaos/3344
  title:
    en_us: Poste.io
  category: BigBearCasaOS
  port_map: '80'

