name: big-bear-faster-whisper
services:
  big-bear-faster-whisper:
    container_name: big-bear-faster-whisper
    image: linuxserver/faster-whisper:3.1.0
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WHISPER_MODEL=tiny-int8
      - WHISPER_BEAM=1
      - WHISPER_LANG=en
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
    ports:
      - '10300:10300'
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: WHISPER_MODEL
          description:
            en_us: 'Container Variable: WHISPER_MODEL'
        - container: WHISPER_BEAM
          description:
            en_us: 'Container Variable: WHISPER_BEAM'
        - container: WHISPER_LANG
          description:
            en_us: 'Container Variable: WHISPER_LANG'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
      ports:
        - container: '10300'
          description:
            en_us: 'Container Port: 10300'
x-casaos:
  architectures:
    - amd64
  main: big-bear-faster-whisper
  description:
    en_us: Faster-whisper is a reimplementation of OpenAI's Whisper model using CTranslate2, which is a fast inference engine for Transformer models. This container provides a Wyoming protocol server for faster-whisper.
  tagline:
    en_us: Faster-whisper
  developer: systran
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/faster-whisper/logo.png
  thumbnail: ''
  title:
    en_us: Faster-whisper
  category: BigBearCasaOS
  port_map: '10300'

