name: big-bear-immich
services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v2.5.6
    ports:
      - '2283:2283'
    volumes:
      - /DATA/.docker/AppData/$AppID/upload:/usr/src/app/upload
    environment:
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
      DB_DATABASE_NAME: immich
      DB_PORT: '5432'
      REDIS_HOSTNAME: immich-redis
      IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - big_bear_immich_network
    x-casaos:
      envs:
        - container: DB_HOSTNAME
          description:
            en_us: 'Container Variable: DB_HOSTNAME'
        - container: DB_USERNAME
          description:
            en_us: 'Container Variable: DB_USERNAME'
        - container: DB_PASSWORD
          description:
            en_us: 'Container Variable: DB_PASSWORD'
        - container: DB_DATABASE_NAME
          description:
            en_us: 'Container Variable: DB_DATABASE_NAME'
        - container: DB_PORT
          description:
            en_us: 'Container Variable: DB_PORT'
        - container: REDIS_HOSTNAME
          description:
            en_us: 'Container Variable: REDIS_HOSTNAME'
        - container: IMMICH_MACHINE_LEARNING_URL
          description:
            en_us: 'Container Variable: IMMICH_MACHINE_LEARNING_URL'
      volumes:
        - container: /usr/src/app/upload
          description:
            en_us: 'Container Path: /usr/src/app/upload'
      ports:
        - container: '2283'
          description:
            en_us: 'Container Port: 2283'
  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.6
    volumes:
      - /DATA/.docker/AppData/$AppID/model-cache:/cache
    environment:
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
      DB_DATABASE_NAME: casaos
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
    restart: unless-stopped
    networks:
      - big_bear_immich_network
    x-casaos:
      envs:
        - container: DB_HOSTNAME
          description:
            en_us: 'Container Variable: DB_HOSTNAME'
        - container: DB_USERNAME
          description:
            en_us: 'Container Variable: DB_USERNAME'
        - container: DB_PASSWORD
          description:
            en_us: 'Container Variable: DB_PASSWORD'
        - container: DB_DATABASE_NAME
          description:
            en_us: 'Container Variable: DB_DATABASE_NAME'
        - container: DB_PORT
          description:
            en_us: 'Container Variable: DB_PORT'
        - container: REDIS_HOSTNAME
          description:
            en_us: 'Container Variable: REDIS_HOSTNAME'
      volumes:
        - container: /cache
          description:
            en_us: 'Container Path: /cache'
  redis:
    container_name: immich-redis
    image: redis:6.2.20-alpine@sha256:2185e741f4c1e7b0ea9ca1e163a3767c4270a73086b6bbea2049a7203212fb7f
    restart: always
    networks:
      - big_bear_immich_network
  database:
    container_name: immich-postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: casaos
      POSTGRES_USER: casaos
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /DATA/.docker/AppData/$AppID/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - big_bear_immich_network
    x-casaos:
      envs:
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
        - container: PG_DATA
          description:
            en_us: 'Container Variable: PG_DATA'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
networks:
  big_bear_immich_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: immich-server
  description:
    en_us: Self-hosted photo and video storage.
  tagline:
    en_us: Immich
  developer: immich-app
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/immich.png
  thumbnail: ''
  title:
    en_us: Immich
  category: BigBearCasaOS
  port_map: '2283'

