name: big-bear-budibase
services:
  big-bear-budibase:
    container_name: big-bear-budibase
    image: budibase/budibase:3.31.5
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/data
    ports:
      - '12010:80'
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-budibase
  description:
    en_us: Low code platform for creating internal tools, workflows, and admin panels in minutes. Supports PostgreSQL, MySQL, MSSQL, MongoDB, Rest API, Docker, K8s, and more 🚀. Budibase, the low code platform you'll enjoy using ⚡
  tagline:
    en_us: Internal tools made easy.
  developer: Budibase
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/budibase.png
  thumbnail: ''
  title:
    en_us: Budibase
  category: BigBearCasaOS
  port_map: '12010'

