name: big-bear-mailpit
services:
  app:
    image: axllent/mailpit:v1.29
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/data
    environment:
      - TZ=UTC
    ports:
      - '12076:8025'
      - '12077:1025'
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
      ports:
        - container: '8025'
          description:
            en_us: 'Container Port: 8025'
        - container: '1025'
          description:
            en_us: 'Container Port: 1025'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Mailpit is a multi-platform email testing tool & API for developers.
  tagline:
    en_us: Mailpit
  developer: axllent
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/mailpit/logo.png
  thumbnail: https://github.com/axllent/mailpit/blob/develop/docs/screenshot.png
  title:
    en_us: Mailpit
  category: BigBearCasaOS
  port_map: '12076'

