name: big-bear-obsidian-livesync
services:
  app:
    container_name: obsidian-livesync
    image: couchdb:3.5.0
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data/couchdb:/opt/couchdb/data
      - /DATA/.docker/AppData/$AppID/data/local.ini:/opt/couchdb/etc/local.ini
    environment:
      - COUCHDB_USER=casaos
      - COUCHDB_PASSWORD=casaos
    ports:
      - '5984:5984'
    x-casaos:
      envs:
        - container: COUCHDB_USER
          description:
            en_us: 'Container Variable: COUCHDB_USER'
        - container: COUCHDB_PASSWORD
          description:
            en_us: 'Container Variable: COUCHDB_PASSWORD'
      volumes:
        - container: /opt/couchdb/data
          description:
            en_us: 'Container Path: /opt/couchdb/data'
        - container: /opt/couchdb/etc/local.ini
          description:
            en_us: 'Container Path: /opt/couchdb/etc/local.ini'
      ports:
        - container: '5984'
          description:
            en_us: 'Container Port: 5984'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Self-hosted database for synchronizing Obsidian vaults.
  tagline:
    en_us: Self-hosted database for synchronizing Obsidian vaults.
  developer: couchdb
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/obsidian.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Run this script before installing the big-bear-obsidian-livesync application:

        ```
        bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/generate-obsidian-livesync-local-ini/run.sh)"
        ```

        Video Tutorial: https://youtu.be/-n1abMPLmFg

        After running this script, you need to restart the container.
  title:
    en_us: Obsidian Livesync
  category: BigBearCasaOS
  port_map: '5984'

