name: big-bear-romm
services:
  big-bear-romm:
    image: rommapp/romm:4.6.1
    container_name: big-bear-romm
    environment:
      - DB_HOST=big-bear-rommdb
      - DB_PORT=3306
      - DB_USER=romm-user
      - DB_NAME=romm
      - DB_PASSWD=casaos
      - ROMM_AUTH_SECRET_KEY=<secret key>
      - IGDB_CLIENT_ID=<igdb client id>
      - IGDB_CLIENT_SECRET=<igdb client secret>
      - MOBYGAMES_API_KEY=<moby api key>
      - STEAMGRIDDB_API_KEY=<sgdb api key>
      - SCREENSCRAPER_USER=<screenscraper user>
      - SCREENSCRAPER_PASSWORD=<screenscraper password>
      - RETROACHIEVEMENTS_API_KEY=<retroachievements api key>
      - HASHEOUS_API_ENABLED=true
      - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=true
      - ENABLE_SCHEDULED_RESCAN=true
      - ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB=true
    volumes:
      - /DATA/.docker/AppData/$AppID/resources:/romm/resources
      - /DATA/.docker/AppData/$AppID/redis-data:/redis-data
      - /media/Safe-Storage/Library/Games:/romm/library
      - /DATA/.docker/AppData/$AppID/assets:/romm/assets
      - /DATA/.docker/AppData/$AppID/config:/romm/config
      - /DATA/.docker/AppData/$AppID/logs:/romm/logs
    ports:
      - '12141:8080'
    depends_on:
      - big-bear-rommdb
    restart: unless-stopped
    networks:
      - big-bear-romm-network
    x-casaos:
      envs:
        - container: DB_HOST
          description:
            en_us: 'Container Variable: DB_HOST'
        - container: DB_PORT
          description:
            en_us: 'Container Variable: DB_PORT'
        - container: DB_USER
          description:
            en_us: 'Container Variable: DB_USER'
        - container: DB_NAME
          description:
            en_us: 'Container Variable: DB_NAME'
        - container: DB_PASSWD
          description:
            en_us: 'Container Variable: DB_PASSWD'
        - container: ROMM_AUTH_SECRET_KEY
          description:
            en_us: 'Container Variable: ROMM_AUTH_SECRET_KEY'
        - container: IGDB_CLIENT_ID
          description:
            en_us: 'Container Variable: IGDB_CLIENT_ID'
        - container: IGDB_CLIENT_SECRET
          description:
            en_us: 'Container Variable: IGDB_CLIENT_SECRET'
        - container: MOBYGAMES_API_KEY
          description:
            en_us: 'Container Variable: MOBYGAMES_API_KEY'
        - container: STEAMGRIDDB_API_KEY
          description:
            en_us: 'Container Variable: STEAMGRIDDB_API_KEY'
        - container: SCREENSCRAPER_USER
          description:
            en_us: 'Container Variable: SCREENSCRAPER_USER'
        - container: SCREENSCRAPER_PASSWORD
          description:
            en_us: 'Container Variable: SCREENSCRAPER_PASSWORD'
        - container: RETROACHIEVEMENTS_API_KEY
          description:
            en_us: 'Container Variable: RETROACHIEVEMENTS_API_KEY'
        - container: HASHEOUS_API_ENABLED
          description:
            en_us: 'Container Variable: HASHEOUS_API_ENABLED'
        - container: ENABLE_RESCAN_ON_FILESYSTEM_CHANGE
          description:
            en_us: 'Container Variable: ENABLE_RESCAN_ON_FILESYSTEM_CHANGE'
        - container: ENABLE_SCHEDULED_RESCAN
          description:
            en_us: 'Container Variable: ENABLE_SCHEDULED_RESCAN'
        - container: ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB
          description:
            en_us: 'Container Variable: ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB'
      volumes:
        - container: /romm/resources
          description:
            en_us: 'Container Path: /romm/resources'
        - container: /redis-data
          description:
            en_us: 'Container Path: /redis-data'
        - container: /romm/library
          description:
            en_us: 'Container Path: /romm/library'
        - container: /romm/assets
          description:
            en_us: 'Container Path: /romm/assets'
        - container: /romm/config
          description:
            en_us: 'Container Path: /romm/config'
        - container: /romm/logs
          description:
            en_us: 'Container Path: /romm/logs'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
  big-bear-rommdb:
    image: mariadb:latest
    container_name: big-bear-rommdb
    environment:
      - MYSQL_ROOT_PASSWORD=casaos
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=casaos
    volumes:
      - /DATA/.docker/AppData/$AppID/mysql:/var/lib/mysql
    ports:
      - '12142:3306'
    restart: unless-stopped
    networks:
      - big-bear-romm-network
    x-casaos:
      envs:
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_ROOT_PASSWORD'
        - container: MYSQL_DATABASE
          description:
            en_us: 'Container Variable: MYSQL_DATABASE'
        - container: MYSQL_USER
          description:
            en_us: 'Container Variable: MYSQL_USER'
        - container: MYSQL_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_PASSWORD'
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: 'Container Path: /var/lib/mysql'
      ports:
        - container: '3306'
          description:
            en_us: 'Container Port: 3306'
networks:
  big-bear-romm-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-romm
  description:
    en_us: ROM manager for organizing, enriching, and playing retro games, with support for 400+ platforms.
  tagline:
    en_us: RomM
  developer: RomM Team
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/romm.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Run this script before installing the big-bear-romm application:

        ```
        bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/generate-romm-config/run.sh)"
        ```

        After running this script, you need to restart the container.
  title:
    en_us: RomM
  category: BigBearCasaOS
  port_map: '12141'

