name: big-bear-playit-docker-web
services:
  big-bear-playit-docker-web:
    container_name: big-bear-playit-docker-web
    image: wisdomsky/playit-docker-web:1.2
    restart: unless-stopped
    network_mode: host
    environment:
      - WEBUI_PORT=8008
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
    x-casaos:
      envs:
        - container: WEBUI_PORT
          description:
            en_us: 'Container Variable: WEBUI_PORT'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-playit-docker-web
  description:
    en_us: Playit.gg is a global proxy that allows anyone to host a server without port forwarding. We use tunneling. Only the server needs to run the program, not every player!
  tagline:
    en_us: Playit.gg is a global proxy that allows anyone to host a server without port forwarding.
  developer: wisdomsky
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/playit-docker-web/logo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-playit-docker-web-to-bigbearcasaos/2276?u=dragonfire1119
  title:
    en_us: Playit Docker Web
  category: BigBearCasaOS
  port_map: '8008'

