name: big-bear-libretranslate
services:
  big-bear-libretranslate:
    container_name: big-bear-libretranslate
    image: libretranslate/libretranslate:v1.9.5
    restart: unless-stopped
    environment:
      - LT_API_KEYS=true
      - LT_API_KEYS_DB_PATH=/app/db/api_keys.db
      - LT_UPDATE_MODELS=true
      - LT_LOAD_ONLY=en,fr,es,de,it,pt,ru,ja,zh
    volumes:
      - /DATA/.docker/AppData/$AppID/db:/app/db
      - /DATA/.docker/AppData/$AppID/.local:/home/libretranslate/.local
    ports:
      - '12069:5000'
    tty: true
    healthcheck:
      test:
        - CMD-SHELL
        - ./venv/bin/python scripts/healthcheck.py
    x-casaos:
      envs:
        - container: LT_API_KEYS
          description:
            en_us: 'Container Variable: LT_API_KEYS'
        - container: LT_API_KEYS_DB_PATH
          description:
            en_us: 'Container Variable: LT_API_KEYS_DB_PATH'
        - container: LT_UPDATE_MODELS
          description:
            en_us: 'Container Variable: LT_UPDATE_MODELS'
        - container: LT_LOAD_ONLY
          description:
            en_us: 'Container Variable: LT_LOAD_ONLY'
      volumes:
        - container: /app/db
          description:
            en_us: 'Container Path: /app/db'
        - container: /home/libretranslate/.local
          description:
            en_us: 'Container Path: /home/libretranslate/.local'
      ports:
        - container: '5000'
          description:
            en_us: 'Container Port: 5000'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-libretranslate
  description:
    en_us: Free and Open Source Machine Translation API, entirely self-hosted. Unlike other APIs, it doesn't rely on proprietary providers such as Google or Azure to perform translations. Instead, its translation engine is powered by the open source Argos Translate library.
  tagline:
    en_us: Free and Open Source Machine Translation API. 100% self-hosted, offline capable and easy to setup.
  developer: LibreTranslate
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/libretranslate/logo.png
  thumbnail: ''
  title:
    en_us: LibreTranslate
  category: BigBearCasaOS
  port_map: '12069'

