name: big-bear-piwigo
services:
  big-bear-piwigo:
    container_name: big-bear-piwigo
    image: linuxserver/piwigo:16.3.0
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
      - /DATA/.docker/AppData/$AppID/gallery:/gallery
    ports:
      - '12121:80'
    networks:
      - big_bear_piwigo_network
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /gallery
          description:
            en_us: 'Container Path: /gallery'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
  big-bear-piwigo-db:
    image: mariadb:10.6
    container_name: big-bear-piwigo-db
    environment:
      - MYSQL_ROOT_PASSWORD=3cf3f2c4-3415-4efe-b478-db7b6f0b9934
      - MYSQL_DATABASE=piwigo
      - MYSQL_USER=big_bear_piwigo
      - MYSQL_PASSWORD=358fac48-4beb-4027-9c11-840464aca400
    volumes:
      - /DATA/.docker/AppData/$AppID/mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - big_bear_piwigo_network
    x-casaos:
      envs:
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_ROOT_PASSWORD'
        - container: MYSQL_DATABASE
          description:
            en_us: 'Container Variable: MYSQL_DATABASE'
        - container: MYSQL_USER
          description:
            en_us: 'Container Variable: MYSQL_USER'
        - container: MYSQL_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_PASSWORD'
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: 'Container Path: /var/lib/mysql'
networks:
  big_bear_piwigo_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-piwigo
  description:
    en_us: Piwigo is a photo gallery software for the web that comes with powerful features to publish and manage your collection of pictures.
  tagline:
    en_us: Piwigo
  developer: piwigo
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/piwigo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Before you install read this: https://community.bigbeartechworld.com/t/added-piwigo-to-bigbearcasaos/1133#documentation-3
  title:
    en_us: Piwigo
  category: BigBearCasaOS
  port_map: '12121'

