name: big-bear-ayon
services:
  big-bear-ayon:
    container_name: big-bear-ayon
    image: ynput/ayon:1.3.6-20240823
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:5000/api/info
      interval: 10s
      timeout: 2s
      retries: '3'
    volumes:
      - /DATA/.docker/AppData/$AppID/addons:/addons
      - /DATA/.docker/AppData/$AppID/storage:/storage
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '5000:5000'
    expose:
      - '5000'
    networks:
      - big-bear-ayon-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    x-casaos:
      volumes:
        - container: /addons
          description:
            en_us: 'Container Path: /addons'
        - container: /storage
          description:
            en_us: 'Container Path: /storage'
        - container: /etc/localtime
          description:
            en_us: 'Container Path: /etc/localtime'
      ports:
        - container: '5000'
          description:
            en_us: 'Container Port: 5000'
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=ayon
      - POSTGRES_PASSWORD=ayon
      - POSTGRES_DB=ayon
    volumes:
      - /DATA/.docker/AppData/$AppID/postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ayon
      interval: 10s
      timeout: 5s
      retries: '5'
    expose:
      - '5432'
    networks:
      - big-bear-ayon-network
    x-casaos:
      envs:
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
  redis:
    image: redis:7.4.6-alpine@sha256:7a7c6b5c49a6896d0a58ee0c6dc0dcabe14f30f0a2f7d2d1362d276fa2d43166
    container_name: redis
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/redis:/data
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      interval: 5s
      timeout: 5s
      retries: '5'
    expose:
      - '6379'
    networks:
      - big-bear-ayon-network
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
networks:
  big-bear-ayon-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
  main: big-bear-ayon
  description:
    en_us: This is the official Docker-based deployment for the Ayon Server. Ayon is a robust tool designed to manage and automate workflows in the animation and visual effects industries.
  tagline:
    en_us: Ayon
  developer: ynput
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/ayon/logo.png
  thumbnail: ''
  title:
    en_us: Ayon
  category: BigBearCasaOS
  port_map: '5000'

