name: big-bear-farmos
services:
  big-bear-farmos:
    container_name: big-bear-farmos
    image: farmos/farmos:3.5.1
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/sites:/opt/drupal/web/sites
    ports:
      - '12028:80'
    networks:
      - big-bear-farmos-network
    x-casaos:
      volumes:
        - container: /opt/drupal/web/sites
          description:
            en_us: 'Container Path: /opt/drupal/web/sites'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
  big-bear-farmos-db:
    container_name: big-bear-farmos-db
    image: mariadb:10
    volumes:
      - /DATA/.docker/AppData/$AppID/db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 037ed96f-5f27-4fa8-bd7f-49b4a804a05c
      MYSQL_DATABASE: big_bear_farmos
      MYSQL_USER: farmos
      MYSQL_PASSWORD: 037ed96f-5f27-4fa8-bd7f-49b4a804a05c
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - big-bear-farmos-network
    x-casaos:
      envs:
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_ROOT_PASSWORD'
        - container: MYSQL_DATABASE
          description:
            en_us: 'Container Variable: MYSQL_DATABASE'
        - container: MYSQL_USER
          description:
            en_us: 'Container Variable: MYSQL_USER'
        - container: MYSQL_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_PASSWORD'
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: 'Container Path: /var/lib/mysql'
      ports:
        - container: '3306'
          description:
            en_us: 'Container Port: 3306'
networks:
  big-bear-farmos-network:
    name: big-bear-farmos-network
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-farmos
  description:
    en_us: farmOS is a web-based application for farm management, planning, and record keeping. It is developed by a community of volunteers and aims to provide a standard platform for farmers, developers, and researchers to build upon.
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/farmos/screenshots/screenshot-1.png
  tagline:
    en_us: A web-based farm record keeping application.
  developer: farmOS
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/farmos/logo.jpeg
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-farmos-to-bigbearcasaos/2334?u=dragonfire1119
  title:
    en_us: FarmOS
  category: BigBearCasaOS
  port_map: '12028'

