name: big-bear-dashy
services:
  big-bear-dashy:
    image: lissy93/dashy:3.1.0
    container_name: big-bear-dashy
    volumes:
      - /DATA/.docker/AppData/$AppID/public:/app/public
    ports:
      - '4000:8080'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - node
        - /app/services/healthcheck
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    x-casaos:
      envs:
        - container: NODE_ENV
          description:
            en_us: 'Container Variable: NODE_ENV'
      volumes:
        - container: /app/public
          description:
            en_us: 'Container Path: /app/public'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-dashy
  description:
    en_us: Dashy helps you organize your self-hosted services by making them accessible from a single place
  tagline:
    en_us: Dashy
  developer: Lissy93
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/dashy.png
  thumbnail: ''
  title:
    en_us: Dashy
  category: BigBearCasaOS
  port_map: '4000'

