name: big-bear-write-freely
services:
  big-bear-write-freely:
    container_name: big-bear-write-freely
    image: nephatrine/write-freely:0.16
    restart: unless-stopped
    environment:
      TZ: UTC
      PUID: 1000
      PGID: 1000
    volumes:
      - /DATA/.docker/AppData/$AppID/data/config:/mnt/config
    ports:
      - 70:70/tcp
      - '12182:8080'
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
      volumes:
        - container: /mnt/config
          description:
            en_us: 'Container Path: /mnt/config'
      ports:
        - container: '70'
          description:
            en_us: 'Container Port: 70'
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-write-freely
  description:
    en_us: WriteFreely is a clean, minimalist publishing platform made for writers. Start a blog, share knowledge within your organization, or build a community around the shared act of writing.
  tagline:
    en_us: Markdown-based publishing platform.
  developer: nephatrine
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/write-freely/logo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-write-freely-to-bigbearcasaos/3164?u=dragonfire1119
  title:
    en_us: Write Freely
  category: BigBearCasaOS
  port_map: '70'

