name: big-bear-octoprint
services:
  app:
    container_name: octoprint
    image: octoprint/octoprint:1.11.7
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/octoprint:/octoprint
    ports:
      - '12092:80'
    x-casaos:
      volumes:
        - container: /octoprint
          description:
            en_us: 'Container Path: /octoprint'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: OctoPrint is the snappy web interface for your 3D printer!
  tagline:
    en_us: OctoPrint
  developer: octoprint
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/octoprint.png
  thumbnail: ''
  title:
    en_us: OctoPrint
  category: BigBearCasaOS
  port_map: '12092'

