name: big-bear-stalwart-mail
services:
  big-bear-stalwart-mail:
    container_name: big-bear-stalwart-mail
    image: stalwartlabs/stalwart:v0.15.5
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/opt/stalwart
    ports:
      - '12152:8080'
      - 25:25/tcp
      - 143:143/tcp
      - 465:465/tcp
      - 587:587/tcp
      - 993:993/tcp
      - 4190:4190/tcp
    x-casaos:
      volumes:
        - container: /opt/stalwart
          description:
            en_us: 'Container Path: /opt/stalwart'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
        - container: '25'
          description:
            en_us: 'Container Port: 25'
        - container: '143'
          description:
            en_us: 'Container Port: 143'
        - container: '465'
          description:
            en_us: 'Container Port: 465'
        - container: '587'
          description:
            en_us: 'Container Port: 587'
        - container: '993'
          description:
            en_us: 'Container Port: 993'
        - container: '4190'
          description:
            en_us: 'Container Port: 4190'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-stalwart-mail
  description:
    en_us: Stalwart Mail Server is an open-source mail server solution with JMAP, IMAP4, POP3, and SMTP support and a wide range of modern features. It is written in Rust and designed to be secure, fast, robust and scalable.
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/stalwart-mail/thumbnail.gif
  tagline:
    en_us: Secure & Modern All-in-One Mail Server (IMAP, JMAP, POP3, SMTP) 🛡️
  developer: stalwartlabs
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/stalwart.png
  thumbnail: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/stalwart-mail/thumbnail.gif
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-stalwart-to-bigbearcasaos/3342#p-5723-documentation-3
  title:
    en_us: Stalwart Mail
  category: BigBearCasaOS
  port_map: '12152'

