name: big-bear-goaway
services:
  big-bear-goaway:
    container_name: big-bear-goaway
    image: pommee/goaway:0.63.9
    restart: unless-stopped
    ports:
      - 12041:53/udp
      - '12042:53'
      - '12043:8080'
    network_mode: bridge
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/app/config
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
    x-casaos:
      volumes:
        - container: /app/config
          description:
            en_us: 'Container Path: /app/config'
      ports:
        - container: '53'
          description:
            en_us: 'Container Port: 53'
        - container: '53'
          description:
            en_us: 'Container Port: 53'
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-goaway
  description:
    en_us: GoAway is a lightweight DNS sinkhole that blocks ads, trackers, and malicious domains at the network level. It provides a web-based admin dashboard for management and supports customizable blocking rules with real-time statistics tracking.
  tagline:
    en_us: Lightweight DNS sinkhole for blocking ads and trackers
  developer: pommee
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/goaway.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Visit the community post for setup instructions and community support:
        https://community.bigbeartechworld.com/t/added-goaway-to-bigbearcasaos/4085
  title:
    en_us: GoAway
  category: BigBearCasaOS
  port_map: '12041'

