name: big-bear-kasm
services:
  app:
    container_name: big-bear-kasm
    image: linuxserver/kasm:1.120.20221218
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    volumes:
      - /DATA/.docker/AppData/$AppID/opt:/opt
      - /DATA/.docker/AppData/$AppID/profiles:/profiles
      - /dev/input:/dev/input
      - /run/udev/data:/run/udev/data
    ports:
      - '12057:3000'
      - '12058:443'
    environment:
      - KASM_PORT=443
    x-casaos:
      envs:
        - container: KASM_PORT
          description:
            en_us: 'Container Variable: KASM_PORT'
      volumes:
        - container: /opt
          description:
            en_us: 'Container Path: /opt'
        - container: /profiles
          description:
            en_us: 'Container Path: /profiles'
        - container: /dev/input
          description:
            en_us: 'Container Path: /dev/input'
        - container: /run/udev/data
          description:
            en_us: 'Container Path: /run/udev/data'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
        - container: '443'
          description:
            en_us: 'Container Port: 443'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: The Container Streaming Platform - Streaming containerized apps and desktops to end-users. The Workspaces platform provides enterprise-class orchestration, data loss prevention, and web streaming technology to enable the delivery of containerized workloads to your browser.
  tagline:
    en_us: Kasm
  developer: Kasm
  author: BigBearCommunity
  icon: https://avatars.githubusercontent.com/u/44181855?s=280&v=4
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Admin default address: admin@kasm.local
        User default address: user@kasm.local
  title:
    en_us: Kasm
  category: BigBearCasaOS
  port_map: '12057'

