name: big-bear-mealie
services:
  app:
    container_name: big-bear-mealie
    image: hkotel/mealie:v3.11.0
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/app/data
    ports:
      - '9925:9000'
    x-casaos:
      volumes:
        - container: /app/data
          description:
            en_us: 'Container Path: /app/data'
      ports:
        - container: '9000'
          description:
            en_us: 'Container Port: 9000'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Mealie is a self hosted recipe manager and meal planner with a RestAPI backend and a reactive frontend application built in Vue for a pleasant user experience for the whole family. Easily add recipes into your database by providing the url and mealie will automatically import the relevant data or add a family recipe with the UI editor
  tagline:
    en_us: Mealie
  developer: mealie-recipes
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/mealie.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this: https://community.bigbeartechworld.com/t/added-mealie-to-bigbearcasaos/587
  title:
    en_us: Mealie
  category: BigBearCasaOS
  port_map: '9925'

