name: big-bear-pd3f
services:
  web:
    container_name: big-bear-pd3f
    image: pd3f/pd3f:latest
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/uploads:/uploads/
    ports:
      - '1616:5000'
    command:
      - gunicorn
      - app:app
      - '--bind=0.0.0.0:5000'
    depends_on:
      - redis
      - parsr
      - worker
      - ocr_worker
    networks:
      - big-bear-pd3f-network
    x-casaos:
      volumes:
        - container: /uploads/
          description:
            en_us: 'Container Path: /uploads/'
      ports:
        - container: '5000'
          description:
            en_us: 'Container Port: 5000'
  parsr:
    image: axarev/parsr:v1.2.2
    networks:
      - big-bear-pd3f-network
    expose:
      - 3001
  redis:
    image: redis:6.2.20-alpine@sha256:2185e741f4c1e7b0ea9ca1e163a3767c4270a73086b6bbea2049a7203212fb7f
    networks:
      - big-bear-pd3f-network
    expose:
      - 6379
  worker:
    image: pd3f/pd3f:latest
    depends_on:
      - parsr
      - redis
    networks:
      - big-bear-pd3f-network
    volumes:
      - /DATA/.docker/AppData/$AppID/cache:/root/.cache/
      - /DATA/.docker/AppData/$AppID/to-ocr:/to-ocr/
      - /DATA/.docker/AppData/$AppID/uploads:/uploads/
    environment:
      - KEEP_RESULTS_HOURS=24
    command:
      - rq
      - worker
      - '-u'
      - redis://redis:6379
      - '--results-ttl'
      - '86400'
    x-casaos:
      envs:
        - container: KEEP_RESULTS_HOURS
          description:
            en_us: 'Container Variable: KEEP_RESULTS_HOURS'
      volumes:
        - container: /root/.cache/
          description:
            en_us: 'Container Path: /root/.cache/'
        - container: /to-ocr/
          description:
            en_us: 'Container Path: /to-ocr/'
        - container: /uploads/
          description:
            en_us: 'Container Path: /uploads/'
  ocr_worker:
    image: pd3f/pd3f-ocr:latest
    networks:
      - big-bear-pd3f-network
    volumes:
      - /DATA/.docker/AppData/$AppID/to-ocr:/to-ocr/
    x-casaos:
      volumes:
        - container: /to-ocr/
          description:
            en_us: 'Container Path: /to-ocr/'
networks:
  big-bear-pd3f-network:
    name: big-bear-pd3f-network
x-casaos:
  architectures:
    - amd64
    - arm64
  main: web
  description:
    en_us: pd3f is a PDF text extraction pipeline that is self-hosted, local-first and Docker-based. It reconstructs the original continuous text with the help of machine learning.
  tagline:
    en_us: PD3F
  developer: pd3f
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/pd3f/logo.jpg
  thumbnail: ''
  title:
    en_us: PD3F
  category: BigBearCasaOS
  port_map: '1616'

