name: big-bear-bookstack
services:
  big-bear-bookstack:
    container_name: big-bear-bookstack
    image: linuxserver/bookstack:25.12.20251224
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
    environment:
      - APP_KEY=base64:3w/hRS2HYVFH5tJqD9AFlyurTh8mBByMKeMRyH9kEEQ=
      - APP_URL=http://[change to your IP]:8080
      - DB_HOST=big-bear-bookstack-db
      - DB_USERNAME=bigbear
      - DB_PASSWORD=a3e8949f-484c-4877-afdb-391f892f9bb6
      - DB_DATABASE=bookstackapp
    ports:
      - '12009:80'
    depends_on:
      - big-bear-bookstack-db
    networks:
      - big_bear_bookstack_network
    x-casaos:
      envs:
        - container: APP_KEY
          description:
            en_us: 'Container Variable: APP_KEY'
        - container: APP_URL
          description:
            en_us: 'Container Variable: APP_URL'
        - container: DB_HOST
          description:
            en_us: 'Container Variable: DB_HOST'
        - container: DB_USERNAME
          description:
            en_us: 'Container Variable: DB_USERNAME'
        - container: DB_PASSWORD
          description:
            en_us: 'Container Variable: DB_PASSWORD'
        - container: DB_DATABASE
          description:
            en_us: 'Container Variable: DB_DATABASE'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
  big-bear-bookstack-db:
    image: linuxserver/mariadb:10.11.6
    container_name: big-bear-bookstack-db
    environment:
      - MYSQL_ROOT_PASSWORD=793e92b7-58d2-47b9-aae5-b8c7d58bd699
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bigbear
      - MYSQL_PASSWORD=a3e8949f-484c-4877-afdb-391f892f9bb6
    volumes:
      - /DATA/.docker/AppData/$AppID/mysql:/config
    restart: unless-stopped
    networks:
      - big_bear_bookstack_network
    x-casaos:
      envs:
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_ROOT_PASSWORD'
        - container: MYSQL_DATABASE
          description:
            en_us: 'Container Variable: MYSQL_DATABASE'
        - container: MYSQL_USER
          description:
            en_us: 'Container Variable: MYSQL_USER'
        - container: MYSQL_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_PASSWORD'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
networks:
  big_bear_bookstack_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-bookstack
  description:
    en_us: BookStack is a simple, self-hosted, easy-to-use platform for organising and storing information. Default login admin@admin.com password password
  tagline:
    en_us: BookStack
  developer: Dan Brown
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/bookstack.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Before you install read this: https://community.bigbeartechworld.com/t/added-bookstack-to-bigbearcasaos/1262#p-2263-documentation-3
  title:
    en_us: bookstack
  category: BigBearCasaOS
  port_map: '12009'

