name: big-bear-pwpush
services:
  big-bear-pwpush:
    container_name: big-bear-pwpush
    image: pglombardo/pwpush:1.69.1
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql2://pwpusher:6280144a-56af-486f-9088-ac7301399328@big-bear-pwpush-db:3306/passwordpusher_db
      PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT: '1'
      PWP__PW__EXPIRE_AFTER_VIEWS_MIN: '1'
      PWP__PW__RETRIEVAL_STEP_DEFAULT: 'true'
    volumes:
      - /DATA/.docker/AppData/$AppID/storage:/opt/PasswordPusher/storage
    ports:
      - '5100:5100'
    networks:
      - big_bear_pwpush_network
    x-casaos:
      envs:
        - container: DATABASE_URL
          description:
            en_us: 'Container Variable: DATABASE_URL'
        - container: PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT
          description:
            en_us: 'Container Variable: PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT'
        - container: PWP__PW__EXPIRE_AFTER_VIEWS_MIN
          description:
            en_us: 'Container Variable: PWP__PW__EXPIRE_AFTER_VIEWS_MIN'
        - container: PWP__PW__RETRIEVAL_STEP_DEFAULT
          description:
            en_us: 'Container Variable: PWP__PW__RETRIEVAL_STEP_DEFAULT'
      volumes:
        - container: /opt/PasswordPusher/storage
          description:
            en_us: 'Container Path: /opt/PasswordPusher/storage'
      ports:
        - container: '5100'
          description:
            en_us: 'Container Port: 5100'
  big-bear-pwpush-db:
    container_name: big-bear-pwpush-db
    image: mariadb:10.6.5
    ports:
      - '12100:3306'
    environment:
      MARIADB_USER: pwpusher
      MARIADB_PASSWORD: 6280144a-56af-486f-9088-ac7301399328
      MARIADB_DATABASE: passwordpusher_db
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - /DATA/.docker/AppData/$AppID/mysql:/var/lib/mysql
    networks:
      - big_bear_pwpush_network
    x-casaos:
      envs:
        - container: MARIADB_USER
          description:
            en_us: 'Container Variable: MARIADB_USER'
        - container: MARIADB_PASSWORD
          description:
            en_us: 'Container Variable: MARIADB_PASSWORD'
        - container: MARIADB_DATABASE
          description:
            en_us: 'Container Variable: MARIADB_DATABASE'
        - container: MARIADB_RANDOM_ROOT_PASSWORD
          description:
            en_us: 'Container Variable: MARIADB_RANDOM_ROOT_PASSWORD'
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: 'Container Path: /var/lib/mysql'
      ports:
        - container: '3306'
          description:
            en_us: 'Container Port: 3306'
networks:
  big_bear_pwpush_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-pwpush
  description:
    en_us: Password Pusher is an open source application to communicate passwords over the web. Links to passwords expire after a certain number of views and/or time has passed.
  tagline:
    en_us: Give your users the tools to be secure by default.
  developer: pglombardo
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/password-pusher.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-password-pusher-to-bigbearcasaos/1508?u=dragonfire1119
  title:
    en_us: Password Pusher
  category: BigBearCasaOS
  port_map: '5100'

