name: big-bear-zigbee2mqtt
services:
  big-bear-zigbee2mqtt:
    container_name: big-bear-zigbee2mqtt
    image: koenkk/zigbee2mqtt:2.9.1
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - '12183:8080'
    environment:
      - TZ=UTC
    devices:
      - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /app/data
          description:
            en_us: 'Container Path: /app/data'
        - container: /run/udev
          description:
            en_us: 'Container Path: /run/udev'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-zigbee2mqtt
  description:
    en_us: Zigbee to MQTT bridge, get rid of your proprietary Zigbee bridges
  tagline:
    en_us: Zigbee to MQTT bridge
  developer: koenkk
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/zigbee2mqtt.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Before you install read this: https://community.bigbeartechworld.com/t/added-zigbee2mqtt-to-bigbearcasaos/1337#documentation-3
  title:
    en_us: Zigbee to MQTT bridge
  category: BigBearCasaOS
  port_map: '12183'

