name: big-bear-gem-digest-bot
services:
  big-bear-gem-digest-bot:
    container_name: big-bear-gem-digest-bot
    image: piero24/gemdigest:1.0
    volumes:
      - /DATA/.docker/AppData/$AppID/extra/configs:/gem_digest_bot/extra_configs
    environment:
      TELEGRAM_API_KEY: TELEGRAM_API_KEY
      GEMINI_API_KEY: GEMINI_API_KEY
      ADMIN_USER_ID: 123;456
    restart: unless-stopped
    ports:
      - '3333:8080'
    x-casaos:
      envs:
        - container: TELEGRAM_API_KEY
          description:
            en_us: 'Container Variable: TELEGRAM_API_KEY'
        - container: GEMINI_API_KEY
          description:
            en_us: 'Container Variable: GEMINI_API_KEY'
        - container: ADMIN_USER_ID
          description:
            en_us: 'Container Variable: ADMIN_USER_ID'
      volumes:
        - container: /gem_digest_bot/extra_configs
          description:
            en_us: 'Container Path: /gem_digest_bot/extra_configs'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-gem-digest-bot
  description:
    en_us: Simplify your reads, amplify your time! 📚✨ GemDigest is a Telegram bot that summarizes articles from any website into bite-sized nuggets, saving you time and energy for what matters most. 📱👋
  tagline:
    en_us: Your personal article summarizer
  developer: Armaggheddon
  author: BigBearCommunity
  icon: https://cdn.jsdelivr.net/gh/Piero24/GemDigest/.github/images/casOS_logo.png
  thumbnail: ''
  title:
    en_us: GemDigest Bot
  category: BigBearCasaOS
  port_map: '3333'

