name: big-bear-ls-adguard-home-sync
services:
  big-bear-ls-adguard-home-sync:
    container_name: big-bear-ls-adguard-home-sync
    image: linuxserver/adguardhome-sync:0.9.0
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - LOG_LEVEL=info
      - ORIGIN_URL=https://192.168.1.2:3000
      - ORIGIN_USERNAME=bigbear
      - ORIGIN_PASSWORD=casaos
      - REPLICA_URL=https://192.168.1.3:3000
      - REPLICA_USERNAME=bigbear
      - REPLICA_PASSWORD=casaos
      - CRON="0 */2 * * *"
      - RUN_ON_START=true
      - API_PORT=8080
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
    ports:
      - '12073:8080'
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: LOG_LEVEL
          description:
            en_us: 'Container Variable: LOG_LEVEL'
        - container: ORIGIN_URL
          description:
            en_us: 'Container Variable: ORIGIN_URL'
        - container: ORIGIN_USERNAME
          description:
            en_us: 'Container Variable: ORIGIN_USERNAME'
        - container: ORIGIN_PASSWORD
          description:
            en_us: 'Container Variable: ORIGIN_PASSWORD'
        - container: REPLICA_URL
          description:
            en_us: 'Container Variable: REPLICA_URL'
        - container: REPLICA_USERNAME
          description:
            en_us: 'Container Variable: REPLICA_USERNAME'
        - container: REPLICA_PASSWORD
          description:
            en_us: 'Container Variable: REPLICA_PASSWORD'
        - container: CRON
          description:
            en_us: 'Container Variable: CRON'
        - container: RUN_ON_START
          description:
            en_us: 'Container Variable: RUN_ON_START'
        - container: API_PORT
          description:
            en_us: 'Container Variable: API_PORT'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-ls-adguard-home-sync
  description:
    en_us: 🛡️ Synchronize AdGuard Home config to replicas. This is the LinuxServer version.
  tagline:
    en_us: LS Adguard Home Sync
  developer: bakito
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/adguard-home.png
  thumbnail: ''
  title:
    en_us: LS Adguard Home Sync
  category: BigBearCasaOS
  port_map: '12073'

