name: big-bear-maybe-finance
services:
  big-bear-maybe-finance:
    container_name: big-bear-maybe-finance
    image: ghcr.io/maybe-finance/maybe:sha-347c0a790693031fdd3b32792b5b6792693d1805
    restart: unless-stopped
    privileged: false
    networks:
      - big_bear_maybe_finance_network
    volumes:
      - /DATA/.docker/AppData/$AppID/app-storage:/rails/storage
    ports:
      - '12078:3000'
    environment:
      SELF_HOSTED: 'true'
      RAILS_FORCE_SSL: 'false'
      RAILS_ASSUME_SSL: 'false'
      GOOD_JOB_EXECUTION_MODE: async
      SECRET_KEY_BASE: SECRET_KEY_BASE
      DB_HOST: big-bear-maybe-finance-postgres
      POSTGRES_DB: maybe_production
      POSTGRES_USER: maybe_user
      POSTGRES_PASSWORD: casaos
      REDIS_URL: redis://big-bear-maybe-finance-redis:6379/1
    depends_on:
      big-bear-maybe-finance-postgres:
        condition: service_healthy
      big-bear-maybe-finance-redis:
        condition: service_healthy
    x-casaos:
      envs:
        - container: SELF_HOSTED
          description:
            en_us: 'Container Variable: SELF_HOSTED'
        - container: RAILS_FORCE_SSL
          description:
            en_us: 'Container Variable: RAILS_FORCE_SSL'
        - container: RAILS_ASSUME_SSL
          description:
            en_us: 'Container Variable: RAILS_ASSUME_SSL'
        - container: GOOD_JOB_EXECUTION_MODE
          description:
            en_us: 'Container Variable: GOOD_JOB_EXECUTION_MODE'
        - container: SECRET_KEY_BASE
          description:
            en_us: 'Container Variable: SECRET_KEY_BASE'
        - container: DB_HOST
          description:
            en_us: 'Container Variable: DB_HOST'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: REDIS_URL
          description:
            en_us: 'Container Variable: REDIS_URL'
      volumes:
        - container: /rails/storage
          description:
            en_us: 'Container Path: /rails/storage'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
  big-bear-maybe-finance-postgres:
    container_name: big-bear-maybe-finance-postgres
    image: postgres:16
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: maybe_production
      POSTGRES_USER: maybe_user
      POSTGRES_PASSWORD: casaos
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U maybe_user -d maybe_production
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - big_bear_maybe_finance_network
    x-casaos:
      envs:
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
  big-bear-maybe-finance-redis:
    container_name: big-bear-maybe-finance-redis
    image: redis:7.4.6-alpine@sha256:7a7c6b5c49a6896d0a58ee0c6dc0dcabe14f30f0a2f7d2d1362d276fa2d43166
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/redis-data:/data
    healthcheck:
      test:
        - CMD
        - sh
        - '-c'
        - '[ "$(redis-cli ping)" = "PONG" ]'
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - big_bear_maybe_finance_network
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
networks:
  big_bear_maybe_finance_network:
    name: big_bear_maybe_finance_network
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-maybe-finance
  description:
    en_us: Maybe is a fully* open-source OS for your personal finances built by a small team alongside an incredible community Discord
  tagline:
    en_us: maybe-finance
  developer: Maybe Finance
  author: BigBearCommunity
  icon: https://raw.githubusercontent.com/maybe-finance/maybe/refs/heads/main/app/assets/images/logo-color.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        ### Additional Instructions:
        Generate the app secret key:

          1. Open a terminal and digit:

          ```bash
          head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n' && echo
          ```
          2. Copy the generated key and paste it in the `SECRET_KEY_BASE`.

          3. Save the changes and restart the application.

        For more information, refer to the [official documentation](https://maybe.co)
  title:
    en_us: Maybe Finance
  category: BigBearCasaOS
  port_map: '12078'

