name: big-bear-filebrowser
services:
  big-bear-filebrowser:
    container_name: big-bear-filebrowser
    image: filebrowser/filebrowser:v2.61.0-s6
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - /DATA/AppData:/srv/app-data
      - /DATA/Documents:/srv/documents
      - /media/Safe-Storage/Library/Downloads:/srv/downloads
      - /DATA/Gallery:/srv/gallery
      - /media/Safe-Storage/Library:/srv/media
      - /DATA/.docker/AppData/$AppID/data/db:/database
      - /DATA/.docker/AppData/$AppID/data/config:/config
    ports:
      - '12030:80'
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
      volumes:
        - container: /srv/app-data
          description:
            en_us: 'Container Path: /srv/app-data'
        - container: /srv/documents
          description:
            en_us: 'Container Path: /srv/documents'
        - container: /srv/downloads
          description:
            en_us: 'Container Path: /srv/downloads'
        - container: /srv/gallery
          description:
            en_us: 'Container Path: /srv/gallery'
        - container: /srv/media
          description:
            en_us: 'Container Path: /srv/media'
        - container: /database
          description:
            en_us: 'Container Path: /database'
        - container: /config
          description:
            en_us: 'Container Path: /config'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-filebrowser
  description:
    en_us: Reliable and Performant File Management Desktop Sync and File Sharing Tool.
  tagline:
    en_us: Access your homeserver files from your browser
  developer: filebrowser
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/file-browser.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-filebrowser-to-bigbearcasaos/1934#p-3590-documentation-4
  title:
    en_us: Filebrowser
  category: BigBearCasaOS
  port_map: '12030'

