name: big-bear-lyrionmusicserver
services:
  big-bear-lyrionmusicserver:
    container_name: big-bear-lyrionmusicserver
    image: lmscommunity/lyrionmusicserver:9.2.0
    restart: unless-stopped
    environment:
      - HTTP_PORT=9000
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
      - /media/Safe-Storage/Library/Music:/music
      - /DATA/.docker/AppData/$AppID/playlists:/playlist
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - '12074:9000'
      - 9090:9090/tcp
      - 3483:3483/tcp
      - 12075:3483/udp
    x-casaos:
      envs:
        - container: HTTP_PORT
          description:
            en_us: 'Container Variable: HTTP_PORT'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /music
          description:
            en_us: 'Container Path: /music'
        - container: /playlist
          description:
            en_us: 'Container Path: /playlist'
        - container: /etc/localtime
          description:
            en_us: 'Container Path: /etc/localtime'
        - container: /etc/timezone
          description:
            en_us: 'Container Path: /etc/timezone'
      ports:
        - container: '9000'
          description:
            en_us: 'Container Port: 9000'
        - container: '9090'
          description:
            en_us: 'Container Port: 9090'
        - container: '3483'
          description:
            en_us: 'Container Port: 3483'
        - container: '3483'
          description:
            en_us: 'Container Port: 3483'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-lyrionmusicserver
  description:
    en_us: Simplify the management of your server with Homarr - a sleek, modern dashboard that puts all of your apps and services at your fingertips. With Homarr, you can access and control everything in one convenient location. Homarr seamlessly integrates with the apps you've added, providing you with valuable information and giving you complete control. Installation is a breeze, and Homarr supports a wide range of deployment methods.
  tagline:
    en_us: Streaming audio server
  developer: LMS-Community
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/lyrionmusicserver/logo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-lyrion-music-server-to-bigbearcasaos/2606#p-4742-documentation-3
  title:
    en_us: LyriOn Music Server
  category: BigBearCasaOS
  port_map: '12074'

