name: big-bear-flcontainers-guacamole
services:
  app:
    image: flcontainers/guacamole:1.6.0
    container_name: big-bear-flcontainers-guacamole
    restart: always
    environment:
      tz: UTC
      EXTENSIONS: auth-totp,auth-ldap
    ports:
      - '12035:8080'
    x-casaos:
      envs:
        - container: tz
          description:
            en_us: 'Container Variable: tz'
        - container: EXTENSIONS
          description:
            en_us: 'Container Variable: EXTENSIONS'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: A Docker Container for Apache Guacamole, a client-less remote desktop gateway. It supports standard protocols like VNC, RDP, and SSH over HTML5.
  tagline:
    en_us: Fully packaged Multi-Arch Guacamole.
  developer: flcontainers
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/apache-guacamole.png
  thumbnail: ''
  title:
    en_us: FlContainers Guacamole
  category: BigBearCasaOS
  port_map: '12035'

