name: big-bear-jlesage-firefox
services:
  big-bear-jlesage-firefox:
    container_name: big-bear-jlesage-firefox
    image: jlesage/firefox:v26.02.3
    ports:
      - '5800:5800'
    environment:
      - VNC_PASSWORD=casaos
      - FF_OPEN_URL=https://community.bigbeartechworld.com/
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
    x-casaos:
      envs:
        - container: VNC_PASSWORD
          description:
            en_us: 'Container Variable: VNC_PASSWORD'
        - container: FF_OPEN_URL
          description:
            en_us: 'Container Variable: FF_OPEN_URL'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
      ports:
        - container: '5800'
          description:
            en_us: 'Container Port: 5800'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-jlesage-firefox
  description:
    en_us: The GUI of the application is accessed through a modern web browser (no installation or configuration needed on the client side) or via any VNC client.
  tagline:
    en_us: This project implements a Docker container for Firefox.
  developer: jlesage
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/firefox.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-jlesage-firefox-to-bigbearcasaos/2506#p-4575-documentation-3
  title:
    en_us: Jlesage Firefox
  category: BigBearCasaOS
  port_map: '5800'

