name: big-bear-pihole-unbound
services:
  app:
    container_name: big-bear-pihole-unbound
    image: bigbeartechworld/big-bear-pihole-unbound:2026.02.0
    restart: unless-stopped
    environment:
      TZ: America/Chicago
      FTLCONF_webserver_api_password: your_password
      FTLCONF_dns_upstreams: 127.0.0.1#5353
    volumes:
      - /DATA/.docker/AppData/$AppID/etc:/etc/pihole/
      - /DATA/.docker/AppData/$AppID/dnsmasq.d:/etc/dnsmasq.d/
    ports:
      - '12110:53'
      - 12111:53/udp
      - 12112:67/udp
      - '12113:80'
      - '12114:443'
    networks:
      - pihole-unbound-network
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: FTLCONF_webserver_api_password
          description:
            en_us: 'Container Variable: FTLCONF_webserver_api_password'
        - container: FTLCONF_dns_upstreams
          description:
            en_us: 'Container Variable: FTLCONF_dns_upstreams'
      volumes:
        - container: /etc/pihole/
          description:
            en_us: 'Container Path: /etc/pihole/'
        - container: /etc/dnsmasq.d/
          description:
            en_us: 'Container Path: /etc/dnsmasq.d/'
      ports:
        - container: '53'
          description:
            en_us: 'Container Port: 53'
        - container: '53'
          description:
            en_us: 'Container Port: 53'
        - container: '67'
          description:
            en_us: 'Container Port: 67'
        - container: '80'
          description:
            en_us: 'Container Port: 80'
        - container: '443'
          description:
            en_us: 'Container Port: 443'
networks:
  pihole-unbound-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: This is a custom pihole and unbound setup.
  tagline:
    en_us: Pi-hole and Unbound
  developer: bigbeartechworld
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/pi-hole-unbound.png
  thumbnail: ''
  title:
    en_us: Pi-hole and Unbound
  category: BigBearCasaOS
  port_map: '12110'

