name: big-bear-pihole-updatelists
services:
  big-bear-pihole-updatelists:
    container_name: big-bear-pihole-updatelists
    image: jacklul/pihole:2026.02.0
    restart: unless-stopped
    environment:
      TZ: UTC
      FTLCONF_webserver_api_password: your_password
      BLOCKLISTS_URL: https://v.firebog.net/hosts/lists.php?type=tick
      REGEX_BLACKLIST_URL: https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list
    volumes:
      - /DATA/.docker/AppData/$AppID/etc:/etc/pihole/
      - /DATA/.docker/AppData/$AppID/etc/pihole-updatelists:/etc/pihole-updatelists/
      - /DATA/.docker/AppData/$AppID/dnsmasq.d:/etc/dnsmasq.d/
    ports:
      - '12115:53'
      - 12116:53/udp
      - 12117:67/udp
      - '12118:80'
      - '12119:443'
    networks:
      - pihole-network
    cap_add:
      - NET_ADMIN
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: FTLCONF_webserver_api_password
          description:
            en_us: 'Container Variable: FTLCONF_webserver_api_password'
        - container: BLOCKLISTS_URL
          description:
            en_us: 'Container Variable: BLOCKLISTS_URL'
        - container: REGEX_BLACKLIST_URL
          description:
            en_us: 'Container Variable: REGEX_BLACKLIST_URL'
      volumes:
        - container: /etc/pihole/
          description:
            en_us: 'Container Path: /etc/pihole/'
        - container: /etc/pihole-updatelists/
          description:
            en_us: 'Container Path: /etc/pihole-updatelists/'
        - container: /etc/dnsmasq.d/
          description:
            en_us: 'Container Path: /etc/dnsmasq.d/'
      ports:
        - container: '53'
          description:
            en_us: 'Container Port: 53'
        - container: '53'
          description:
            en_us: 'Container Port: 53'
        - container: '67'
          description:
            en_us: 'Container Port: 67'
        - container: '80'
          description:
            en_us: 'Container Port: 80'
        - container: '443'
          description:
            en_us: 'Container Port: 443'
networks:
  pihole-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-pihole-updatelists
  description:
    en_us: The Pi-hole® is a DNS sinkhole that protects your devices from unwanted content without installing any client-side software. This is a fork of the Pi-hole® application that adds the ability to update the lists of blocked domains and regexes.
  tagline:
    en_us: A black hole for Internet advertisements. This is a fork of the Pi-hole® application that adds the ability to update the lists of blocked domains and regexes.
  developer: jacklul
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/pi-hole.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-pi-hole-updatelists-to-bigbearcasaos/3472?u=dragonfire1119
  title:
    en_us: Pi-hole® Updatelists
  category: BigBearCasaOS
  port_map: '12115'

