name: big-bear-ghost
services:
  app:
    container_name: big-bear-ghost
    image: ghost:6.20.0-alpine
    restart: on-failure
    networks:
      - ghost-network
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: casaos
      database__connection__database: ghost
      url: http://localhost:2368
    volumes:
      - /DATA/.docker/AppData/$AppID/content:/var/lib/ghost/content
    ports:
      - '2368:2368'
    depends_on:
      - db
    x-casaos:
      envs:
        - container: database__client
          description:
            en_us: 'Container Variable: database__client'
        - container: database__connection__host
          description:
            en_us: 'Container Variable: database__connection__host'
        - container: database__connection__user
          description:
            en_us: 'Container Variable: database__connection__user'
        - container: database__connection__password
          description:
            en_us: 'Container Variable: database__connection__password'
        - container: database__connection__database
          description:
            en_us: 'Container Variable: database__connection__database'
        - container: url
          description:
            en_us: 'Container Variable: url'
      volumes:
        - container: /var/lib/ghost/content
          description:
            en_us: 'Container Path: /var/lib/ghost/content'
      ports:
        - container: '2368'
          description:
            en_us: 'Container Port: 2368'
  db:
    container_name: big-bear-ghost-db
    image: mysql:8.0
    restart: on-failure
    volumes:
      - /DATA/.docker/AppData/$AppID/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: ghost
      MYSQL_DATABASE: ghost
      MYSQL_PASSWORD: casaos
      MYSQL_ROOT_PASSWORD: casaos
    networks:
      - ghost-network
    x-casaos:
      envs:
        - container: MYSQL_USER
          description:
            en_us: 'Container Variable: MYSQL_USER'
        - container: MYSQL_DATABASE
          description:
            en_us: 'Container Variable: MYSQL_DATABASE'
        - container: MYSQL_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_PASSWORD'
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_ROOT_PASSWORD'
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: 'Container Path: /var/lib/mysql'
networks:
  ghost-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Ghost is a free and open source blogging platform written in JavaScript and distributed under the MIT License, designed to simplify the process of online publishing for individual bloggers as well as online publications.
  tagline:
    en_us: Ghost is a free and open source blogging platform
  developer: ghost
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/ghost.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Update the url environment variable to reflect your CasaOS IP address.
  title:
    en_us: Ghost
  category: BigBearCasaOS
  port_map: '2368'

