name: big-bear-traccar
services:
  app:
    image: traccar/traccar:6.12-ubuntu
    container_name: traccar
    hostname: traccar
    restart: unless-stopped
    ports:
      - '12156:8082'
      - 5000-5150:5000-5150
      - 5000-5150:5000-5150/udp
    volumes:
      - /DATA/.docker/AppData/$AppID/logs:/opt/traccar/logs
      - /DATA/.docker/AppData/$AppID/traccar.xml:/opt/traccar/conf/traccar.xml
    x-casaos:
      volumes:
        - container: /opt/traccar/logs
          description:
            en_us: 'Container Path: /opt/traccar/logs'
        - container: /opt/traccar/conf/traccar.xml
          description:
            en_us: 'Container Path: /opt/traccar/conf/traccar.xml'
      ports:
        - container: '8082'
          description:
            en_us: 'Container Port: 8082'
        - container: 5000-5150
          description:
            en_us: 'Container Port: 5000-5150'
        - container: 5000-5150
          description:
            en_us: 'Container Port: 5000-5150'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Traccar GPS Tracking System in Docker image.
  tagline:
    en_us: Traccar
  developer: traccar
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/traccar.png
  thumbnail: ''
  title:
    en_us: Traccar
  category: BigBearCasaOS
  port_map: '12156'

