name: big-bear-uisp
services:
  big-bear-uisp:
    container_name: big-bear-uisp
    image: nico640/docker-unms:2.4.155.1
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
    ports:
      - '12158:80'
      - '12159:443'
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
        - container: '443'
          description:
            en_us: 'Container Port: 443'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-uisp
  description:
    en_us: All-in-one docker image for Ubiquiti UISP (formerly UNMS). Supports x86_64 and ARM (Raspberry Pi).
  tagline:
    en_us: UISP
  developer: nico640
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-icons/Apps/uisp/logo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Before you install read this: https://community.bigbeartechworld.com/t/added-uisp-to-bigbearcasaos/2582#p-4674-documentation-3
  title:
    en_us: UISP
  category: BigBearCasaOS
  port_map: '12158'

