name: big-bear-pihole
services:
  app:
    container_name: big-bear-pihole
    image: pihole/pihole:2026.02.0
    restart: unless-stopped
    environment:
      TZ: UTC
      FTLCONF_webserver_api_password: your_password
    volumes:
      - /DATA/.docker/AppData/$AppID/etc:/etc/pihole/
      - /DATA/.docker/AppData/$AppID/dnsmasq.d:/etc/dnsmasq.d/
    ports:
      - '12105:53'
      - 12106:53/udp
      - 12107:67/udp
      - '12108:80'
      - '12109:443'
    networks:
      - pihole-network
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: FTLCONF_webserver_api_password
          description:
            en_us: 'Container Variable: FTLCONF_webserver_api_password'
      volumes:
        - container: /etc/pihole/
          description:
            en_us: 'Container Path: /etc/pihole/'
        - container: /etc/dnsmasq.d/
          description:
            en_us: 'Container Path: /etc/dnsmasq.d/'
      ports:
        - container: '53'
          description:
            en_us: 'Container Port: 53'
        - container: '53'
          description:
            en_us: 'Container Port: 53'
        - container: '67'
          description:
            en_us: 'Container Port: 67'
        - container: '80'
          description:
            en_us: 'Container Port: 80'
        - container: '443'
          description:
            en_us: 'Container Port: 443'
networks:
  pihole-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: The Pi-hole® is a DNS sinkhole that protects your devices from unwanted content without installing any client-side software.
  tagline:
    en_us: A black hole for Internet advertisements
  developer: pi-hole.net
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/pi-hole.png
  thumbnail: ''
  title:
    en_us: Pi-hole
  category: BigBearCasaOS
  port_map: '12105'

