name: big-bear-komf
services:
  big-bear-komf:
    container_name: big-bear-komf
    image: sndxr/komf:1.7.1
    restart: unless-stopped
    environment:
      - KOMF_KOMGA_BASE_URI=http://komga:25600
      - KOMF_KOMGA_USER=admin@example.org
      - KOMF_KOMGA_PASSWORD=admin
      - KOMF_KAVITA_BASE_URI=http://kavita:5000
      - KOMF_KAVITA_API_KEY=cd1edcc1-6010-41a8-a82b-73f501dc2760
      - KOMF_LOG_LEVEL=INFO
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
    user: '1000:1000'
    ports:
      - '12061:8085'
    networks:
      - big_bear_komf_network
    x-casaos:
      envs:
        - container: KOMF_KOMGA_BASE_URI
          description:
            en_us: 'Container Variable: KOMF_KOMGA_BASE_URI'
        - container: KOMF_KOMGA_USER
          description:
            en_us: 'Container Variable: KOMF_KOMGA_USER'
        - container: KOMF_KOMGA_PASSWORD
          description:
            en_us: 'Container Variable: KOMF_KOMGA_PASSWORD'
        - container: KOMF_KAVITA_BASE_URI
          description:
            en_us: 'Container Variable: KOMF_KAVITA_BASE_URI'
        - container: KOMF_KAVITA_API_KEY
          description:
            en_us: 'Container Variable: KOMF_KAVITA_API_KEY'
        - container: KOMF_LOG_LEVEL
          description:
            en_us: 'Container Variable: KOMF_LOG_LEVEL'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
      ports:
        - container: '8085'
          description:
            en_us: 'Container Port: 8085'
networks:
  big_bear_komf_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-komf
  description:
    en_us: Komga and Kavita Metadata Fetcher is a tool that fetches metadata and thumbnails for your digital comic book library. It can automatically pick up added series and update their metadata and thumbnail. You can also manually search and identify series, or match the entire library or a series. Additionally, you can install the Komf userscript to add Komf integration directly to Komga and Kavita UI, allowing you to launch manual or automatic metadata identification.
  tagline:
    en_us: Komga and Kavita Metadata Fetcher
  developer: sndxr
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/komga.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-komf-to-bigbearcasaos/1951#p-3619-documentation-4
  title:
    en_us: Komf
  category: BigBearCasaOS
  port_map: '12061'

