name: big-bear-it-tools
services:
  app:
    container_name: big-bear-it-tools
    image: corentinth/it-tools:2023.11.2-7d94e11
    restart: unless-stopped
    ports:
      - '12054:80'
    x-casaos:
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Collection of handy online tools for developers, with great UX as a web app.
  tagline:
    en_us: IT Tools
  developer: corentinth
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/it-tools.png
  thumbnail: ''
  title:
    en_us: IT Tools
  category: BigBearCasaOS
  port_map: '12054'

