name: big-bear-ncdu
services:
  big-bear-ncdu:
    container_name: big-bear-ncdu
    image: bigbeartechworld/big-bear-ncdu:0.0.4
    restart: unless-stopped
    privileged: true
    volumes:
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      - /:/casaos
    ports:
      - '12084:7681'
    environment:
      - NCDU_PATH=/
    x-casaos:
      envs:
        - container: NCDU_PATH
          description:
            en_us: 'Container Variable: NCDU_PATH'
      volumes:
        - container: /proc
          description:
            en_us: 'Container Path: /proc'
        - container: /sys
          description:
            en_us: 'Container Path: /sys'
        - container: /dev
          description:
            en_us: 'Container Path: /dev'
        - container: /etc/localtime
          description:
            en_us: 'Container Path: /etc/localtime'
        - container: /casaos
          description:
            en_us: 'Container Path: /casaos'
      ports:
        - container: '7681'
          description:
            en_us: 'Container Port: 7681'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-ncdu
  description:
    en_us: Ncdu is a disk usage analyzer with an ncurses interface. It is designed to find space hogs on a remote server where you don’t have an entire graphical setup available, but it is a useful tool even on regular desktop systems. Ncdu aims to be fast, simple and easy to use, and should be able to run in any minimal POSIX-like environment with ncurses installed. Software made by Yorhel at https://dev.yorhel.nl/ncdu
  tagline:
    en_us: Ncdu is a disk usage analyzer with an ncurses interface.
  developer: bigbeartechworld
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/ncdu/logo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-ncdu-to-bigbearcasaos/1240?u=dragonfire1119
  title:
    en_us: Ncdu
  category: BigBearCasaOS
  port_map: '12084'

