name: big-bear-joplin
services:
  big-bear-joplin:
    container_name: big-bear-joplin
    image: joplin/server:3.5.2
    restart: unless-stopped
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=http://localhost:22300
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=27a1d42a-a15d-43dd-903c-2a73538647fe
      - POSTGRES_USER=bigbear
      - POSTGRES_DATABASE=joplin
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=big-bear-joplin-db
      - MAX_TIME_DRIFT=0
    ports:
      - '22300:22300'
    networks:
      - big_bear_joplin_network
    depends_on:
      - big-bear-joplin-db
    x-casaos:
      envs:
        - container: APP_PORT
          description:
            en_us: 'Container Variable: APP_PORT'
        - container: APP_BASE_URL
          description:
            en_us: 'Container Variable: APP_BASE_URL'
        - container: DB_CLIENT
          description:
            en_us: 'Container Variable: DB_CLIENT'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_DATABASE
          description:
            en_us: 'Container Variable: POSTGRES_DATABASE'
        - container: POSTGRES_PORT
          description:
            en_us: 'Container Variable: POSTGRES_PORT'
        - container: POSTGRES_HOST
          description:
            en_us: 'Container Variable: POSTGRES_HOST'
        - container: MAX_TIME_DRIFT
          description:
            en_us: 'Container Variable: MAX_TIME_DRIFT'
      ports:
        - container: '22300'
          description:
            en_us: 'Container Port: 22300'
  big-bear-joplin-db:
    container_name: big-bear-joplin-db
    image: postgres:14.2
    volumes:
      - /DATA/.docker/AppData/$AppID/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=27a1d42a-a15d-43dd-903c-2a73538647fe
      - POSTGRES_USER=bigbear
      - POSTGRES_DB=joplin
    networks:
      - big_bear_joplin_network
    x-casaos:
      envs:
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
networks:
  big_bear_joplin_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-joplin
  description:
    en_us: Note taking and to-do application with synchronisation
  tagline:
    en_us: joplin
  developer: joplin
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/joplin.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-joplin-server-to-bigbearcasaos/800?u=dragonfire1119
  title:
    en_us: joplin
  category: BigBearCasaOS
  port_map: '22300'

