name: big-bear-actual-server
services:
  app:
    image: actualbudget/actual-server:26.3.0
    container_name: actual-server
    volumes:
      - /DATA/.docker/AppData/$AppID:/data
    ports:
      - '5006:5006'
    restart: unless-stopped
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
      ports:
        - container: '5006'
          description:
            en_us: 'Container Port: 5006'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Actual Budget is a super fast and privacy-focused app for managing your finances. At its heart is the well proven and much loved Envelope Budgeting methodology. You own your data and can do whatever you want with it. Featuring multi-device sync, optional end-to-end encryption and so much more.
  tagline:
    en_us: Local-first OpenSource Budget tool
  developer: actualbudget
  author: BigBearCommunity
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/actual-budget.png
  thumbnail: ''
  title:
    en_us: Actual Budget
  category: BigBearCasaOS
  port_map: '5006'

