name: big-bear-firefox
services:
  firefox:
    container_name: big-bear-firefox
    image: linuxserver/firefox:1147.0.4
    ports:
      - '12033:3000'
      - '12034:3001'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - FIREFOX_CLI=https://community.bigbeartechworld.com/
    shm_size: 1gb
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: FIREFOX_CLI
          description:
            en_us: 'Container Variable: FIREFOX_CLI'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
        - container: '3001'
          description:
            en_us: 'Container Port: 3001'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: firefox
  description:
    en_us: This Image contains a browser-accessible version of Firefox.
  tagline:
    en_us: Firefox
  developer: linuxserver
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/firefox.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Access the browser at http://your-server:3000 or https://your-server:3001
  title:
    en_us: Firefox
  category: BigBearCasaOS
  port_map: '12033'

