name: big-bear-zotero
services:
  big-bear-zotero:
    container_name: big-bear-zotero
    image: linuxserver/zotero:7.0.20240809
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - '12185:3000'
      - '12186:3001'
    security_opt:
      - seccomp:unconfined
    shm_size: 1gb
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
        - container: '3001'
          description:
            en_us: 'Container Port: 3001'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-zotero
  description:
    en_us: Zotero is a free, easy-to-use tool to help you collect, organize, annotate, cite, and share research.
  tagline:
    en_us: Zotero
  developer: linuxserver
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/zotero/logo.png
  thumbnail: ''
  title:
    en_us: Zotero
  category: BigBearCasaOS
  port_map: '12185'

