name: big-bear-psitransfer
services:
  app:
    image: psitrax/psitransfer:v2.4.1
    container_name: big-bear-psitransfer
    user: '1000:1000'
    environment:
      PSITRANSFER_ADMIN_PASS: ''
      PSITRANSFER_UPLOAD_PASS: ''
      PSITRANSFER_REQUIRE_BUCKET_PASSWORD: 'false'
      PSITRANSFER_MAX_FILE_SIZE: ''
      PSITRANSFER_MAX_BUCKET_SIZE: ''
      PSITRANSFER_DEFAULT_RETENTION: '604800'
      PSITRANSFER_MAX_AGE: '6480000'
    ports:
      - '12132:3000'
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/data
    restart: unless-stopped
    x-casaos:
      envs:
        - container: PSITRANSFER_ADMIN_PASS
          description:
            en_us: 'Container Variable: PSITRANSFER_ADMIN_PASS'
        - container: PSITRANSFER_UPLOAD_PASS
          description:
            en_us: 'Container Variable: PSITRANSFER_UPLOAD_PASS'
        - container: PSITRANSFER_REQUIRE_BUCKET_PASSWORD
          description:
            en_us: 'Container Variable: PSITRANSFER_REQUIRE_BUCKET_PASSWORD'
        - container: PSITRANSFER_MAX_FILE_SIZE
          description:
            en_us: 'Container Variable: PSITRANSFER_MAX_FILE_SIZE'
        - container: PSITRANSFER_MAX_BUCKET_SIZE
          description:
            en_us: 'Container Variable: PSITRANSFER_MAX_BUCKET_SIZE'
        - container: PSITRANSFER_DEFAULT_RETENTION
          description:
            en_us: 'Container Variable: PSITRANSFER_DEFAULT_RETENTION'
        - container: PSITRANSFER_MAX_AGE
          description:
            en_us: 'Container Variable: PSITRANSFER_MAX_AGE'
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: PsiTransfer is a simple open source self-hosted file sharing solution. It's an alternative to paid services like Dropbox and WeTransfer. Features include no accounts or logins required, mobile friendly responsive interface, support for many and very big files with resumable uploads and downloads, expiring upload buckets, one-time downloads, password protected downloads, and admin dashboard.
  tagline:
    en_us: Simple self-hosted file sharing solution
  developer: psi-4ward
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/psitransfer.png
  thumbnail: https://cdn.jsdelivr.net/gh/psi-4ward/psitransfer@master/docs/psitransfer.gif
  tips:
    before_install:
      en_us: 'Read more here: https://community.bigbeartechworld.com/t/added-psitransfer-to-bigbearuniversal-apps/5142#p-7883-documentation-5'
  title:
    en_us: PsiTransfer
  category: BigBearCasaOS
  port_map: '12132'

