name: big-bear-beszel
services:
  big-bear-beszel:
    container_name: big-bear-beszel
    image: henrygd/beszel:0.18.4
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/beszel_data
    ports:
      - '12007:8090'
    x-casaos:
      volumes:
        - container: /beszel_data
          description:
            en_us: 'Container Path: /beszel_data'
      ports:
        - container: '8090'
          description:
            en_us: 'Container Port: 8090'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-beszel
  description:
    en_us: A lightweight server resource monitoring hub with historical data, docker stats, and alerts.
  tagline:
    en_us: Server Monitoring Hub
  developer: henrygd
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/beszel/logo.jpg
  thumbnail: ''
  title:
    en_us: Beszel
  category: BigBearCasaOS
  port_map: '12007'

