name: big-bear-plant-it
services:
  big-bear-plant-it:
    container_name: big-bear-plant-it
    image: msdeluise/plant-it-server:0.10.0
    restart: unless-stopped
    environment:
      - MYSQL_HOST=big-bear-plant-it-db
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PSW=9c75c563-b549-40e6-a0d2-360cf9a962ea
      - MYSQL_DATABASE=plantit
      - MYSQL_ROOT_PASSWORD=9c75c563-b549-40e6-a0d2-360cf9a962ea
      - JWT_SECRET=putTheSecretHere
      - JWT_EXP=1
      - USERS_LIMIT=-1
      - UPLOAD_DIR=/upload-dir
      - API_PORT=8080
      - TREFLE_KEY=
      - LOG_LEVEL=DEBUG
      - ALLOWED_ORIGINS=*
      - CACHE_TTL=86400
      - CACHE_HOST=big-bear-plant-it-cache
      - CACHE_PORT=6379
      - SSL_ENABLED=false
      - CERTIFICATE_PATH=/certificates/
    volumes:
      - /DATA/.docker/AppData/$AppID/upload-dir:/upload-dir
      - /DATA/.docker/AppData/$AppID/certificates:/certificates
    ports:
      - '12124:3000'
      - '12125:8080'
    networks:
      - big_bear_plant_it_network
    x-casaos:
      envs:
        - container: MYSQL_HOST
          description:
            en_us: 'Container Variable: MYSQL_HOST'
        - container: MYSQL_PORT
          description:
            en_us: 'Container Variable: MYSQL_PORT'
        - container: MYSQL_USERNAME
          description:
            en_us: 'Container Variable: MYSQL_USERNAME'
        - container: MYSQL_PSW
          description:
            en_us: 'Container Variable: MYSQL_PSW'
        - container: MYSQL_DATABASE
          description:
            en_us: 'Container Variable: MYSQL_DATABASE'
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_ROOT_PASSWORD'
        - container: JWT_SECRET
          description:
            en_us: 'Container Variable: JWT_SECRET'
        - container: JWT_EXP
          description:
            en_us: 'Container Variable: JWT_EXP'
        - container: USERS_LIMIT
          description:
            en_us: 'Container Variable: USERS_LIMIT'
        - container: UPLOAD_DIR
          description:
            en_us: 'Container Variable: UPLOAD_DIR'
        - container: API_PORT
          description:
            en_us: 'Container Variable: API_PORT'
        - container: TREFLE_KEY
          description:
            en_us: 'Container Variable: TREFLE_KEY'
        - container: LOG_LEVEL
          description:
            en_us: 'Container Variable: LOG_LEVEL'
        - container: ALLOWED_ORIGINS
          description:
            en_us: 'Container Variable: ALLOWED_ORIGINS'
        - container: CACHE_TTL
          description:
            en_us: 'Container Variable: CACHE_TTL'
        - container: CACHE_HOST
          description:
            en_us: 'Container Variable: CACHE_HOST'
        - container: CACHE_PORT
          description:
            en_us: 'Container Variable: CACHE_PORT'
        - container: SSL_ENABLED
          description:
            en_us: 'Container Variable: SSL_ENABLED'
        - container: CERTIFICATE_PATH
          description:
            en_us: 'Container Variable: CERTIFICATE_PATH'
      volumes:
        - container: /upload-dir
          description:
            en_us: 'Container Path: /upload-dir'
        - container: /certificates
          description:
            en_us: 'Container Path: /certificates'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
  big-bear-plant-it-db:
    container_name: big-bear-plant-it-db
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=plantit
      - MYSQL_ROOT_PASSWORD=9c75c563-b549-40e6-a0d2-360cf9a962ea
    ports:
      - '12126:3306'
    volumes:
      - /DATA/.docker/AppData/$AppID/mysql:/var/lib/mysql
    networks:
      - big_bear_plant_it_network
    x-casaos:
      envs:
        - container: MYSQL_DATABASE
          description:
            en_us: 'Container Variable: MYSQL_DATABASE'
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_ROOT_PASSWORD'
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: 'Container Path: /var/lib/mysql'
      ports:
        - container: '3306'
          description:
            en_us: 'Container Port: 3306'
  big-bear-plant-it-cache:
    container_name: big-bear-plant-it-cache
    image: redis:7.2.11@sha256:9c44a721d444690605ffa32d6b6e1ac565060676386f88bbbb376f56cef2f724
    restart: always
    networks:
      - big_bear_plant_it_network
networks:
  big_bear_plant_it_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-plant-it
  description:
    en_us: Plant-it is a self-hosted gardening companion app. Useful for keeping track of plant care, receiving notifications about when to water plants, uploading plant images, and more.
  tagline:
    en_us: Self-hosted, open source gardening companion app
  developer: msdeluise
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/plant-it/logo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Before installing read this: https://community.bigbeartechworld.com/t/added-plant-it-to-bigbearcasaos/1297#documentation-3
  title:
    en_us: Plant-it
  category: BigBearCasaOS
  port_map: '12124'

