name: big-bear-home-assistant
services:
  app:
    container_name: big-bear-home-assistant
    image: ghcr.io/home-assistant/home-assistant:2026.2.3
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    network_mode: host
    x-casaos:
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /etc/localtime
          description:
            en_us: 'Container Path: /etc/localtime'
        - container: /run/dbus
          description:
            en_us: 'Container Path: /run/dbus'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Open source home automation that puts local control and privacy first. Powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect to run on a Raspberry Pi or a local server.
  tagline:
    en_us: Home Automation
  developer: home-assistant
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/home-assistant.png
  thumbnail: ''
  title:
    en_us: Home Assistant
  category: BigBearCasaOS
  port_map: '8123'

