name: big-bear-audiobookshelf
services:
  big-bear-audiobookshelf:
    container_name: big-bear-audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:2.32.1
    restart: unless-stopped
    volumes:
      - /media/Safe-Storage/Library/Audiobooks:/audiobooks
      - /media/Safe-Storage/Library:/podcasts
      - /DATA/.docker/AppData/$AppID/data/config:/config
      - /DATA/.docker/AppData/$AppID/data/metadata:/metadata
    ports:
      - '12005:80'
    x-casaos:
      volumes:
        - container: /audiobooks
          description:
            en_us: 'Container Path: /audiobooks'
        - container: /podcasts
          description:
            en_us: 'Container Path: /podcasts'
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /metadata
          description:
            en_us: 'Container Path: /metadata'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-audiobookshelf
  description:
    en_us: Audiobookshelf is a self-hosted audiobook server for managing and playing your audiobooks. Audiobookshelf has a clean, accessible design that's loaded with features but not overly complicated.
  tagline:
    en_us: Audiobookshelf is a self-hosted audiobook and podcast server.
  developer: ajnart
  author: advplyr
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/audiobookshelf.png
  thumbnail: ''
  title:
    en_us: Audiobookshelf
  category: BigBearCasaOS
  port_map: '12005'

