name: big-bear-gluetun
services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.1
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - '12039:8888'
      - 8388:8388/tcp
      - 12040:8388/udp
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - TZ=
      - UPDATER_PERIOD=
    x-casaos:
      envs:
        - container: VPN_SERVICE_PROVIDER
          description:
            en_us: 'Container Variable: VPN_SERVICE_PROVIDER'
        - container: VPN_TYPE
          description:
            en_us: 'Container Variable: VPN_TYPE'
        - container: OPENVPN_USER
          description:
            en_us: 'Container Variable: OPENVPN_USER'
        - container: OPENVPN_PASSWORD
          description:
            en_us: 'Container Variable: OPENVPN_PASSWORD'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: UPDATER_PERIOD
          description:
            en_us: 'Container Variable: UPDATER_PERIOD'
      volumes:
        - container: /gluetun
          description:
            en_us: 'Container Path: /gluetun'
      ports:
        - container: '8888'
          description:
            en_us: 'Container Port: 8888'
        - container: '8388'
          description:
            en_us: 'Container Port: 8388'
        - container: '8388'
          description:
            en_us: 'Container Port: 8388'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: gluetun
  description:
    en_us: Lightweight swiss-knife-like VPN client to multiple VPN service providers
  tagline:
    en_us: Gluetun
  developer: portainer
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/gluetun.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        You will need to configure the providers in the environment variables. See: [BigBearCasaOS Gluetun Docs](https://community.bigbeartechworld.com/t/added-gluetun-to-big-bear-casaos/175)
  title:
    en_us: Gluetun
  category: BigBearCasaOS
  port_map: '12039'

