name: big-bear-upsnap
services:
  big-bear-upsnap:
    container_name: big-bear-upsnap
    image: ghcr.io/seriousm4x/upsnap:5.2.8
    restart: unless-stopped
    network_mode: host
    volumes:
      - /DATA/.docker/AppData/$AppID/pb/data:/app/pb_data
    x-casaos:
      volumes:
        - container: /app/pb_data
          description:
            en_us: 'Container Path: /app/pb_data'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-upsnap
  description:
    en_us: A simple wake on lan web app written with SvelteKit, Go and PocketBase.
  tagline:
    en_us: Upsnap
  developer: seriousm4x
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/upsnap.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-upsnap-to-bigbearcasaos/2279?u=dragonfire1119
  title:
    en_us: Upsnap
  category: BigBearCasaOS
  port_map: '8090'

