name: big-bear-linkwarden
services:
  linkwarden:
    container_name: big-bear-linkwarden
    image: ghcr.io/linkwarden/linkwarden:v2.13.5
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data/linkwarden:/data/data
    environment:
      - DATABASE_URL=postgresql://casaos:casaospassword@big-bear-linkwarden-db:5432/big-bear-linkwarden
      - NEXTAUTH_SECRET=7e2d8797-dc20-422a-9a68-44b958bd33c0
      - NEXTAUTH_URL=http://localhost/api/v1/auth
      - NEXT_PUBLIC_DISABLE_REGISTRATION=
    ports:
      - '12072:3000'
    networks:
      - linkwarden_network
    x-casaos:
      envs:
        - container: DATABASE_URL
          description:
            en_us: 'Container Variable: DATABASE_URL'
        - container: NEXTAUTH_SECRET
          description:
            en_us: 'Container Variable: NEXTAUTH_SECRET'
        - container: NEXTAUTH_URL
          description:
            en_us: 'Container Variable: NEXTAUTH_URL'
        - container: NEXT_PUBLIC_DISABLE_REGISTRATION
          description:
            en_us: 'Container Variable: NEXT_PUBLIC_DISABLE_REGISTRATION'
      volumes:
        - container: /data/data
          description:
            en_us: 'Container Path: /data/data'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
  linkwarden-db:
    container_name: big-bear-linkwarden-db
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=casaos
      - POSTGRES_PASSWORD=casaospassword
      - POSTGRES_DB=big-bear-linkwarden
    volumes:
      - /DATA/.docker/AppData/$AppID/data/postgres:/var/lib/postgresql/data
    networks:
      - linkwarden_network
    x-casaos:
      envs:
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
networks:
  linkwarden_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: linkwarden
  description:
    en_us: ⚡️⚡️⚡️Self-hosted collaborative bookmark manager to collect, organize, and preserve webpages and articles.
  tagline:
    en_us: Linkwarden
  developer: linkwarden
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/linkwarden.png
  thumbnail: ''
  title:
    en_us: Linkwarden
  category: BigBearCasaOS
  port_map: '12072'

