name: big-bear-convertx
services:
  big-bear-convertx:
    container_name: big-bear-convertx
    image: ghcr.io/c4illin/convertx:v0.17.0
    restart: unless-stopped
    ports:
      - '12018:3000'
    environment:
      - JWT_SECRET=c8330437-e6ae-4cf0-9837-4d1326457e32
      - HTTP_ALLOWED=true
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/app/data
    x-casaos:
      envs:
        - container: JWT_SECRET
          description:
            en_us: 'Container Variable: JWT_SECRET'
        - container: HTTP_ALLOWED
          description:
            en_us: 'Container Variable: HTTP_ALLOWED'
      volumes:
        - container: /app/data
          description:
            en_us: 'Container Path: /app/data'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-convertx
  description:
    en_us: A self-hosted online file converter. Supports over a thousand different formats. Written with TypeScript, Bun and Elysia.
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/convertx/screenshots/screenshot-1.png
  tagline:
    en_us: 💾 Self-hosted online file converter. Supports 1000+ formats ⚙️
  developer: C4illin
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/convertx/logo.png
  thumbnail: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/convertx/thumbnail.png
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/add-convertx-to-bigbearcasaos/3232#p-5599-documentation-5
  title:
    en_us: ConvertX
  category: BigBearCasaOS
  port_map: '12018'

