name: big-bear-readeck
services:
  big-bear-readeck:
    container_name: big-bear-readeck
    image: codeberg.org/readeck/readeck:0.21.6
    restart: unless-stopped
    environment:
      - READECK_LOG_LEVEL=info
      - READECK_SERVER_HOST=0.0.0.0
      - READECK_SERVER_PORT=8000
      - READECK_LOG_FORMAT=text
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/readeck
    ports:
      - '12138:8000'
    healthcheck:
      test:
        - CMD
        - /bin/readeck
        - healthcheck
        - '-config'
        - config.toml
      interval: 30s
      timeout: 2s
      retries: 3
    x-casaos:
      envs:
        - container: READECK_LOG_LEVEL
          description:
            en_us: 'Container Variable: READECK_LOG_LEVEL'
        - container: READECK_SERVER_HOST
          description:
            en_us: 'Container Variable: READECK_SERVER_HOST'
        - container: READECK_SERVER_PORT
          description:
            en_us: 'Container Variable: READECK_SERVER_PORT'
        - container: READECK_LOG_FORMAT
          description:
            en_us: 'Container Variable: READECK_LOG_FORMAT'
      volumes:
        - container: /readeck
          description:
            en_us: 'Container Path: /readeck'
      ports:
        - container: '8000'
          description:
            en_us: 'Container Port: 8000'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-readeck
  description:
    en_us: Readeck is a simple web application that lets you save the precious readable content of web pages you like and want to keep forever. It is a self-hosted alternative to Instapaper and Wallabag with a modern interface and powerful features for managing your bookmarks and reading list.
  tagline:
    en_us: Self-hosted bookmark manager and read-it-later app
  developer: readeck
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/readeck.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-readeck-to-bigbearcasaos/5079#p-7723-documentation-3
  title:
    en_us: Readeck
  category: BigBearCasaOS
  port_map: '12138'

