name: big-bear-jellystat
services:
  big-bear-jellystat:
    container_name: big-bear-jellystat
    image: cyfershepard/jellystat:1.1.8
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8a23ad09-61cf-4178-a783-6d4586496e3a
      - POSTGRES_IP=big-bear-jellystat-db
      - POSTGRES_PORT=5432
      - JWT_SECRET="my-secret-jwt-key"
    volumes:
      - /DATA/.docker/AppData/$AppID/backup-data:/app/backend/backup-data
    ports:
      - '12055:3000'
    networks:
      - big-bear-jellystat-network
    x-casaos:
      envs:
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_IP
          description:
            en_us: 'Container Variable: POSTGRES_IP'
        - container: POSTGRES_PORT
          description:
            en_us: 'Container Variable: POSTGRES_PORT'
        - container: JWT_SECRET
          description:
            en_us: 'Container Variable: JWT_SECRET'
      volumes:
        - container: /app/backend/backup-data
          description:
            en_us: 'Container Path: /app/backend/backup-data'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
  big-bear-jellystat-db:
    container_name: big-bear-jellystat-db
    image: postgres:15.2
    environment:
      POSTGRES_DB: jfstat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8a23ad09-61cf-4178-a783-6d4586496e3a
    volumes:
      - /DATA/.docker/AppData/$AppID/postgres-data:/var/lib/postgresql/data
    networks:
      - big-bear-jellystat-network
    x-casaos:
      envs:
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
networks:
  big-bear-jellystat-network:
    name: big-bear-jellystat-network
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-jellystat
  description:
    en_us: Jellystat is a free and open source Statistics App for Jellyfin! (This project is still in development - expect some weirdness)
  tagline:
    en_us: Jellystat
  developer: cyfershepard
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellystat.png
  thumbnail: ''
  title:
    en_us: Jellystat
  category: BigBearCasaOS
  port_map: '12055'

