name: big-bear-baserow
services:
  app:
    container_name: baserow
    image: baserow/baserow:2.1.3
    environment:
      BASEROW_PUBLIC_URL: http://[YOUR_CASAOS_IP]:7350
    ports:
      - '7350:80'
      - '7351:443'
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/baserow/data
    x-casaos:
      envs:
        - container: BASEROW_PUBLIC_URL
          description:
            en_us: 'Container Variable: BASEROW_PUBLIC_URL'
      volumes:
        - container: /baserow/data
          description:
            en_us: 'Container Path: /baserow/data'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
        - container: '443'
          description:
            en_us: 'Container Port: 443'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Create your own online database without technical experience. Our user-friendly no-code tool gives you the powers of a developer without leaving your browser.
  tagline:
    en_us: Baserow
  developer: baserow
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/baserow.png
  thumbnail: https://github.com/bram2w/baserow/raw/master/docs/assets/screenshot.png
  title:
    en_us: Baserow
  category: BigBearCasaOS
  port_map: '7350'

