name: big-bear-ghostfolio
services:
  big-bear-ghostfolio:
    container_name: big-bear-ghostfolio
    image: ghostfolio/ghostfolio:2.246.0
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: '3333'
      ACCESS_TOKEN_SALT: 5a7f9e0d-0e64-4c19-8279-bbe8b4c590f4
      DATABASE_URL: postgresql://ghostfolio:casaospassword@big-bear-ghostfolio-db:5432/ghostfolio?sslmode=prefer
      JWT_SECRET_KEY: 534e820d-da30-4dd3-baf9-0511847c478a
      POSTGRES_DB: ghostfolio
      POSTGRES_USER: ghostfolio
      POSTGRES_PASSWORD: casaospassword
      REDIS_HOST: big-bear-ghostfolio-redis
      REDIS_PASSWORD: casaosredispassword
      REDIS_PORT: '6379'
    ports:
      - '12038:3333'
    depends_on:
      big-bear-ghostfolio-db:
        condition: service_healthy
      big-bear-ghostfolio-redis:
        condition: service_healthy
    networks:
      - big_bear_ghostfolio_network
    x-casaos:
      envs:
        - container: NODE_ENV
          description:
            en_us: 'Container Variable: NODE_ENV'
        - container: HOST
          description:
            en_us: 'Container Variable: HOST'
        - container: PORT
          description:
            en_us: 'Container Variable: PORT'
        - container: ACCESS_TOKEN_SALT
          description:
            en_us: 'Container Variable: ACCESS_TOKEN_SALT'
        - container: DATABASE_URL
          description:
            en_us: 'Container Variable: DATABASE_URL'
        - container: JWT_SECRET_KEY
          description:
            en_us: 'Container Variable: JWT_SECRET_KEY'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: REDIS_HOST
          description:
            en_us: 'Container Variable: REDIS_HOST'
        - container: REDIS_PASSWORD
          description:
            en_us: 'Container Variable: REDIS_PASSWORD'
        - container: REDIS_PORT
          description:
            en_us: 'Container Variable: REDIS_PORT'
      ports:
        - container: '3333'
          description:
            en_us: 'Container Port: 3333'
  big-bear-ghostfolio-db:
    container_name: big-bear-ghostfolio-db
    image: postgres:15.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ghostfolio
      POSTGRES_USER: ghostfolio
      POSTGRES_PASSWORD: casaospassword
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d ghostfolio -U ghostfolio
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /DATA/.docker/AppData/$AppID/data/db:/var/lib/postgresql/data
    networks:
      - big_bear_ghostfolio_network
    x-casaos:
      envs:
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: PGDATA
          description:
            en_us: 'Container Variable: PGDATA'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
  big-bear-ghostfolio-redis:
    container_name: big-bear-ghostfolio-redis
    image: redis:7.4.6-alpine@sha256:7a7c6b5c49a6896d0a58ee0c6dc0dcabe14f30f0a2f7d2d1362d276fa2d43166
    restart: unless-stopped
    command: |
      --requirepass casaosredispassword
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - /DATA/.docker/AppData/$AppID/data/redis:/data
    networks:
      - big_bear_ghostfolio_network
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
networks:
  big_bear_ghostfolio_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-ghostfolio
  description:
    en_us: Open Source Wealth Management Software. Angular + NestJS + Prisma + Nx + TypeScript 🤍
  tagline:
    en_us: Ghostfolio
  developer: ghostfolio
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/ghostfolio.png
  thumbnail: ''
  title:
    en_us: Ghostfolio
  category: BigBearCasaOS
  port_map: '12038'

