name: big-bear-composetoolbox
services:
  big-bear-composetoolbox:
    environment:
      NODE_ENV: production
    image: ghcr.io/bluegoosemedia/composetoolbox:latest
    pull_policy: always
    ports:
      - '3002:3000'
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/app/data
    container_name: big-bear-composetoolbox
    x-casaos:
      envs:
        - container: NODE_ENV
          description:
            en_us: 'Container Variable: NODE_ENV'
      volumes:
        - container: /app/data
          description:
            en_us: 'Container Path: /app/data'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-composetoolbox
  description:
    en_us: Self-hosted tool to edit, validate, and get suggestions for docker-compose.yml files.
  tagline:
    en_us: Compose file editor & validator
  developer: bluegoosemedia
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bluegoosemedia/composetoolbox@498d1527dcf9cc6422300216df6244ea79ae3630/public/favicon.png
  thumbnail: ''
  title:
    en_us: Compose Toolbox
  category: BigBearCasaOS
  port_map: '3002'

