name: big-bear-mind
services:
  app:
    image: mrcas/mind:v1.4.1
    container_name: mind
    environment:
      - TZ=UTC
    volumes:
      - /DATA/.docker/AppData/$AppID/db:/app/db
    ports:
      - '12080:8080'
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /app/db
          description:
            en_us: 'Container Path: /app/db'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: A simple self hosted reminder application that can send push notifications to your device. Set the reminder and forget about it!
  tagline:
    en_us: A simple self hosted reminder application that can send push notifications to your device. Set the reminder and forget about it!
  developer: Casvt
  author: BigBearTechWorld
  icon: https://i.imgur.com/UgjalkK.png
  thumbnail: ''
  title:
    en_us: MIND
  category: BigBearCasaOS
  port_map: '12080'

