name: big-bear-casaos-user-management
services:
  big-bear-casaos-user-management:
    container_name: big-bear-casaos-user-management
    image: bigbeartechworld/big-bear-casaos-user-management:0.1.1
    restart: unless-stopped
    privileged: true
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - ADMIN_USERNAME=casaos
      - ADMIN_PASSWORD=casaos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/casaos/db:/var/lib/casaos/db
      - /run/systemd/system:/run/systemd/system
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    ports:
      - '12008:5000'
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    x-casaos:
      envs:
        - container: FLASK_APP
          description:
            en_us: 'Container Variable: FLASK_APP'
        - container: FLASK_ENV
          description:
            en_us: 'Container Variable: FLASK_ENV'
        - container: ADMIN_USERNAME
          description:
            en_us: 'Container Variable: ADMIN_USERNAME'
        - container: ADMIN_PASSWORD
          description:
            en_us: 'Container Variable: ADMIN_PASSWORD'
      volumes:
        - container: /sys/fs/cgroup
          description:
            en_us: 'Container Path: /sys/fs/cgroup'
        - container: /var/lib/casaos/db
          description:
            en_us: 'Container Path: /var/lib/casaos/db'
        - container: /run/systemd/system
          description:
            en_us: 'Container Path: /run/systemd/system'
        - container: /var/run/dbus/system_bus_socket
          description:
            en_us: 'Container Path: /var/run/dbus/system_bus_socket'
      ports:
        - container: '5000'
          description:
            en_us: 'Container Port: 5000'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-casaos-user-management
  description:
    en_us: Manage users in CasaOS
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/big-bear-casaos-user-management/screenshots/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/big-bear-casaos-user-management/screenshots/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/big-bear-casaos-user-management/screenshots/screenshot-3.png
  tagline:
    en_us: Manage users in CasaOS
  developer: bigbeartechworld
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-docker-images/big-bear-casaos-user-management/logo.jpg
  thumbnail: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/big-bear-casaos-user-management/thumbnail-v2.png
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-big-bear-casaos-user-management-to-bigbearcasaos/2227#p-4191-quick-start-3
  title:
    en_us: Big Bear CasaOS User Management
  category: BigBearCasaOS
  port_map: '12008'

