name: big-bear-umami
services:
  app:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - '12160:3000'
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      db:
        condition: service_healthy
    restart: always
    x-casaos:
      envs:
        - container: DATABASE_URL
          description:
            en_us: 'Container Variable: DATABASE_URL'
        - container: DATABASE_TYPE
          description:
            en_us: 'Container Variable: DATABASE_TYPE'
        - container: APP_SECRET
          description:
            en_us: 'Container Variable: APP_SECRET'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - /DATA/.docker/AppData/$AppID/pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
    x-casaos:
      envs:
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Umami is a simple, fast, privacy-focused alternative to Google Analytics.
  tagline:
    en_us: Umami is a simple, fast, privacy-focused alternative to Google Analytics.
  developer: umami-software
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/umami.png
  thumbnail: ''
  title:
    en_us: Umami
  category: BigBearCasaOS
  port_map: '12160'

