name: big-bear-kavita
services:
  big-bear-kavita:
    container_name: big-bear-kavita
    image: jvmilazz0/kavita:0.8.9
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data/kavita-config:/kavita/config
      - /media/Safe-Storage/Library/Books:/books
      - /media/Safe-Storage/Library/Comics:/comics
      - /media/Safe-Storage/Library:/manga
    ports:
      - '12059:5000'
    x-casaos:
      volumes:
        - container: /kavita/config
          description:
            en_us: 'Container Path: /kavita/config'
        - container: /books
          description:
            en_us: 'Container Path: /books'
        - container: /comics
          description:
            en_us: 'Container Path: /comics'
        - container: /manga
          description:
            en_us: 'Container Path: /manga'
      ports:
        - container: '5000'
          description:
            en_us: 'Container Port: 5000'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-kavita
  description:
    en_us: Kavita is a fast, feature rich, cross platform reading server
  tagline:
    en_us: Kavita
  developer: jvmilazz0
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/kavita.png
  thumbnail: ''
  title:
    en_us: Kavita
  category: BigBearCasaOS
  port_map: '12059'

