name: big-bear-ejbca-ce
services:
  big-bear-ejbca-ce:
    container_name: big-bear-ejbca-ce
    image: keyfactor/ejbca-ce:9.3.7
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/persistent:/mnt/persistent
    ports:
      - '12025:8080'
      - '12026:8443'
    environment:
      - TLS_SETUP_ENABLED=simple
    x-casaos:
      envs:
        - container: TLS_SETUP_ENABLED
          description:
            en_us: 'Container Variable: TLS_SETUP_ENABLED'
      volumes:
        - container: /mnt/persistent
          description:
            en_us: 'Container Path: /mnt/persistent'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
        - container: '8443'
          description:
            en_us: 'Container Port: 8443'
x-casaos:
  architectures:
    - amd64
  main: big-bear-ejbca-ce
  description:
    en_us: The open-source public key infrastructure (PKI) and certificate authority (CA) software EJBCA is one of the longest running CA software projects. EJBCA covers all your needs - from certificate enrollment, via certificate management, to certificate validation.
  tagline:
    en_us: The open-source public key infrastructure (PKI) and certificate authority (CA)
  developer: Keyfactor
  author: BigBearCommunity
  icon: https://cdn.jsdelivr.net/gh/Keyfactor/ejbca-ce/.github/images/community-ejbca-icon.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        After installation wait for a few minutes as the initialization takes a while.
        Default admin URL: https://<host/ip>:8443/ejbca/adminweb
        Default HTTP port: 8080
        For more information on custom setup visit: https://github.com/Keyfactor/ejbca-ce
  title:
    en_us: EJBCA Community
  category: BigBearCasaOS
  port_map: '12025'

