name: big-bear-adguard-home-host
services:
  big-bear-adguard-home-host:
    container_name: big-bear-adguard-home-host
    image: adguard/adguardhome:v0.107.72
    volumes:
      - /DATA/.docker/AppData/$AppID/data/work:/opt/adguardhome/work
      - /DATA/.docker/AppData/$AppID/data/conf:/opt/adguardhome/conf
    restart: unless-stopped
    network_mode: host
    x-casaos:
      volumes:
        - container: /opt/adguardhome/work
          description:
            en_us: 'Container Path: /opt/adguardhome/work'
        - container: /opt/adguardhome/conf
          description:
            en_us: 'Container Path: /opt/adguardhome/conf'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-adguard-home-host
  description:
    en_us: Use if you're going to use Adguard Home as a DHCP server. AdGuard Home is a network-wide software for blocking ads and tracking. After you set it up, it'll cover all your home devices, and you won't need any client-side software for that. Learn more on our official Github repository.
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-3.png
  tagline:
    en_us: Network Mode is host. Network-wide ads & trackers blocking DNS server.
  developer: AdGuardTeam
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/adguard-home.png
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/thumbnail.png
  tips:
    before_install:
      en_us: |
        Run this script:

        ```
        bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/generate-adguard-home-config/run.sh)"
        ```

        After running this script, you need to restart the container.
  title:
    en_us: AdGuard Home (HOST)
  category: BigBearCasaOS
  port_map: '80'

