name: big-bear-minio
services:
  app:
    image: bigbeartechworld/big-bear-minio:RELEASE.2025-10-15T17-29-55Z
    container_name: big-bear-minio
    volumes:
      - /DATA/.docker/AppData/$AppID:/data
    ports:
      - '9010:9000'
      - '9011:9001'
    environment:
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ROOT_USER: minioadmin
    restart: unless-stopped
    command:
      - server
      - '--console-address'
      - ':9001'
      - /data
    x-casaos:
      envs:
        - container: MINIO_ROOT_PASSWORD
          description:
            en_us: 'Container Variable: MINIO_ROOT_PASSWORD'
        - container: MINIO_ROOT_USER
          description:
            en_us: 'Container Variable: MINIO_ROOT_USER'
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
      ports:
        - container: '9000'
          description:
            en_us: 'Container Port: 9000'
        - container: '9001'
          description:
            en_us: 'Container Port: 9001'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: A distributed object storage server built for cloud applications and devops. Default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables.
  tagline:
    en_us: An open-source S3 alternative
  developer: minio
  author: BigBearCommunity
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/minio.png
  thumbnail: ''
  title:
    en_us: Minio
  category: BigBearCasaOS
  port_map: '9010'

