name: big-bear-kopia
services:
  big-bear-kopia:
    container_name: big-bear-kopia
    image: ghcr.io/thespad/kopia-server:v0.17.0-spad3
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC
      - KOPIA_HTTPS=true
      - KOPIA_UI_USERNAME=casaos
      - KOPIA_UI_PASSWORD=casaos
      - KOPIA_PASSWORD=casaos
      - REFRESH_INTERVAL=
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
      - /DATA/.docker/AppData/$AppID/home:/backups/home
      - /var/lib/docker/volumes:/backups/docker:ro
      - /DATA/.docker/AppData/$AppID/repository:/repository
      - /tmp:/tmp:shared
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '51515:51515'
    cap_add:
      - SYS_ADMIN
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: KOPIA_HTTPS
          description:
            en_us: 'Container Variable: KOPIA_HTTPS'
        - container: KOPIA_UI_USERNAME
          description:
            en_us: 'Container Variable: KOPIA_UI_USERNAME'
        - container: KOPIA_UI_PASSWORD
          description:
            en_us: 'Container Variable: KOPIA_UI_PASSWORD'
        - container: KOPIA_PASSWORD
          description:
            en_us: 'Container Variable: KOPIA_PASSWORD'
        - container: REFRESH_INTERVAL
          description:
            en_us: 'Container Variable: REFRESH_INTERVAL'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /backups/home
          description:
            en_us: 'Container Path: /backups/home'
        - container: /backups/docker
          description:
            en_us: 'Container Path: /backups/docker'
        - container: /repository
          description:
            en_us: 'Container Path: /repository'
        - container: /tmp
          description:
            en_us: 'Container Path: /tmp'
        - container: /var/run/docker.sock
          description:
            en_us: 'Container Path: /var/run/docker.sock'
      ports:
        - container: '51515'
          description:
            en_us: 'Container Port: 51515'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-kopia
  description:
    en_us: Kopia is a fast and secure open-source backup/restore tool that allows you to create encrypted snapshots of your data and save the snapshots to remote or cloud storage of your choice, to network-attached storage or server, or locally on your machine.
  tagline:
    en_us: Kopia
  developer: thespad
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/kopia.png
  thumbnail: ''
  title:
    en_us: Kopia
  category: BigBearCasaOS
  port_map: '51515'

