name: big-bear-plex-nvidia
services:
  big-bear-plex-nvidia:
    container_name: big-bear-plex-nvidia
    image: linuxserver/plex:1.43.0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=
      - CPU_FALLBACK=true
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    network_mode: host
    volumes:
      - /DATA/.docker/AppData/$AppID/config:/config
      - /media/Safe-Storage/Library/TV:/tv
      - /media/Safe-Storage/Library/Movies:/movies
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
    deploy:
      resources:
        reservations:
          memory: 256M
          devices:
            - capabilities:
                - gpu
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: VERSION
          description:
            en_us: 'Container Variable: VERSION'
        - container: PLEX_CLAIM
          description:
            en_us: 'Container Variable: PLEX_CLAIM'
        - container: CPU_FALLBACK
          description:
            en_us: 'Container Variable: CPU_FALLBACK'
        - container: NVIDIA_VISIBLE_DEVICES
          description:
            en_us: 'Container Variable: NVIDIA_VISIBLE_DEVICES'
      volumes:
        - container: /config
          description:
            en_us: 'Container Path: /config'
        - container: /tv
          description:
            en_us: 'Container Path: /tv'
        - container: /movies
          description:
            en_us: 'Container Path: /movies'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-plex-nvidia
  description:
    en_us: Stream Movies & TV Shows with NVIDIA GPU
  tagline:
    en_us: Stream Movies & TV Shows with NVIDIA GPU
  developer: plexinc
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/plex.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-plex-with-nvidia-gpu-to-bigbearcasaos/3447?u=dragonfire1119
  title:
    en_us: Plex with NVIDIA GPU
  category: BigBearCasaOS
  port_map: '32400'

