name: big-bear-syncthing
services:
  big-bear-syncthing:
    container_name: big-bear-syncthing
    image: syncthing/syncthing:2.0
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/var/syncthing
      - /media/Safe-Storage/Library/Sync:/media/data/syncthing
    ports:
      - '8384:8384'
      - 22000:22000/tcp
      - 12154:22000/udp
      - 21027:21027/udp
    environment:
      - PUID=1000
      - PGID=1000
    stop_grace_period: 1m
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
      volumes:
        - container: /var/syncthing
          description:
            en_us: 'Container Path: /var/syncthing'
        - container: /media/data/syncthing
          description:
            en_us: 'Container Path: /media/data/syncthing'
      ports:
        - container: '8384'
          description:
            en_us: 'Container Port: 8384'
        - container: '22000'
          description:
            en_us: 'Container Port: 22000'
        - container: '22000'
          description:
            en_us: 'Container Port: 22000'
        - container: '21027'
          description:
            en_us: 'Container Port: 21027'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-syncthing
  description:
    en_us: Syncthing is a continuous file synchronization program. It synchronizes files between two or more computers. We strive to fulfill the goals below. The goals are listed in order of importance, the most important one being the first.
  tagline:
    en_us: Peer-to-peer file synchronization between your devices
  developer: syncthing
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/syncthing.png
  thumbnail: ''
  title:
    en_us: Syncthing
  category: BigBearCasaOS
  port_map: '8384'

