name: big-bear-wallos
services:
  big-bear-wallos:
    container_name: big-bear-wallos
    image: bellamy/wallos:4.6.1
    restart: unless-stopped
    environment:
      TZ: UTC
    volumes:
      - /DATA/.docker/AppData/$AppID/db:/var/www/html/db
      - /DATA/.docker/AppData/$AppID/logos:/var/www/html/images/uploads/logos
    ports:
      - '8282:80'
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /var/www/html/db
          description:
            en_us: 'Container Path: /var/www/html/db'
        - container: /var/www/html/images/uploads/logos
          description:
            en_us: 'Container Path: /var/www/html/images/uploads/logos'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-wallos
  description:
    en_us: 'Wallos: Open-Source Personal Subscription Tracker'
  tagline:
    en_us: Wallos
  developer: bellamy
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/wallos.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Before you install read this: https://community.bigbeartechworld.com/t/added-wallos-to-bigbearcasaos/2139?u=dragonfire1119
  title:
    en_us: Wallos
  category: BigBearCasaOS
  port_map: '8282'

