name: big-bear-note-mark-aio
services:
  big-bear-note-mark-aio:
    container_name: big-bear-note-mark-aio
    image: ghcr.io/enchant97/note-mark-aio:0.19.0
    restart: unless-stopped
    environment:
      - JWT_SECRET="MGZiMzlkM2EtNmYxNC00NzNlLWI2YjItYTViY2M0Mzg0NjNl"
      - CORS_ORIGINS="http://example.com:8000"
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/data
    ports:
      - '12089:8000'
    networks:
      - big_bear_note_mark_aio_network
    x-casaos:
      envs:
        - container: JWT_SECRET
          description:
            en_us: 'Container Variable: JWT_SECRET'
        - container: CORS_ORIGINS
          description:
            en_us: 'Container Variable: CORS_ORIGINS'
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
      ports:
        - container: '8000'
          description:
            en_us: 'Container Port: 8000'
networks:
  big_bear_note_mark_aio_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-note-mark-aio
  description:
    en_us: Note Mark Aio is a self-hosted note taking app that allows you to create, organize, and share notes. It's a fork of the popular note-mark app with a focus on simplicity and ease of use.
  tagline:
    en_us: Note Mark Aio
  developer: enchant97
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/note-mark-aio/logo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-note-mark-aio-to-bigbearcasaos/1952#p-3621-documentation-4
  title:
    en_us: Note Mark AIO
  category: BigBearCasaOS
  port_map: '12089'

