name: big-bear-erugo
services:
  big-bear-erugo:
    container_name: big-bear-erugo
    image: wardy784/erugo:0.2.15
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/storage:/var/www/html/storage
    ports:
      - '9997:80'
    x-casaos:
      volumes:
        - container: /var/www/html/storage
          description:
            en_us: 'Container Path: /var/www/html/storage'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-erugo
  description:
    en_us: A powerful, self-hosted file-sharing platform built with PHP and Laravel with a Vue.js frontend. It offers secure, customizable file-transfer capabilities through an elegant user interface, giving you complete control over your data while providing a seamless experience for both senders and recipients.
  tagline:
    en_us: A powerful, self-hosted file-sharing platform built with PHP and Laravel with a Vue.js frontend.
  developer: wardy784
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/erugo.png
  thumbnail: ''
  title:
    en_us: Erugo
  category: BigBearCasaOS
  port_map: '9997'

