name: big-bear-immich-kiosk
services:
  big-bear-immich-kiosk:
    container_name: big-bear-immich-kiosk
    image: ghcr.io/damongolding/immich-kiosk:0.33.2
    tty: true
    restart: unless-stopped
    environment:
      LANG: en_us
      TZ: UTC
      KIOSK_IMMICH_API_KEY: ''
      KIOSK_IMMICH_URL: ''
      KIOSK_IMMICH_EXTERNAL_URL: ''
    ports:
      - '12051:3000'
    x-casaos:
      envs:
        - container: LANG
          description:
            en_us: 'Container Variable: LANG'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
        - container: KIOSK_IMMICH_API_KEY
          description:
            en_us: 'Container Variable: KIOSK_IMMICH_API_KEY'
        - container: KIOSK_IMMICH_URL
          description:
            en_us: 'Container Variable: KIOSK_IMMICH_URL'
        - container: KIOSK_IMMICH_EXTERNAL_URL
          description:
            en_us: 'Container Variable: KIOSK_IMMICH_EXTERNAL_URL'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-immich-kiosk
  description:
    en_us: Immich Kiosk is a lightweight slideshow for running on kiosk devices and browsers that uses Immich as a data source.
  tagline:
    en_us: Immich Kiosk
  developer: damongolding
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/immich-kiosk.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-immich-kiosk-to-bigbearcasaos/3513?u=dragonfire1119
  title:
    en_us: Immich Kiosk
  category: BigBearCasaOS
  port_map: '12051'

