name: big-bear-semaphore
services:
  big-bear-semaphore:
    container_name: big-bear-semaphore
    image: semaphoreui/semaphore:v2.17.16
    restart: unless-stopped
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: big-bear-semaphore-db
      SEMAPHORE_DB_PORT: '3306'
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_ADMIN_PASSWORD: password
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@example.com
      SEMAPHORE_ADMIN: admin
      TZ: UTC
    volumes:
      - /DATA/.docker/AppData/$AppID/home:/etc/semaphore
      - /DATA/.docker/AppData/$AppID/lib:/var/lib/semaphore
    ports:
      - '12146:3000'
    networks:
      - big-bear-semaphore-network
    x-casaos:
      envs:
        - container: SEMAPHORE_DB_USER
          description:
            en_us: 'Container Variable: SEMAPHORE_DB_USER'
        - container: SEMAPHORE_DB_PASS
          description:
            en_us: 'Container Variable: SEMAPHORE_DB_PASS'
        - container: SEMAPHORE_DB_HOST
          description:
            en_us: 'Container Variable: SEMAPHORE_DB_HOST'
        - container: SEMAPHORE_DB_PORT
          description:
            en_us: 'Container Variable: SEMAPHORE_DB_PORT'
        - container: SEMAPHORE_DB_DIALECT
          description:
            en_us: 'Container Variable: SEMAPHORE_DB_DIALECT'
        - container: SEMAPHORE_DB
          description:
            en_us: 'Container Variable: SEMAPHORE_DB'
        - container: SEMAPHORE_ADMIN_PASSWORD
          description:
            en_us: 'Container Variable: SEMAPHORE_ADMIN_PASSWORD'
        - container: SEMAPHORE_ADMIN_NAME
          description:
            en_us: 'Container Variable: SEMAPHORE_ADMIN_NAME'
        - container: SEMAPHORE_ADMIN_EMAIL
          description:
            en_us: 'Container Variable: SEMAPHORE_ADMIN_EMAIL'
        - container: SEMAPHORE_ADMIN
          description:
            en_us: 'Container Variable: SEMAPHORE_ADMIN'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /etc/semaphore
          description:
            en_us: 'Container Path: /etc/semaphore'
        - container: /var/lib/semaphore
          description:
            en_us: 'Container Path: /var/lib/semaphore'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
  big-bear-semaphore-db:
    container_name: big-bear-semaphore-db
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore
    networks:
      - big-bear-semaphore-network
    x-casaos:
      envs:
        - container: MYSQL_RANDOM_ROOT_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_RANDOM_ROOT_PASSWORD'
        - container: MYSQL_DATABASE
          description:
            en_us: 'Container Variable: MYSQL_DATABASE'
        - container: MYSQL_USER
          description:
            en_us: 'Container Variable: MYSQL_USER'
        - container: MYSQL_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_PASSWORD'
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: 'Container Path: /var/lib/mysql'
networks:
  big-bear-semaphore-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-semaphore
  description:
    en_us: Ansible Semaphore is a modern UI for Ansible. It lets you easily run Ansible playbooks, get notifications about fails, control access to deployment system.
  tagline:
    en_us: Ansible Semaphore
  developer: semaphore
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/semaphore-ui.png
  thumbnail: ''
  title:
    en_us: Ansible Semaphore
  category: BigBearCasaOS
  port_map: '12146'

