name: big-bear-peppermint
services:
  app:
    container_name: big-bear-peppermint
    image: pepperlabs/peppermint:latest
    restart: always
    privileged: false
    networks:
      - default
    ports:
      - '12102:3000'
      - 5003:5003/tcp
    environment:
      - API_URL=http://local.host:5003
      - DB_HOST=db
      - DB_PASSWORD=casaos
      - DB_USERNAME=casaos
      - SECRET=peppermint4life
    depends_on:
      db:
        condition: service_started
        required: true
    x-casaos:
      envs:
        - container: API_URL
          description:
            en_us: 'Container Variable: API_URL'
        - container: DB_HOST
          description:
            en_us: 'Container Variable: DB_HOST'
        - container: DB_PASSWORD
          description:
            en_us: 'Container Variable: DB_PASSWORD'
        - container: DB_USERNAME
          description:
            en_us: 'Container Variable: DB_USERNAME'
        - container: SECRET
          description:
            en_us: 'Container Variable: SECRET'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
        - container: '5003'
          description:
            en_us: 'Container Port: 5003'
  db:
    container_name: db
    image: postgres:15.5
    restart: always
    environment:
      - PGID=1000
      - POSTGRES_DB=casaos
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
      - PUID=1000
      - TZ=Etc/UTC
    ports:
      - '12103:5432'
    volumes:
      - /DATA/.docker/AppData/$AppID/postgres/data:/var/lib/postgresql/data
    networks:
      - default
    privileged: false
    x-casaos:
      envs:
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
      ports:
        - container: '5432'
          description:
            en_us: 'Container Port: 5432'
networks:
  default:
    name: peppermint_default
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Peppermint is a central hub for your help desk. A powerfully easy system for tracking, prioritising, and solving customer support tickets.
  tagline:
    en_us: peppermint
  developer: Pepperlabs
  author: BigBearCommunity
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/peppermint/logo.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        ### Additional Instructions:
        After finished installing, open the `app settings` and update the `API_URL` to point it to your Home Server's IP Address.
        e.g:
        ``` http://192.168.31.31:5003
        ```
        ### Default credentials:
        Username: `admin@admin.com` Password: `1234`
  title:
    en_us: Peppermint
  category: BigBearCasaOS
  port_map: '12102'

