name: big-bear-pingvin-share
services:
  app:
    image: stonith404/pingvin-share:v1.13.0
    restart: unless-stopped
    ports:
      - '12120:3000'
    volumes:
      - /DATA/.docker/AppData/pingvin-share/data:/opt/app/backend/data
      - /DATA/.docker/AppData/pingvin-share/images:/opt/app/frontend/public/img
    x-casaos:
      volumes:
        - container: /opt/app/backend/data
          description:
            en_us: 'Container Path: /opt/app/backend/data'
        - container: /opt/app/frontend/public/img
          description:
            en_us: 'Container Path: /opt/app/frontend/public/img'
      ports:
        - container: '3000'
          description:
            en_us: 'Container Port: 3000'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Pingvin Share is self-hosted file sharing platform and an alternative for WeTransfer.
  tagline:
    en_us: Pingvin Share
  developer: stonith404
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/pingvin-share.png
  thumbnail: https://user-images.githubusercontent.com/58886915/225038319-b2ef742c-3a74-4eb6-9689-4207a36842a4.png
  title:
    en_us: Pingvin Share
  category: BigBearCasaOS
  port_map: '12120'

