name: big-bear-tandoor
services:
  big-bear-tandoor:
    container_name: big-bear-tandoor
    image: ghcr.io/tandoorrecipes/recipes:2.5.3
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/staticfiles:/opt/recipes/staticfiles
      - /media/Safe-Storage/Library/Recipes:/opt/recipes/mediafiles
    ports:
      - '12155:8080'
    environment:
      - SECRET_KEY=6496f725-e4a4-4fa5-9f7b-db0114bc1568
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=big-bear-tandoor-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=tandoor
      - POSTGRES_PASSWORD=100c7d31-9ec5-44ec-9101-e226c8e2420d
      - POSTGRES_DB=tandoordb
    networks:
      - big_bear_tandoor_network
    depends_on:
      big-bear-tandoor-db:
        condition: service_healthy
    x-casaos:
      envs:
        - container: SECRET_KEY
          description:
            en_us: 'Container Variable: SECRET_KEY'
        - container: DB_ENGINE
          description:
            en_us: 'Container Variable: DB_ENGINE'
        - container: POSTGRES_HOST
          description:
            en_us: 'Container Variable: POSTGRES_HOST'
        - container: POSTGRES_PORT
          description:
            en_us: 'Container Variable: POSTGRES_PORT'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
      volumes:
        - container: /opt/recipes/staticfiles
          description:
            en_us: 'Container Path: /opt/recipes/staticfiles'
        - container: /opt/recipes/mediafiles
          description:
            en_us: 'Container Path: /opt/recipes/mediafiles'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
  big-bear-tandoor-db:
    image: postgres:15-alpine
    container_name: big-bear-tandoor-db
    volumes:
      - /DATA/.docker/AppData/$AppID/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=tandoor
      - POSTGRES_PASSWORD=100c7d31-9ec5-44ec-9101-e226c8e2420d
      - POSTGRES_DB=tandoordb
    restart: unless-stopped
    networks:
      - big_bear_tandoor_network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
        - '-d'
        - tandoor
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    x-casaos:
      envs:
        - container: POSTGRES_PORT
          description:
            en_us: 'Container Variable: POSTGRES_PORT'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
networks:
  big_bear_tandoor_network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-tandoor
  description:
    en_us: Drop your collection of links and notes. Get Tandoor and never look back onto a time without recipe management, storage, sharing and collaborative cooking!
  tagline:
    en_us: Recipe collection manager.
  developer: tandoorrecipes
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/tandoor-recipes.png
  thumbnail: ''
  title:
    en_us: Tandoor
  category: BigBearCasaOS
  port_map: '12155'

