name: big-bear-homer
services:
  app:
    image: b4bz/homer:v25.11.1
    container_name: homer
    volumes:
      - /DATA/.docker/AppData/$AppID/assets:/www/assets
    ports:
      - '12048:8080'
    user: '1000:1000'
    environment:
      - INIT_ASSETS=1
    x-casaos:
      envs:
        - container: INIT_ASSETS
          description:
            en_us: 'Container Variable: INIT_ASSETS'
      volumes:
        - container: /www/assets
          description:
            en_us: 'Container Path: /www/assets'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: A dead simple static HOMepage for your servER to keep your services on hand, from a simple yaml configuration file.
  tagline:
    en_us: Homer
  developer: bastienwirtz
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/homer.png
  thumbnail: ''
  title:
    en_us: Homer
  category: BigBearCasaOS
  port_map: '12048'

