name: big-bear-penpot
services:
  penpot-frontend:
    container_name: big-bear-penpot-frontend
    image: penpotapp/frontend:2.13.3
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/assets:/opt/data/assets
    ports:
      - '9001:8080'
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - big-bear-penpot-network
    x-casaos:
      volumes:
        - container: /opt/data/assets
          description:
            en_us: 'Container Path: /opt/data/assets'
      ports:
        - container: '8080'
          description:
            en_us: 'Container Port: 8080'
  penpot-backend:
    image: penpotapp/backend:2.13.3
    container_name: big-bear-penpot-backend
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/assets:/opt/data/assets
    depends_on:
      - penpot-postgres
      - penpot-redis
    networks:
      - big-bear-penpot-network
    environment:
      - PENPOT_FLAGS=enable-registration enable-login-with-password disable-email-verification disable-secure-session-cookies
      - PENPOT_SECRET_KEY=big-bear-penpot-secret-key
      - PENPOT_PUBLIC_URI=http://big-bear-penpot-frontend:8080
      - PENPOT_DATABASE_URI=postgresql://big-bear-penpot-postgres/penpot
      - PENPOT_DATABASE_USERNAME=bigbear
      - PENPOT_DATABASE_PASSWORD=casaos
      - PENPOT_REDIS_URI=redis://big-bear-penpot-redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=false
    x-casaos:
      envs:
        - container: PENPOT_FLAGS
          description:
            en_us: 'Container Variable: PENPOT_FLAGS'
        - container: PENPOT_SECRET_KEY
          description:
            en_us: 'Container Variable: PENPOT_SECRET_KEY'
        - container: PENPOT_PUBLIC_URI
          description:
            en_us: 'Container Variable: PENPOT_PUBLIC_URI'
        - container: PENPOT_DATABASE_URI
          description:
            en_us: 'Container Variable: PENPOT_DATABASE_URI'
        - container: PENPOT_DATABASE_USERNAME
          description:
            en_us: 'Container Variable: PENPOT_DATABASE_USERNAME'
        - container: PENPOT_DATABASE_PASSWORD
          description:
            en_us: 'Container Variable: PENPOT_DATABASE_PASSWORD'
        - container: PENPOT_REDIS_URI
          description:
            en_us: 'Container Variable: PENPOT_REDIS_URI'
        - container: PENPOT_ASSETS_STORAGE_BACKEND
          description:
            en_us: 'Container Variable: PENPOT_ASSETS_STORAGE_BACKEND'
        - container: PENPOT_STORAGE_ASSETS_FS_DIRECTORY
          description:
            en_us: 'Container Variable: PENPOT_STORAGE_ASSETS_FS_DIRECTORY'
        - container: PENPOT_TELEMETRY_ENABLED
          description:
            en_us: 'Container Variable: PENPOT_TELEMETRY_ENABLED'
      volumes:
        - container: /opt/data/assets
          description:
            en_us: 'Container Path: /opt/data/assets'
  penpot-exporter:
    image: penpotapp/exporter:2.13.3
    container_name: big-bear-penpot-exporter
    restart: unless-stopped
    networks:
      - big-bear-penpot-network
    environment:
      - PENPOT_PUBLIC_URI=http://big-bear-penpot-frontend:8080
      - PENPOT_REDIS_URI=redis://big-bear-penpot-redis/0
    x-casaos:
      envs:
        - container: PENPOT_PUBLIC_URI
          description:
            en_us: 'Container Variable: PENPOT_PUBLIC_URI'
        - container: PENPOT_REDIS_URI
          description:
            en_us: 'Container Variable: PENPOT_REDIS_URI'
  penpot-postgres:
    image: postgres:14
    restart: unless-stopped
    container_name: big-bear-penpot-postgres
    stop_signal: SIGINT
    volumes:
      - /DATA/.docker/AppData/$AppID/pgdata:/var/lib/postgresql/data
    networks:
      - big-bear-penpot-network
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=bigbear
      - POSTGRES_PASSWORD=casaos
    x-casaos:
      envs:
        - container: POSTGRES_INITDB_ARGS
          description:
            en_us: 'Container Variable: POSTGRES_INITDB_ARGS'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
  penpot-redis:
    image: redis:7.4.6@sha256:d7432711a2a5c99c2e9dd0e006061cd274d7cb7a9e77f07ffe2ea99e21244677
    container_name: big-bear-penpot-redis
    restart: unless-stopped
    networks:
      - big-bear-penpot-network
  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    restart: always
    expose:
      - '1025'
    ports:
      - '12101:1080'
    networks:
      - big-bear-penpot-network
    x-casaos:
      ports:
        - container: '1080'
          description:
            en_us: 'Container Port: 1080'
networks:
  big-bear-penpot-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: penpot-frontend
  description:
    en_us: Designers and developers can finally work in unison to build beautifully designed software experiences that truly scale up.
  tagline:
    en_us: Bring Design Freedom to your Product Team
  developer: penpotapp
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/penpot/logo.jpg
  thumbnail: ''
  title:
    en_us: Penpot
  category: BigBearCasaOS
  port_map: '9001'

