name: big-bear-paperless-ngx
services:
  big-bear-paperless-ngx:
    container_name: big-bear-paperless-ngx
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.10
    restart: unless-stopped
    environment:
      PAPERLESS_REDIS: redis://big-bear-paperless-ngx-broker:6379
      PAPERLESS_DBHOST: big-bear-paperless-ngx-db
      PAPERLESS_DBUSER: bigbear
      PAPERLESS_DBPASS: c6e74adb-3fce-4318-b657-4bdc0858fcac
      PAPERLESS_ADMIN_USER: bigbear
      PAPERLESS_ADMIN_PASSWORD: c22e92a6-2a3d-4edf-a98e-4044834daea6
      PAPERLESS_TIKA_ENABLED: 'true'
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://big-bear-paperless-ngx-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://big-bear-paperless-ngx-tika:9998
      PAPERLESS_URL: http://[YOUR_IP]:8000
      COMPOSE_PROJECT_NAME: big-bear-paperless-ngx
      PAPERLESS_CSRF_TRUSTED_ORIGINS: http://[YOUR_IP]:8000
    volumes:
      - /DATA/.docker/AppData/$AppID/paperless/data:/usr/src/paperless/data
      - /media/Safe-Storage/Library/Documents:/usr/src/paperless/media
      - /DATA/.docker/AppData/$AppID/paperless/export:/usr/src/paperless/export
      - /DATA/.docker/AppData/$AppID/paperless/consume:/usr/src/paperless/consume
      - /DATA/.docker/AppData/$AppID/paperless/tmp:/tmp
    ports:
      - '12099:8000'
    depends_on:
      - big-bear-paperless-ngx-db
      - big-bear-paperless-ngx-broker
    networks:
      - big-bear-paperless-ngx-network
    x-casaos:
      envs:
        - container: PAPERLESS_REDIS
          description:
            en_us: 'Container Variable: PAPERLESS_REDIS'
        - container: PAPERLESS_DBHOST
          description:
            en_us: 'Container Variable: PAPERLESS_DBHOST'
        - container: PAPERLESS_DBUSER
          description:
            en_us: 'Container Variable: PAPERLESS_DBUSER'
        - container: PAPERLESS_DBPASS
          description:
            en_us: 'Container Variable: PAPERLESS_DBPASS'
        - container: PAPERLESS_ADMIN_USER
          description:
            en_us: 'Container Variable: PAPERLESS_ADMIN_USER'
        - container: PAPERLESS_ADMIN_PASSWORD
          description:
            en_us: 'Container Variable: PAPERLESS_ADMIN_PASSWORD'
        - container: PAPERLESS_TIKA_ENABLED
          description:
            en_us: 'Container Variable: PAPERLESS_TIKA_ENABLED'
        - container: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
          description:
            en_us: 'Container Variable: PAPERLESS_TIKA_GOTENBERG_ENDPOINT'
        - container: PAPERLESS_TIKA_ENDPOINT
          description:
            en_us: 'Container Variable: PAPERLESS_TIKA_ENDPOINT'
        - container: PAPERLESS_URL
          description:
            en_us: 'Container Variable: PAPERLESS_URL'
        - container: COMPOSE_PROJECT_NAME
          description:
            en_us: 'Container Variable: COMPOSE_PROJECT_NAME'
        - container: PAPERLESS_CSRF_TRUSTED_ORIGINS
          description:
            en_us: 'Container Variable: PAPERLESS_CSRF_TRUSTED_ORIGINS'
      volumes:
        - container: /usr/src/paperless/data
          description:
            en_us: 'Container Path: /usr/src/paperless/data'
        - container: /usr/src/paperless/media
          description:
            en_us: 'Container Path: /usr/src/paperless/media'
        - container: /usr/src/paperless/export
          description:
            en_us: 'Container Path: /usr/src/paperless/export'
        - container: /usr/src/paperless/consume
          description:
            en_us: 'Container Path: /usr/src/paperless/consume'
        - container: /tmp
          description:
            en_us: 'Container Path: /tmp'
      ports:
        - container: '8000'
          description:
            en_us: 'Container Port: 8000'
  big-bear-paperless-ngx-broker:
    container_name: big-bear-paperless-ngx-broker
    image: docker.io/library/redis:8.6.1
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/redis:/data
    networks:
      - big-bear-paperless-ngx-network
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
  big-bear-paperless-ngx-db:
    container_name: big-bear-paperless-ngx-db
    image: library/postgres:16
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: bigbear
      POSTGRES_PASSWORD: c6e74adb-3fce-4318-b657-4bdc0858fcac
    networks:
      - big-bear-paperless-ngx-network
    x-casaos:
      envs:
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
  big-bear-paperless-ngx-gotenberg:
    container_name: big-bear-paperless-ngx-gotenberg
    image: gotenberg/gotenberg:8.27
    restart: unless-stopped
    command:
      - gotenberg
      - '--chromium-disable-javascript=true'
      - '--chromium-allow-list=file:///tmp/.*'
    networks:
      - big-bear-paperless-ngx-network
  big-bear-paperless-ngx-tika:
    container_name: big-bear-paperless-ngx-tika
    image: apache/tika:3.2.3.0
    restart: unless-stopped
    volumes:
      - /DATA/.docker/AppData/$AppID/tika/tmp:/tmp
    networks:
      - big-bear-paperless-ngx-network
    x-casaos:
      volumes:
        - container: /tmp
          description:
            en_us: 'Container Path: /tmp'
networks:
  big-bear-paperless-ngx-network:
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-paperless-ngx
  description:
    en_us: Paperless-ngx is a community-supported open-source document management system that transforms your physical documents into a searchable online archive so you can keep, well, less paper.
  tagline:
    en_us: Paperless-ngx
  developer: paperless-ngx
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/paperless-ngx.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-paperlessngx-to-bigbearcasaos/1954#p-3625-documentation-4
  title:
    en_us: Paperless-ngx
  category: BigBearCasaOS
  port_map: '12099'

