name: big-bear-portracker
services:
  big-bear-portracker:
    container_name: big-bear-portracker
    image: mostafawahied/portracker:1.3
    restart: unless-stopped
    environment:
      - PORT=4999
      - DATABASE_PATH=/data/portracker.db
      - TRUSTED_LOCAL_EMAIL=your@email.com
      - CACHE_TIMEOUT_MS=30000
      - DISABLE_CACHE=false
      - INCLUDE_UDP=false
      - DEBUG=false
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '4999:4999'
    x-casaos:
      envs:
        - container: PORT
          description:
            en_us: 'Container Variable: PORT'
        - container: DATABASE_PATH
          description:
            en_us: 'Container Variable: DATABASE_PATH'
        - container: TRUSTED_LOCAL_EMAIL
          description:
            en_us: 'Container Variable: TRUSTED_LOCAL_EMAIL'
        - container: CACHE_TIMEOUT_MS
          description:
            en_us: 'Container Variable: CACHE_TIMEOUT_MS'
        - container: DISABLE_CACHE
          description:
            en_us: 'Container Variable: DISABLE_CACHE'
        - container: INCLUDE_UDP
          description:
            en_us: 'Container Variable: INCLUDE_UDP'
        - container: DEBUG
          description:
            en_us: 'Container Variable: DEBUG'
      volumes:
        - container: /data
          description:
            en_us: 'Container Path: /data'
        - container: /var/run/docker.sock
          description:
            en_us: 'Container Path: /var/run/docker.sock'
      ports:
        - container: '4999'
          description:
            en_us: 'Container Port: 4999'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-portracker
  description:
    en_us: A self-hosted, real-time port monitoring and discovery tool that automatically discovers and maps network services across systems.
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/portracker/screenshots/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/portracker/screenshots/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/portracker/screenshots/screenshot-3.png
    - https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps@main/apps/portracker/screenshots/screenshot-4.png
  tagline:
    en_us: Real-time Port Monitoring Tool
  developer: Mostafa-Wahied
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/portracker.png
  thumbnail: ''
  tips:
    before_install:
      en_us: |-
        Portracker is a self-hosted port monitoring tool that automatically discovers network services.
                        
        Read this before installing: https://community.bigbeartechworld.com/t/added-portracker-to-bigbearcasaos/5003?u=dragonfire1119
  title:
    en_us: Portracker
  category: BigBearCasaOS
  port_map: '4999'

