name: big-bear-omada-controller
services:
  app:
    container_name: big-bear-omada-controller
    image: mbentley/omada-controller:6.1
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    network_mode: host
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
    volumes:
      - /DATA/.docker/AppData/$AppID/data:/opt/tplink/EAPController/data
      - /DATA/.docker/AppData/$AppID/logs:/opt/tplink/EAPController/logs
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: 'Container Variable: PUID'
        - container: PGID
          description:
            en_us: 'Container Variable: PGID'
        - container: MANAGE_HTTP_PORT
          description:
            en_us: 'Container Variable: MANAGE_HTTP_PORT'
        - container: MANAGE_HTTPS_PORT
          description:
            en_us: 'Container Variable: MANAGE_HTTPS_PORT'
        - container: PORTAL_HTTP_PORT
          description:
            en_us: 'Container Variable: PORTAL_HTTP_PORT'
        - container: PORTAL_HTTPS_PORT
          description:
            en_us: 'Container Variable: PORTAL_HTTPS_PORT'
        - container: PORT_APP_DISCOVERY
          description:
            en_us: 'Container Variable: PORT_APP_DISCOVERY'
        - container: PORT_ADOPT_V1
          description:
            en_us: 'Container Variable: PORT_ADOPT_V1'
        - container: PORT_UPGRADE_V1
          description:
            en_us: 'Container Variable: PORT_UPGRADE_V1'
        - container: PORT_MANAGER_V1
          description:
            en_us: 'Container Variable: PORT_MANAGER_V1'
        - container: PORT_MANAGER_V2
          description:
            en_us: 'Container Variable: PORT_MANAGER_V2'
        - container: PORT_DISCOVERY
          description:
            en_us: 'Container Variable: PORT_DISCOVERY'
        - container: SHOW_SERVER_LOGS
          description:
            en_us: 'Container Variable: SHOW_SERVER_LOGS'
        - container: SHOW_MONGODB_LOGS
          description:
            en_us: 'Container Variable: SHOW_MONGODB_LOGS'
        - container: SSL_CERT_NAME
          description:
            en_us: 'Container Variable: SSL_CERT_NAME'
        - container: SSL_KEY_NAME
          description:
            en_us: 'Container Variable: SSL_KEY_NAME'
        - container: TZ
          description:
            en_us: 'Container Variable: TZ'
      volumes:
        - container: /opt/tplink/EAPController/data
          description:
            en_us: 'Container Path: /opt/tplink/EAPController/data'
        - container: /opt/tplink/EAPController/logs
          description:
            en_us: 'Container Path: /opt/tplink/EAPController/logs'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Docker image for TP-Link Omada Controller to control TP-Link Omada Hardware
  tagline:
    en_us: TP-Link Omada Controller
  developer: mbentley
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/omada.png
  thumbnail: ''
  title:
    en_us: TP-Link Omada Controller
  category: BigBearCasaOS
  port_map: '8088'

