name: big-bear-wordpress
services:
  app:
    image: wordpress:6.9.1
    ports:
      - '12181:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: casaos
      WORDPRESS_DB_PASSWORD: casaos
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /DATA/.docker/AppData/$AppID/html:/var/www/html
    depends_on:
      - db
    x-casaos:
      envs:
        - container: WORDPRESS_DB_HOST
          description:
            en_us: 'Container Variable: WORDPRESS_DB_HOST'
        - container: WORDPRESS_DB_USER
          description:
            en_us: 'Container Variable: WORDPRESS_DB_USER'
        - container: WORDPRESS_DB_PASSWORD
          description:
            en_us: 'Container Variable: WORDPRESS_DB_PASSWORD'
        - container: WORDPRESS_DB_NAME
          description:
            en_us: 'Container Variable: WORDPRESS_DB_NAME'
      volumes:
        - container: /var/www/html
          description:
            en_us: 'Container Path: /var/www/html'
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: casaos
      MYSQL_PASSWORD: casaos
      MYSQL_ROOT_PASSWORD: casaos
    volumes:
      - /DATA/.docker/AppData/$AppID/mysql:/var/lib/mysql
    x-casaos:
      envs:
        - container: MYSQL_DATABASE
          description:
            en_us: 'Container Variable: MYSQL_DATABASE'
        - container: MYSQL_USER
          description:
            en_us: 'Container Variable: MYSQL_USER'
        - container: MYSQL_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_PASSWORD'
        - container: MYSQL_ROOT_PASSWORD
          description:
            en_us: 'Container Variable: MYSQL_ROOT_PASSWORD'
      volumes:
        - container: /var/lib/mysql
          description:
            en_us: 'Container Path: /var/lib/mysql'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Initially started as a blogging tool in 2003, it has evolved into a highly flexible CMS that powers over 40% of the web (as of my last training data in 2022).
  tagline:
    en_us: WordPress
  developer: Automattic
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/wordpress.png
  thumbnail: ''
  title:
    en_us: WordPress
  category: BigBearCasaOS
  port_map: '12181'

