name: big-bear-chatpad
services:
  big-bear-chatpad:
    container_name: big-bear-chatpad
    image: ghcr.io/deiucanta/chatpad:f45cd53bc410412610c1ba1cbd84cd137d8e167d
    restart: unless-stopped
    ports:
      - '12013:80'
    x-casaos:
      ports:
        - container: '80'
          description:
            en_us: 'Container Port: 80'
x-casaos:
  architectures:
    - amd64
    - arm64
  main: big-bear-chatpad
  description:
    en_us: Recently, there has been a surge of UIs for ChatGPT, making it the new to-do app that everyone wants to try their hand at. Chatpad sets itself apart with a broader vision - to become the ultimate interface for ChatGPT users.
  tagline:
    en_us: Not just another ChatGPT user-interface!
  developer: deiucanta
  author: BigBearTechWorld
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-universal-apps/apps/chatpad/logo.jpeg
  thumbnail: ''
  title:
    en_us: Chatpad
  category: BigBearCasaOS
  port_map: '12013'

